(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.webFontTxtInst = {}; 
var loadedTypekitCount = 0;
var loadedGoogleCount = 0;
var gFontsUpdateCacheList = [];
var tFontsUpdateCacheList = [];
lib.ssMetadata = [
		{name:"index_atlas_", frames: [[0,775,140,77],[0,0,320,480],[0,704,161,69],[219,703,127,120],[219,482,135,219],[0,482,217,220]]}
];



lib.updateListCache = function (cacheList) {		
	for(var i = 0; i < cacheList.length; i++) {		
		if(cacheList[i].cacheCanvas)		
			cacheList[i].updateCache();		
	}		
};		

lib.addElementsToCache = function (textInst, cacheList) {		
	var cur = textInst;		
	while(cur != null && cur != exportRoot) {		
		if(cacheList.indexOf(cur) != -1)		
			break;		
		cur = cur.parent;		
	}		
	if(cur != exportRoot) {		
		var cur2 = textInst;		
		var index = cacheList.indexOf(cur);		
		while(cur2 != null && cur2 != cur) {		
			cacheList.splice(index, 0, cur2);		
			cur2 = cur2.parent;		
			index++;		
		}		
	}		
	else {		
		cur = textInst;		
		while(cur != null && cur != exportRoot) {		
			cacheList.push(cur);		
			cur = cur.parent;		
		}		
	}		
};		

lib.gfontAvailable = function(family, totalGoogleCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], gFontsUpdateCacheList);		

	loadedGoogleCount++;		
	if(loadedGoogleCount == totalGoogleCount) {		
		lib.updateListCache(gFontsUpdateCacheList);		
	}		
};		

lib.tfontAvailable = function(family, totalTypekitCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], tFontsUpdateCacheList);		

	loadedTypekitCount++;		
	if(loadedTypekitCount == totalTypekitCount) {		
		lib.updateListCache(tFontsUpdateCacheList);		
	}		
};
// symbols:



(lib.interstetititialorangefruite = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.interstitialatasteoftable = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.interstitialcranberries = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();



(lib.interstitialgreens = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(3);
}).prototype = p = new cjs.Sprite();



(lib.interstitialmashedpotatoes = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(4);
}).prototype = p = new cjs.Sprite();



(lib.interstitialturkey = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(5);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.whiterectanglefade = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ege2AqlMAAAhVJMA9tAAAMAAABVJg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.whiterectanglefade, new cjs.Rectangle(-197.4,-272.4,395,545), null);


(lib.trynewflavors = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgMBaIgTgDIgFADIgGABIgDgBIgDgCQgGgFgFgOQgFgOAAgNQAAgFADgEQADgEAEAAQAIAAAIAOIAHAKQAFAIAJADQAJAFAJAAQAMgBAGgFQAHgGAAgKQAAgPgcgNIgKgFQgbgOgJgKQgKgLAAgQQAAgXAPgOQAQgPAaAAIAKABIANADIAIgEIAGgBQAIAAAIAOQAIAOAAAPQAAAFgDAEQgDAEgEgBQgFABgDgEQgEgDgFgIQgHgMgHgDQgGgEgKgBQgKAAgFAGQgHAFABAKQAAAHAGAGQAGAHAVAKIACABQAwAYAAAbQAAAZgTAPQgSARgcAAg");
	this.shape.setTransform(122.5,1.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("Ag0BWQgIgDAAgIQAAgFAIgEIAFgCQAEgCACgGQACgFAAgOIAAgLIAAgOIAAgLQAAgegCgKQgBgKgEgCIgIgDQgKgDAAgGQAAgEADgDQADgDAIgDIAXgHIAQgEQAIABADAXIAAADIABABQAJgOAJgHQAKgIAKAAQAMAAAHAIQAHAHAAAMQAAAMgFAHQgGAHgKAAIgIgBIgIgGIgEgGQgBgFgCAAQgMAAgFARQgEAQAAA0QAAAPABAHQACAIAFACIAHACQAKADAAAIQAAAGgJADQgKACgXABQgagBgJgCg");
	this.shape_1.setTransform(108.9,1.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("Ag+BBQgZgaAAgmQAAgmAagaQAagaAmAAQAlAAAYAYQAYAYAAAmQAAAngaAbQgZAbglAAQgmAAgYgZgAgggzQgLAOAAAXQAAAiAPAXQAOAXAUAAQARAAALgOQAKgPAAgXQAAghgOgXQgPgXgUAAQgRAAgKAOg");
	this.shape_2.setTransform(92.2,1.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgSBIQgKgQgYg5IgKgaQgNgggHgEIgGgCQgJgEgBgHQABgHAIgCQAJgDAcAAQAYAAAIADQAJACAAAHIgBAGIgEADIgFACQgIADABAEIADAOIAOAhIAOAhQADAIACAAQADAAADgFIAIgPIATgrQAFgRAAgFIgBgHIgEgDIgFgCQgHgDgBgGQABgHAHgCQAIgDAWAAQARAAAIADQAHACAAAHQABAHgKADIgFACQgJAEgOAiIgFAKIgHAQQgnBZgLAAQgHAAgKgRg");
	this.shape_3.setTransform(73.6,1.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAfBRIgKgJIgHAEQgUAOgWAAQgZAAgQgOQgQgPAAgYQABgbATgPQAVgPAkAAQAIAAAEACQAFADAAAGQAAAKgMAAQgQAAgLAIQgLAIAAAPQAAAOAJAIQAKAIAPAAQAQAAAHgHQAHgIAAgSIAAhBQAAgPgGgIQgHgIgMAAQgIAAgHADQgHAEgHAIIgEAEQgLAOgLAAQgHAAgEgFQgEgEAAgIQAAgQAUgLQAUgLAgAAQASAAANAFQAPAFAHAKQAFAGACALQADAKAAAZIAAA3QAAAKABAFQACAEADABIAGACQALADgBAGQAAAIgLAHQgLAGgQAAQgIAAgIgJg");
	this.shape_4.setTransform(55.6,1.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgcB8QgJgCAAgIQAAgGAHgDIAJgFQADgCABgLIABgiIAAgbIAAggIAAgNQAAgsgBgMQgCgNgEgCIgKgDQgLgDAAgGQAAgFADgDQAEgCAMgFIAXgHIARgCQAFAAACAEQADADAAAIIgBANQgCA9AAA+IABA8QABAMADADIAKAFQAIAEAAAGQAAAGgJADQgIADgXAAQgZAAgIgDg");
	this.shape_5.setTransform(41,-2.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AhXB8QgJgEAAgIQgBgGAKgEQAJgDABgCQACgEACgaIAChDIgCg/QgCgbgCgDQgBgDgJgDQgKgEABgHQgBgHAJgDQAHgCAeAAIBpAAIARgCIAJgBIAEABIADACQAEAHADALQADAMABAJQgBAIgDAEQgCAEgGAAQgGAAgGgMIgGgIQgEgGgHgDQgIgCgLAAIgYAAQgQAAgJABQgIACgDAFQgDADgBALIgBAhIAAAPQAAAIABACQABACAFAAIAcAAQAOAAAFgEQAGgEABgLIABgDQACgSAJAAQAIAAADAKQACAJAAAhQAAAggCAKQgDAJgIAAQgJAAgCgTIgBgCQgBgLgGgEQgFgEgOAAIgcAAQgFAAgBADQgBADAAAKIAAAOIABAwQAAALAEACIAIAEQAKAEAAAHQAAAHgKAEQgJADgbAAQgcAAgJgDg");
	this.shape_6.setTransform(26.3,-2.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAKATIgVg2QgJgYgJgEIgFgCQgJgEAAgHQAAgHAIgCQAJgDAbAAQAYAAAIADQAJACAAAHIgBAGIgEADIgFACQgIADAAAEIADALIAPAkIAPAhQADAIACAAQADAAADgFIAIgPIATgrQAFgRAAgFIgBgHIgEgDIgFgCQgHgDgBgGQABgHAHgCQAIgDAWAAQARAAAIADQAHACAAAHQABAHgKADIgFACQgJAEgPAkIgEAIIgHAQQgoBZgLAAQgMAAgehGgAhlAKIgFgLIgMgdQgLgdgHgEIgGgCQgJgEgBgHQABgHAIgCQAJgDAcAAQAYAAAIADQAJACAAAHIgBAGIgEADIgFACQgIADAAAEIAEAOIAOAhIAOAgQAEAJACAAQAGAAAEgLIAGgMIAEgFQACgCAEAAQAEAAADACQACADAAAEQAAAFgEAJQgTAogHANQgIANgHAAQgMAAgihPg");
	this.shape_7.setTransform(-7.8,1.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("Ag3BBQgZgZAAglQAAgoAZgaQAagaAmAAQAhAAAUATQATATAAAgQAAALgDADQgDAEgNAAIhBAAQgGAAgDgDQgDgDAAgFQAAgEADgDQADgCAFAAIAkAAIAJgBQACgCAAgEQAAgQgLgMQgMgLgPAAQgVAAgKASQgJASAAAZQAAAaANAUQAOAUAVAAQANAAAJgDQAJgDAIgGIAGgFQAJgHAFAAQADAAADADQACACAAAEQAAAEgEAGQgEAGgIAGQgPAMgOAGQgOAFgQAAQgkAAgYgZg");
	this.shape_8.setTransform(-31.4,1.6);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AAPAwIgFgIIglguIgjgtIgPgQIAAALIAAAYIAAAQQAABLACAUQACATAFAAQAFAAAFAEQAFAEAAAEQAAAIgIADQgJADgUAAQgVAAgIgDQgIgDAAgIQAAgGAKgEQAJgDABgDQADgDABgZIABhEIgBhAQgCgagCgDQgBgDgJgEQgKgDAAgHQAAgHAIgCQAIgDAVAAIATABIAHACIAZAeIAiAtIAmAvIAbAgIASAUIABgHIAAgNIgBhVQgCgjgBgGIgCgEIgEgCQgKgEgCgCQgDgDAAgEQAAgHAHgCQAHgDAYAAQAVAAAHADQAIACAAAHQAAAEgCACIgHAFIgEABQgHADgBAEQgCAHgBAiIgBBoIAAAgIAAAWQAAANgBADQgCADgFAAQgSAAg+hNg");
	this.shape_9.setTransform(-54,-2.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AhPByQgIgHAAgLQAAgIAGgHQAGgGAIAAIAIABIAFAEIAFAHQAEAHAEAAQAJAAAJgNQAJgNAAgNQAAgPgMgcIgCgEIgcg8IgQghQgDgGgKgFIAAAAQgGgCgCgCQgCgDAAgEQAAgHAJgDQAJgDAZAAQAaAAAIADQAIACAAAHIgBAGIgDADIgGADQgHACAAADIAEANIAOAjIANAgQAFAJACAAQACAAAEgJIALgbIANgiQAEgMAAgFQAAgFgKgFQgKgGAAgEQAAgGAIgDQAIgCAUAAQAVAAAHADQAHACAAAHQAAAHgKACIgHACQgKAGgLAdIgFANIgWA3QgcBIgSAWQgSAVgZAAQgNAAgIgHg");
	this.shape_10.setTransform(-85.6,5);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("Ag0BWQgIgDAAgIQAAgFAIgEIAFgCQAEgCACgGQACgFAAgOIAAgLIAAgOIAAgLQAAgegCgKQgBgKgEgCIgIgDQgKgDAAgGQAAgEADgDQADgDAIgDIAXgHIAQgEQAIABADAXIAAADIABABQAJgOAJgHQAKgIAKAAQAMAAAHAIQAHAHAAAMQAAAMgFAHQgGAHgKAAIgIgBIgIgGIgEgGQgBgFgCAAQgMAAgFARQgEAQAAA0QAAAPABAHQACAIAFACIAHACQAKADAAAIQAAAGgJADQgKACgXABQgagBgJgCg");
	this.shape_11.setTransform(-100.6,1.4);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgkB7QgJgDgBgIQAAgHAKgDQAKgEABgCQACgDABgdIABhRIgBgtIgBgcQAAgFgEgBQgCgCgIAAIgHAAQgMAAgHADQgGADgFAHIgFALIgGAMIgFAFQgDACgCAAQgGAAgCgEQgCgFAAgKQgBgXAGgOQAFgOAJAAIABAAQAOACAVAAIBlAAQAVAAANgCIACAAQAJAAAGAOQAEAOAAAXQAAAKgCAFQgCAEgGAAIgFgCIgGgFIgFgMIgFgLQgFgHgGgDQgIgDgMAAIgGAAQgIAAgCACQgEABAAAFIgCAcIAAAtIABBRQABAdACADQACACAJAEQAKADAAAHQgBAIgJADQgKADgbAAQgaAAgKgDg");
	this.shape_12.setTransform(-118.8,-2.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.trynewflavors, new cjs.Rectangle(-132.1,-24.9,264.2,45.1), null);


(lib.thanksgiving = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhABxQgWgOABgTQAAgIAEgGQAFgGAKAAQAGAAAEAEQAEAFADAIQAEAMALAIQALAHAVAAQAWAAAPgJQAPgJABgNQgBgIgFgFQgGgEgLAAIgUABIgaACQgeAAgRgLQgRgKAAgOQAAgJAHgIQAFgIANgHQgKgJgFgLQgFgLAAgOQAAgcAVgSQAWgTAgAAIARABIAbAGQAGAAAHgEQAIgDALgHIAFAFIACAGQABAHgGAHQgFAHgLAFIAGAOIACAOQAAAdgWASQgUARgiAAIgSgBIgQgEIgFAHIgCAGQgBAIAJAEQAIAEARAAIAZgCIAbgCQAYAAANAKQANAKABASQgBAcgbASQgbASgpAAQggAAgXgNgAgchVQgJALAAARQAAASAJALQAIAKAPAAQANAAAKgKQAKgLAAgSQAAgRgKgLQgJgLgOAAQgNAAgKALg");
	this.shape.setTransform(97,6.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAXBWQgIgDAAgGQAAgHAIgDIAHgDQAEgCABgIQACgHAAgTQAAg2gHgOQgHgOgSAAQgJAAgIAGQgIAFgFAJQgEAIgBANQgCANAAAiQAAARACAGQABAFAEACIAGADQAJADAAAHQAAAGgIADQgJADgWgBQgbABgIgDQgJgDAAgHQAAgHAJgCIAEgDQAEgCACgFQACgHAAgNIAAgMIAAgNIAAgRQAAgcgCgHQgBgJgDgCIgIgDQgLgDAAgGQAAgEADgDQAEgDAHgDIAZgIIASgDQAFAAACADQACADAAAFIAAALIAAACIABABIABgBIABAAIAEgDIAEgEQASgRAVgBQANAAALAGQAMAFAIAKQAIAJADANQADAOAAAbIAAAWIAAAMIAAAKQAAAMACAFQACAFAEACIAEADQAJACAAAHQAAAHgIADQgIACgbAAQgYABgIgDg");
	this.shape_1.setTransform(76.9,3.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgeB8QgJgDAAgIQAAgGAJgDIAEgCQAEgCACgGQACgGAAgNIAAgMIAAgNIAAgSQAAgcgCgHQgBgIgDgCIgIgDQgKgDAAgGQAAgEACgDQAEgDAHgDIAagIIASgEQAFAAACAEQABADAAAIIAAAKIAAAIIgBArIAAABIgBArQAAAQACAHQABAHAEACIAGACQAJAEAAAGQABAHgJADQgJACgWAAQgaAAgIgCgAgVhWQgHgGAAgJQAAgKAIgHQAIgHAMAAQAKAAAHAGQAIAHAAAJQAAAJgIAHQgIAHgMAAQgLAAgHgGg");
	this.shape_2.setTransform(61.7,0.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgSBIQgKgQgYg5IgKgaQgNgggHgEIgGgCQgJgEgBgHQABgHAIgCQAJgDAcAAQAYAAAIADQAJACAAAHIgBAGIgEADIgFACQgIADAAAEIAEAOIAOAhIAOAhQAEAIABAAQADAAADgFIAIgPIATgrQAFgRAAgFIgBgHIgEgDIgFgCQgHgDgBgGQABgHAHgCQAIgDAWAAQARAAAIADQAHACAAAHQABAHgKADIgFACQgJAEgPAiIgEAKIgHAQQgnBZgLAAQgHAAgKgRg");
	this.shape_3.setTransform(48,4.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgeB8QgJgDAAgIQAAgGAJgDIAEgCQAFgCABgGQADgGAAgNIgBgMIAAgNIAAgSQAAgcgCgHQAAgIgEgCIgIgDQgKgDAAgGQAAgEACgDQAEgDAHgDIAagIIASgEQAEAAACAEQACADAAAIIAAAKIAAAIIgBArIAAABIgBArQAAAQABAHQACAHAEACIAHACQAIAEABAGQAAAHgJADQgJACgWAAQgaAAgIgCgAgVhWQgHgGAAgJQAAgKAIgHQAIgHAMAAQAKAAAIAGQAHAHAAAJQAAAJgIAHQgIAHgMAAQgKAAgIgGg");
	this.shape_4.setTransform(34,0.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("Ag/BxQgXgOAAgTQABgIAFgGQAEgGAJAAQAHAAAFAEQAEAFACAIQAEAMALAIQALAHAVAAQAWAAAQgJQAPgJAAgNQAAgIgGgFQgGgEgLAAIgTABIgaACQgfAAgRgLQgQgKAAgOQAAgJAFgIQAHgIAMgHQgKgJgFgLQgFgLAAgOQAAgcAVgSQAWgTAgAAIARABIAbAGQAGAAAHgEQAIgDALgHIAGAFIABAGQAAAHgFAHQgGAHgJAFIAFAOIABAOQABAdgWASQgUARgiAAIgSgBIgQgEIgFAHIgDAGQAAAIAJAEQAIAEARAAIAagCIAagCQAZAAAMAKQAOAKAAASQAAAcgcASQgbASgoAAQgiAAgVgNgAgbhVQgKALAAARQAAASAJALQAJAKAOAAQAOAAAJgKQAKgLAAgSQAAgRgJgLQgKgLgOAAQgOAAgIALg");
	this.shape_5.setTransform(20.7,6.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgMBaIgTgEIgFAEIgGABIgDgBIgDgDQgGgEgFgOQgFgOAAgNQAAgGADgDQADgEAEAAQAIAAAIAOIAHAKQAFAHAJAFQAJADAJABQAMgBAGgFQAHgGAAgJQAAgPgcgOIgKgFQgbgNgJgLQgKgLAAgRQAAgWAPgOQAQgPAaAAIAKABIANADIAIgEIAFgBQAJAAAIAOQAIANAAAPQAAAGgCAEQgEADgEAAQgEAAgEgDQgEgDgFgIQgHgMgHgEQgGgDgKAAQgKgBgFAGQgHAFABAKQAAAHAGAGQAGAHAVAKIABABQAxAXAAAcQAAAYgTARQgSAQgcAAg");
	this.shape_6.setTransform(3.3,4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AA4B/IgHgCQgHgDgRgUIgHgKIgDgEQgqg2gDAAQgBAAAAAAQgBAAAAABQAAAAAAAAQgBABAAAAIAAAHIAAAHIABAlQABAKACAEIAKAEQAIADAAAHQAAAGgJADQgIADgXAAQgaAAgIgDQgJgDAAgHQAAgGAJgDIAEgCQAFgCACgJQABgIAAgUIAAgWIAAgbIAAgUIgBhAQgBgRgDgCQgCgDgHgCIgGgBIgHgDIgBgGQAAgEADgDQAEgDAMgEIAXgGIASgDQAFAAACAEQADACAAAJIgBAhIgBAtIAAArIAAAJQABAAAAAAQAAAAAAABQABAAAAAAQAAAAABAAIAHgEIANgKIAQgRQAEgEAAgDQAAgBgGgEQgFgDAAgFQAAgJAIgCQAJgEAYAAQAQAAAIAEQAIADAAAHQAAAHgNADQgMAEgGADQgGADgPAPIgCACIgGAHIgCADQAAADAPAVIACACIAeAkQAMAPAHAEQAEADALAEQALADAAAHQAAAIgIADQgIADgSAAg");
	this.shape_7.setTransform(-13.1,0);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAXBWQgIgDAAgGQAAgHAIgDIAHgDQAEgCABgIQACgHAAgTQAAg2gHgOQgHgOgSAAQgJAAgIAGQgIAFgFAJQgEAIgBANQgCANAAAiQAAARACAGQABAFAEACIAGADQAJADAAAHQAAAGgIADQgJADgWgBQgbABgIgDQgJgDAAgHQAAgHAJgCIAEgDQAEgCACgFQACgHAAgNIAAgMIAAgNIAAgRQAAgcgCgHQgBgJgDgCIgIgDQgLgDAAgGQAAgEADgDQAEgDAHgDIAZgIIASgDQAFAAACADQACADAAAFIAAALIAAACIABABIABgBIABAAIAEgDIAEgEQASgRAVgBQANAAALAGQAMAFAIAKQAIAJADANQADAOAAAbIAAAWIAAAMIAAAKQAAAMACAFQACAFAEACIAEADQAJACAAAHQAAAHgIADQgIACgbAAQgYABgIgDg");
	this.shape_8.setTransform(-33.7,3.9);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AAfBRIgKgJIgHAEQgVAOgVAAQgZAAgQgOQgQgPAAgYQABgbATgPQAVgPAkAAQAIAAAEACQAFADAAAGQAAAKgMAAQgRAAgKAIQgLAIAAAPQAAAOAJAIQAKAIAPAAQAQAAAHgHQAHgIAAgSIAAhBQAAgPgHgIQgGgIgMAAQgIAAgHADQgHAEgHAIIgEAEQgKAOgMAAQgHAAgEgFQgEgEAAgIQAAgQAUgLQAUgLAfAAQATAAANAFQAOAFAIAKQAFAGACALQACAKABAZIAAA3QAAAKABAFQACAEADABIAGACQALADgBAGQAAAIgLAHQgMAGgPAAQgIAAgIgJg");
	this.shape_9.setTransform(-53,4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAYB8QgJgDAAgGQAAgHAJgDIAHgDQAEgCABgHQACgIAAgSQAAg4gHgNQgHgOgSAAQgJAAgIAGQgJAFgEAJQgEAHgBANQgCAOAAAhQAAASACAGQABAFAEACIAGADQAJADAAAHQAAAGgJADQgIADgWAAQgcAAgIgDQgIgDAAgHQAAgGAIgDIAFgCQAEgDACgHQACgHAAgTIAAgcIAAgbIgBhNQgBgTgDgEQgBgCgLgDQgKgDAAgGQAAgFAEgDQAFgDAPgGIARgFIAQgCQAGAAACAEQADADAAAIIgBAHIgBBFIAAAIIABAEIACACIAEgEIAGgHQAJgJAKgEQAJgEAKAAQAeAAAPATQAOATAAAmIAAAQIABAfIAAAKQAAAJABAEQACAEAEACIAEACQAJADAAAGQAAAHgIADQgJADgbAAQgXAAgIgDg");
	this.shape_10.setTransform(-73,0);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgkB7QgKgDAAgIQAAgHAKgDQAJgEACgCQACgDABgdIABhRIAAgtIgCgcQgBgFgDgBQgCgCgIAAIgHAAQgMAAgHADQgGADgFAHIgGALIgEAMIgGAFQgCACgDAAQgGAAgCgEQgDgFAAgKQAAgXAGgOQAFgOAJAAIACAAQANACAVAAIBlAAQAVAAAOgCIABAAQAJAAAGAOQAEAOAAAXQAAAKgBAFQgDAEgGAAIgGgCIgEgFIgGgMIgFgLQgEgHgIgDQgGgDgNAAIgHAAQgGAAgEACQgDABAAAFIgBAcIgBAtIABBRQABAdACADQACACAJAEQAKADgBAHQAAAIgKADQgJADgbAAQgaAAgKgDg");
	this.shape_11.setTransform(-94.2,0.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.thanksgiving, new cjs.Rectangle(-107.5,-22.5,215.1,45.1), null);


(lib.TASTINGEVENTNEARYOU = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgSA3QgKgDgGgHQgHgGgEgJIgDgJIgBgLIAAgeIAAgfQAAgBAAAAQAAgBABAAQAAgBAAAAQAAAAABgBIADgBIAFgBIADAAIAFABQABABAAAAQABABAAAAQAAAAABABQAAABAAAAIAAA6QAAAGACAGQACAGADAFQAEAFAGACQAFADAGAAQAHAAAGgDQAFgCAEgFQAEgEACgGQABgHAAgGIAAg5QAAgEADgBIAFgBIAEgBIAEABIAEACQAAAAAAAAQABABAAAAQAAABAAAAQAAABAAABIAAA9IgBALIgDAJQgEAJgHAGQgGAHgJADQgJAEgLAAQgJAAgJgEg");
	this.shape.setTransform(103.8,-0.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgLA5IgMgDIgKgFIgJgHQgIgIgFgLIgEgLIgBgMIABgLIAEgLQAFgLAIgIIAJgHIAKgGIAMgDIALgBIAMABIAMADQALAFAIAIQAIAIAFALQAFALAAALIgCAMIgDALQgFALgIAIQgIAIgLAEIgMADQgGACgGAAQgFAAgGgCgAgOgjQgHADgFAFQgGAGgDAGQgDAIAAAHQAAAIADAIQADAGAGAFQAFAGAHADQAHADAHAAQAHAAAHgDQAHgDAGgGQAFgFADgGQAEgIAAgIQAAgHgEgIQgDgGgFgGQgGgFgHgDQgHgDgHAAQgHAAgHADg");
	this.shape_1.setTransform(90.9,-0.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgEA7IgDgBIgBgBIgBgCIAAgoIgBgHIgEgGIgggxIAAgBQAAgBAAAAQAAgBAAAAQABgBAAAAQAAAAABgBIADgDIAEgCIAEAAIADAAIADADIAWAkIADACIACABIACgBIADgCIAXgkIACgDIAEgBIAEABIAEABIAEADIABADIAAACIgBABIggAyIgDAGIgBADIAAACIAAAoQgCAEgDABIgGAAg");
	this.shape_2.setTransform(79.1,-0.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAcA6IgCgCIgDgBIgBgBIgUgdIgCgFIgFgBIgOAAQgBAAAAABQgBAAAAAAQgBAAAAAAQgBABgBAAQAAAAAAABQAAAAgBABQAAAAAAABQAAAAAAABIAAAcQAAABAAAAQAAAAAAABQgBAAAAAAQAAABAAAAIgFABIgEABIgEAAQgDAAgCgCQgCgBAAgEIABhnQAAAAAAgBQAAAAAAgBQAAAAAAgBQABAAAAAAIADgBIAwAAQAIgBAHADQAIADAGAFQAFAFADAHQADAHAAAJQAAAJgDAHQgFAEgDAEIgIAGQgEACAAADIAAACIAEAHIAHAJIAGAJIADAGQAAAAgBAAQAAABAAAAQAAABAAAAQgBABAAAAIgEACIgDACIgFABgAgXgkQAAABgBAAQAAABgBAAQAAABAAAAQAAABAAABIAAAZQAAABAAABQAAABAAAAQABABAAAAQABABAAAAQADABADAAIAWAAIAIgBQAEgBADgCQADgCACgEQACgDAAgFQgBgKgGgEQgDgCgEgCQgDgBgFAAIgWAAQgDAAgDABg");
	this.shape_3.setTransform(63.8,-0.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAsA5IgCAAIgHAAQgDgBgBgDIgGgPIgCgDIgEgBIglAAIgBABIgCABIgCABIgBABIgGAPIgCACIgDABIgDABIgDAAIgEAAIgDAAIgDgCQAAAAgBAAQAAAAAAgBQAAAAAAAAQgBAAAAgBIAvhqQAAAAABgBQAAAAAAAAQABgBAAAAQAAAAABAAIADgBIAFAAQAAAAABABQABAAAAAAQABABAAAAQAAABAAAAIAtBqIAAABQAAAAAAAAQAAABAAAAQAAAAAAABQgBAAAAAAIgDABgAgBgRIgBACIgBADIgCAFIgDAHIgDAFIgBAFIgBACIABADIACABIAWAAIACgBIABgCIgCgFIgEgJIgDgJIgDgGIgDgBg");
	this.shape_4.setTransform(52,-0.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgmA4IgDgBQgBAAAAAAQgBgBAAAAQAAAAAAgBQAAAAAAAAIAAhpQAAAAAAAAQAAgBAAAAQAAAAABgBQAAAAAAAAIAEgBIBOAAIADABIABAEIABAEIAAADIgBAFIgEACIg6AAIgDACIgCAEIAAAPQAAABABAAQAAABAAAAQAAABAAAAQABAAAAABQAAAAABAAQAAAAABABQAAAAABAAQAAAAABAAIAlAAQAAAAABAAQAAAAABAAQAAABAAAAQAAAAAAAAIACAEIAAAFIAAACQAAAFgEABIgkAAQgBAAAAABQgBAAgBAAQAAAAgBABQAAAAgBAAQAAABAAAAQgBABAAABQAAAAAAABQgBAAAAABIAAARQAAAAABABQAAAAAAABQAAAAAAABQABAAAAAAQAAABABAAQAAAAABABQAAAAABAAQAAAAABAAIA5AAQAEACAAAFIAAADIAAAFIgCADQAAAAAAABQAAAAgBAAQAAAAAAAAQgBAAAAAAg");
	this.shape_5.setTransform(41.6,-0.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAhA7QgCgBgCgDIgug/QAAAAgBgBQAAAAAAAAQgBAAAAAAQgBAAAAAAIgDABQgBAAAAABQAAAAAAAAQgBABAAAAQAAABAAAAIAAA6QgBACgDABIgFABIgHAAQgDgBgCgDIAAhrQAAAAAAgBQAAAAABAAQAAgBAAAAQAAAAABAAIADgCIAEgBIADAAQAFAAADAEIAuA9IADABIACAAIABgCIAAg6QAAAAABgBQAAAAAAgBQAAAAABAAQAAAAABAAIADgCIAEAAIAEAAQAFAAACAEIAABsQAAABgBAAQAAABAAAAQgBABAAAAQgBAAAAABQgBAAAAAAQgBAAAAABQgBAAgBAAQAAAAgBAAg");
	this.shape_6.setTransform(29.5,-0.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgBA5IgGgBQgCgBAAgDIAAhTQAAgBAAgBQAAAAgBgBQAAAAAAgBQAAAAgBgBQgBgBgEAAIgJAAIgJAAIgEAAQgDAAgCgCIgBgGIAAgDIABgEIABgDIAEgBIBNAAQAEAAABACIABAGIAAACIgBAFIgCADQAAAAAAABQgBAAAAAAQAAAAgBAAQAAAAgBAAIgWAAIgFABQAAABgBAAQAAABAAAAQAAABgBABQAAAAAAABIAABSIgBAEIgDABIgEABg");
	this.shape_7.setTransform(14.1,-0.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAhA7QgCgBgCgDIgug/QAAAAgBgBQAAAAAAAAQgBAAAAAAQgBAAAAAAIgDABQgBAAAAABQAAAAAAAAQgBABAAAAQAAABAAAAIAAA6QgBACgDABIgFABIgHAAQgDgBgCgDIAAhrQAAAAAAgBQAAAAABAAQAAgBAAAAQAAAAABAAIADgCIAEgBIADAAQAFAAADAEIAuA9IADABIACAAIABgCIAAg6QAAAAABgBQAAAAAAgBQAAAAABAAQAAAAABAAIADgCIAEAAIAEAAQAFAAACAEIAABsQgBABAAAAQAAABgBAAQAAABAAAAQgBAAAAABQgBAAAAAAQgBAAAAABQgBAAgBAAQAAAAgBAAg");
	this.shape_8.setTransform(3.4,-0.4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AglA4IgEgBQgBAAAAAAQgBgBAAAAQAAAAAAgBQgBAAAAAAIAAhpQAAAAABAAQAAgBAAAAQAAAAABgBQAAAAAAAAIAEgBIBPAAIACABIABAEIAAAEIAAADIgBAFIgCACIg7AAIgDACIgBAEIAAAPQAAABAAAAQAAABAAAAQAAABAAAAQABAAAAABQAAAAABAAQAAAAABABQAAAAABAAQAAAAABAAIAlAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAABAAIABAEIAAAFIAAACQAAAFgEABIglAAQAAAAgBABQAAAAgBAAQAAAAAAABQgBAAAAAAQgBABAAAAQgBABAAABQAAAAAAABQAAAAAAABIAAARQAAAAAAABQAAAAAAABQAAAAAAABQABAAAAAAQAAABABAAQAAAAABABQAAAAABAAQAAAAABAAIA6AAQADACAAAFIAAADIgBAFIAAADQgBAAAAABQAAAAgBAAQAAAAAAAAQgBAAAAAAg");
	this.shape_9.setTransform(-7.5,-0.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgBA4IgEgIIgFgNIgIgQIgIgSIgIgRIgGgPIgEgMIgCgFIABgDIAEgDIAEgCIAEAAQABAAAAAAQABAAAAAAQABABAAAAQABAAABAAIACAFIAYA4IABABIABABQAAAAABAAQAAAAABgBQAAAAAAAAQABgBAAgBIAXg4IADgEQABAAAAgBQABAAAAAAQABAAAAAAQABgBABAAIADABIAFABIADADQABAAAAAAQAAABABAAQAAABAAAAQAAAAAAABIgCAFIgFALIgGAQIgIARIgIATIgIAQIgFAOIgDAGIgBACIgBABQAAAAAAgBQgBAAAAAAQAAAAAAgBQAAAAAAAAg");
	this.shape_10.setTransform(-18.5,-0.4);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgmA4IgDgBQgBAAAAAAQgBgBAAAAQAAAAAAgBQgBAAAAAAIAAhpQAAAAABAAQAAgBAAAAQAAAAABgBQAAAAABAAIADgBIBPAAIACABIABAEIAAAEIAAADIgBAFIgCACIg7AAIgDACIgBAEIAAAPQAAABAAAAQAAABAAAAQAAABAAAAQABAAAAABQAAAAABAAQAAAAABABQAAAAABAAQAAAAABAAIAlAAQAAAAABAAQAAAAABAAQAAABAAAAQAAAAABAAIABAEIAAAFIAAACQAAAFgEABIglAAQAAAAgBABQAAAAgBAAQAAAAgBABQAAAAgBAAQAAABAAAAQgBABAAABQAAAAAAABQAAAAAAABIAAARQAAAAAAABQAAAAAAABQAAAAAAABQABAAAAAAQAAABABAAQAAAAABABQAAAAABAAQAAAAABAAIA6AAQADACAAAFIAAADIgBAFIgBADQAAAAAAABQAAAAgBAAQAAAAAAAAQgBAAAAAAg");
	this.shape_11.setTransform(-28.4,-0.4);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgIA6QgGgBgGgDQgFgCgFgDIgJgHIgIgIIgFgKQgFgMAAgMQAAgFABgGQABgGADgGQAFgKAIgIIAJgHIAKgGIAMgDIALgBIANACQAGABAGACQAMAGAJAKIAAACIgBADIgEAFIgEADIgEABQgCAAgDgCIgGgFIgJgGQgFgCgIAAQgHAAgHADQgHADgGAFQgFAGgDAHQgDAHAAAHQAAAIADAHQADAHAFAFQAGAGAHADQAHADAHAAIAIgBIAIgBIAGgEQAEgCACgEIAAgCQAAgBAAAAQAAgBAAAAQAAgBgBAAQAAAAAAgBIgEgBIgUAAQgBAAAAAAQgBAAAAAAQAAAAgBAAQAAgBAAAAIgCgDIAAgFIAAgDIABgFIADgCIAwAAIABABIACABQACAFAAAGIAAAEIgBAFQgDAJgGAGQgGAHgGAFQgIAEgIACQgIADgJAAIgLgBg");
	this.shape_12.setTransform(-46.2,-0.4);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AAhA7QgCgBgCgDIgug/QAAAAgBgBQAAAAAAAAQgBAAAAAAQgBAAAAAAIgDABQgBAAAAABQAAAAAAAAQgBABAAAAQAAABAAAAIAAA6QgBACgDABIgFABIgHAAQgDgBgCgDIAAhrQAAAAAAgBQAAAAABAAQAAgBAAAAQAAAAABAAIADgCIAEgBIADAAQAFAAADAEIAuA9IADABIACAAIABgCIAAg6QAAAAABgBQAAAAAAgBQAAAAABAAQAAAAABAAIADgCIAEAAIAEAAQAFAAACAEIAABsQAAABgBAAQAAABgBAAQAAABAAAAQgBAAAAABQgBAAAAAAQgBAAAAABQgBAAgBAAQAAAAgBAAg");
	this.shape_13.setTransform(-58.6,-0.4);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgDA7QgEAAgCgEIAAhtIACgCIAFgBIACAAIAEAAQAFAAABADIAABsIgCADIgEABIgEABg");
	this.shape_14.setTransform(-67.1,-0.4);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgBA5IgGgBQgCgBAAgDIAAhTQAAgBAAgBQAAAAgBgBQAAAAAAgBQAAAAgBgBQgBgBgEAAIgJAAIgJAAIgEAAQgDAAgCgCIgBgGIAAgDIABgEIABgDIAEgBIBNAAQAEAAABACIABAGIAAACIgBAFIgCADQAAAAAAABQgBAAAAAAQAAAAgBAAQAAAAgBAAIgWAAIgFABQAAABgBAAQAAABAAAAQgBABAAABQAAAAAAABIAABSIgBAEIgDABIgEABg");
	this.shape_15.setTransform(-74.3,-0.3);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgZA2QgMgEgJgJIgBgCIAAgCIABgEIADgEIAFgDIADgBQADAAADACIAHAFIAKAFQAFACAHAAIAIgBQAFAAAEgCQAEgCADgDQADgEgBgFQAAgEgCgDQgDgDgFgBIgMgDIgNgBIgNgDIgMgEQgFgEgDgGQgDgFAAgJQAAgJAEgGQAFgHAHgEQAGgEAIgCQAJgCAGAAIALABIAMACIALAFQAFADAEADIAAACIABACIgBAEIgEAEIgFACIgDABIgEAAQgGgFgGgDQgIgDgHAAIgHAAIgIADIgGAFQgDADAAAEQAAAGAGADQAFADAJABIAQACQAKACAHADQAJADAFAFQAGAGAAAMQAAAKgFAHQgFAHgHAFQgHAEgJADQgJACgHAAQgMAAgNgFg");
	this.shape_16.setTransform(-84.4,-0.4);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AAsA5IgCAAIgHAAQgCgBgCgDIgGgPIgCgDIgEgBIglAAIgBABIgCABIgCABIgBABIgGAPIgCACIgDABIgDABIgEAAIgDAAIgDAAIgDgCQAAAAgBAAQAAAAAAgBQAAAAAAAAQgBAAAAgBIAvhqQAAAAABgBQAAAAAAAAQABgBAAAAQAAAAABAAIADgBIAFAAQAAAAABABQABAAAAAAQABABAAAAQAAABAAAAIAtBqIAAABQAAAAAAAAQAAABAAAAQAAAAAAABQgBAAAAAAIgEABgAAAgRIgBACIgCADIgCAFIgDAHIgCAFIgCAFIgCACIACADIACABIAVAAIADgBIABgCIgCgFIgEgJIgDgJIgDgGIgDgBg");
	this.shape_17.setTransform(-95.3,-0.4);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgBA5IgGgBQgCgBAAgDIAAhTQAAgBAAgBQAAAAgBgBQAAAAAAgBQAAAAgBgBQgBgBgEAAIgJAAIgJAAIgEAAQgDAAgCgCIgBgGIAAgDIABgEIABgDIAEgBIBNAAQAEAAABACIABAGIAAACIgBAFIgCADQAAAAAAABQgBAAAAAAQAAAAgBAAQAAAAgBAAIgWAAIgFABQAAABgBAAQAAABAAAAQAAABgBABQAAAAAAABIAABSIgBAEIgDABIgEABg");
	this.shape_18.setTransform(-105.5,-0.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.TASTINGEVENTNEARYOU, new cjs.Rectangle(-112.2,-10.2,224.5,20.6), null);


(lib.savorysides = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgNBaIgSgDIgFADIgGABIgDgBIgEgCQgFgFgFgOQgFgOAAgNQAAgFADgEQADgEAEAAQAIAAAIAOIAHAKQAFAIAJADQAJAFAJAAQALgBAHgFQAHgGAAgKQAAgPgcgNIgKgFQgbgOgKgKQgJgLAAgQQAAgXAQgOQAPgPAaAAIALABIAMADIAIgEIAGgBQAIAAAIAOQAIAOAAAPQAAAFgDAEQgCAEgGgBQgEABgDgEQgEgDgGgIQgFgMgIgDQgHgEgJgBQgJAAgHAGQgFAFAAAKQgBAHAHAGQAGAHAUAKIADABQAwAYAAAbQAAAZgSAPQgTARgcAAg");
	this.shape.setTransform(92.1,1.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("Ag3BBQgZgZAAglQAAgoAZgaQAagaAmAAQAhAAAUATQATATAAAgQAAALgDADQgDAEgNAAIhBAAQgGAAgDgDQgDgDAAgFQAAgEADgDQADgCAFAAIAkAAIAJgBQACgCAAgEQAAgQgLgMQgMgLgPAAQgVAAgKASQgJASAAAZQAAAaANAUQAOAUAVAAQANAAAJgDQAJgDAIgGIAGgFQAJgHAFAAQADAAADADQACACAAAEQAAAEgEAGQgEAGgIAGQgPAMgOAGQgOAFgQAAQgkAAgYgZg");
	this.shape_1.setTransform(75.6,1.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AhLBpQgUgYAAglQAAgqAXgaQAXgaAlgBIAMACQAFACADADQADAEAAAFQAAAJgLAAIgFAAIgEgBQgTAAgMAQQgLAOAAAcQAAAdAMASQANASATABQASgBAKgJQAKgLAAgTIAAgvIAAhPQAAgMgDgFQgCgFgGgCIgFgCQgLgCAAgHQAAgEAEgEQAFgDANgEIATgGIAQgCQAGAAADADQACAEAAAHIAAAJIgCBqIABBIQABARADACIAMAEQAJACAAAGQAAAIgZAIIgRAFIgNABQgFAAgCgCQgCgDAAgGIAAgIIgBgDIgBgCIgFAEIgIAFQgKAJgJADQgKAEgKAAQghAAgUgXg");
	this.shape_2.setTransform(56.8,-2.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgeB8QgJgDABgIQgBgGAJgDIAEgCQAFgCACgGQABgGAAgNIAAgMIAAgNIAAgSQAAgcgBgHQgBgIgEgCIgIgDQgLgDAAgGQAAgEAEgDQADgDAIgDIAagIIARgEQAFAAABAEQADADAAAIIAAAKIgBAIIgBArIAAABIgBArQAAAQACAHQABAHAEACIAHACQAJAEAAAGQAAAHgJADQgIACgXAAQgZAAgJgCgAgVhWQgHgGAAgJQAAgKAIgHQAIgHAMAAQAKAAAIAGQAHAHAAAJQAAAJgIAHQgIAHgLAAQgLAAgIgGg");
	this.shape_3.setTransform(41,-2.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgqB9QgTgEgNgIQgGgEgFgOQgEgQAAgTQAAgIADgEQADgEAFAAQAIAAAJAQIAEAGQALAUANAJQANAIASAAQASAAANgLQANgLAAgRQAAgYgygWIgGgCQgqgSgNgQQgOgOAAgZQAAgfAXgUQAXgUAkAAIAUACIAYAFIAHgFIAGgBQAEAAADADQAEACADAHQAGAKAEAMQADALAAAJQAAAGgDADQgDADgEAAQgKAAgIgMIgDgEQgKgNgLgGQgMgGgOAAQgTAAgLAJQgLAJAAAQQAAAOAJAJQAKAKAkAQIAHACQAfAOAOALQAJAJAFALQAFANAAANQAAAjgYAUQgZAUgrAAQgVAAgTgEg");
	this.shape_4.setTransform(26.1,-2.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AhPByQgIgHAAgLQAAgIAGgHQAGgGAIAAIAIABIAFAEIAFAHQAEAHAEAAQAJAAAJgNQAJgNAAgNQAAgPgMgcIgCgEIgcg8IgQghQgDgGgKgFIAAAAQgGgCgCgCQgCgDAAgEQAAgHAJgDQAJgDAZAAQAaAAAIADQAIACAAAHIgBAGIgDADIgGADQgHACAAADIAEANIAOAjIANAgQAFAJACAAQACAAAEgJIALgbIANgiQAEgMAAgFQAAgFgKgFQgKgGAAgEQAAgGAIgDQAIgCAUAAQAVAAAHADQAHACAAAHQAAAHgKACIgHACQgKAGgLAdIgFANIgWA3QgcBIgSAWQgSAVgZAAQgNAAgIgHg");
	this.shape_5.setTransform(-1.9,5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("Ag0BWQgIgDAAgIQAAgFAIgEIAFgCQAEgCACgGQACgFAAgOIAAgLIAAgOIAAgLQAAgegCgKQgBgKgEgCIgIgDQgKgDAAgGQAAgEADgDQADgDAIgDIAXgHIAQgEQAIABADAXIAAADIABABQAJgOAJgHQAKgIAKAAQAMAAAHAIQAHAHAAAMQAAAMgFAHQgGAHgKAAIgIgBIgIgGIgEgGQgBgFgCAAQgMAAgFARQgEAQAAA0QAAAPABAHQACAIAFACIAHACQAKADAAAIQAAAGgJADQgKACgXABQgagBgJgCg");
	this.shape_6.setTransform(-16.9,1.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("Ag+BBQgZgaAAgmQAAgmAagaQAagaAmAAQAlAAAYAYQAYAYAAAmQAAAngaAbQgZAbglAAQgmAAgYgZgAgggzQgLAOAAAXQAAAiAPAXQAOAXAUAAQARAAALgOQAKgPAAgXQAAghgOgXQgPgXgUAAQgRAAgKAOg");
	this.shape_7.setTransform(-33.6,1.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgSBIQgKgQgYg5IgKgaQgMgggIgEIgGgCQgKgEAAgHQAAgHAJgCQAJgDAcAAQAYAAAIADQAJACAAAHIgBAGIgEADIgFACQgIADABAEIADAOIAOAhIANAhQAFAIABAAQADAAADgFIAHgPIAUgrQAFgRAAgFIgBgHIgEgDIgFgCQgHgDgBgGQABgHAHgCQAIgDAVAAQATAAAHADQAHACAAAHQABAHgKADIgGACQgHAEgPAiIgFAKIgHAQQgnBZgKAAQgIAAgKgRg");
	this.shape_8.setTransform(-52.1,1.8);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AAfBRIgJgJIgIAEQgVAOgVAAQgZAAgQgOQgQgPAAgYQABgbATgPQAVgPAkAAQAIAAAEACQAFADAAAGQAAAKgMAAQgRAAgKAIQgKAIAAAPQgBAOAKAIQAJAIAPAAQAQAAAHgHQAHgIAAgSIAAhBQAAgPgHgIQgGgIgMAAQgIAAgHADQgIAEgGAIIgEAEQgLAOgLAAQgHAAgEgFQgEgEAAgIQAAgQAUgLQAUgLAfAAQATAAANAFQAOAFAIAKQAFAGACALQACAKAAAZIAAA3QAAAKACAFQACAEADABIAGACQALADgBAGQAAAIgLAHQgMAGgPAAQgHAAgJgJg");
	this.shape_9.setTransform(-70.2,1.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgqB9QgTgEgNgIQgGgEgFgOQgEgQAAgTQAAgIADgEQADgEAFAAQAIAAAJAQIAEAGQALAUANAJQANAIASAAQASAAANgLQANgLAAgRQAAgYgygWIgGgCQgqgSgNgQQgOgOAAgZQAAgfAXgUQAXgUAkAAIAUACIAYAFIAHgFIAGgBQAEAAADADQAEACADAHQAGAKAEAMQADALAAAJQAAAGgDADQgDADgEAAQgKAAgIgMIgDgEQgKgNgLgGQgMgGgOAAQgTAAgLAJQgLAJAAAQQAAAOAJAJQAKAKAkAQIAHACQAfAOAOALQAJAJAFALQAFANAAANQAAAjgYAUQgZAUgrAAQgVAAgTgEg");
	this.shape_10.setTransform(-89.7,-2.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.savorysides, new cjs.Rectangle(-101.7,-24.9,203.5,45.1), null);


(lib.orangefruit = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.interstetititialorangefruite();
	this.instance.parent = this;
	this.instance.setTransform(-70,-38.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.orangefruit, new cjs.Rectangle(-70,-38.5,140,77), null);


(lib.mainbutton = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006F46").s().p("EgQFAzRMAAAhmhMAgLAAAMAAABmhg");
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.foryourfeast = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgIBoQgJgDgGgGQgGgFgDgKQgCgJAAgaIAAhcIgQAAIgFgBIgCgFIAAgEQAAgGASgPIAHgGIAHgGQASgQAHAAIAEACQABAAAAABQAAAAABABQAAAAAAABQAAAAAAABIAAAgIAnAAQAEAAACACQABABAAAFIAAAEQAAAFgBACQgCACgEAAIgkAAIgDABIgBAEIAABVQAAAXAEAFQAEAGAKAAQAGAAAIgDIAMgDQAEAAACADQADACAAADQAAAKgPAJQgPAJgSAAQgKAAgIgDg");
	this.shape.setTransform(104.8,2.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgNBaIgSgEIgFAEIgFABIgEgBIgEgDQgFgEgFgOQgFgOAAgNQAAgGADgDQADgEAEAAQAIAAAIAOIAHAKQAFAHAJAFQAJADAJABQALgBAIgFQAGgGAAgJQAAgPgcgOIgKgFQgbgNgKgLQgJgLAAgRQAAgWAQgOQAPgPAZAAIAMABIAMADIAIgEIAGgBQAIAAAIAOQAIANAAAPQAAAGgCAEQgEADgFAAQgDAAgEgDQgEgDgGgIQgGgMgGgEQgIgDgJAAQgJgBgHAGQgFAFgBAKQAAAHAHAGQAGAHAUAKIACABQAxAXAAAcQAAAYgSARQgTAQgcAAg");
	this.shape_1.setTransform(91,4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAfBRIgJgJIgIAEQgVAOgVAAQgZAAgQgOQgPgPAAgYQAAgbATgPQAVgPAkAAQAIAAAFACQAEADAAAGQAAAKgMAAQgRAAgKAIQgKAIAAAPQgBAOAKAIQAIAIAQAAQAQAAAHgHQAHgIAAgSIAAhBQAAgPgHgIQgGgIgMAAQgIAAgHADQgIAEgGAIIgEAEQgLAOgLAAQgHAAgEgFQgEgEAAgIQAAgQAUgLQAUgLAfAAQATAAAOAFQANAFAIAKQAFAGACALQACAKAAAZIAAA3QAAAKACAFQACAEADABIAGACQAKADABAGQAAAIgMAHQgMAGgPAAQgHAAgJgJg");
	this.shape_2.setTransform(74.6,4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("Ag3BBQgZgZAAglQAAgoAZgaQAagaAmAAQAhAAAUATQATATAAAgQAAALgDADQgDAEgNAAIhBAAQgGAAgDgDQgDgDAAgFQAAgEADgDQADgCAFAAIAkAAIAJgBQACgCAAgEQAAgQgLgMQgMgLgPAAQgVAAgKASQgJASAAAZQAAAaANAUQAOAUAVAAQANAAAJgDQAJgDAIgGIAGgFQAJgHAFAAQADAAADADQACACAAAEQAAAEgEAGQgEAGgIAGQgPAMgOAGQgOAFgQAAQgkAAgYgZg");
	this.shape_3.setTransform(56,4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhXB8QgKgDAAgIQAAgHAJgEQAKgDABgCQACgEACgaIAChDIgCg/QgCgbgCgDQgBgCgKgEQgJgEAAgHQAAgHAJgCQAHgDAeAAIBpAAIARgCIAJgCIAEABIAEADQADAHADALQAEANAAAIQAAAHgEAFQgCAEgGAAQgFAAgIgMIgFgIQgEgFgHgEQgIgCgLAAIgYAAQgQAAgIABQgJADgDAEQgDADgBAMIgBAgIAAAPQAAAIABACQABACAFAAIAcAAQAOAAAFgEQAGgEABgLIABgDQACgSAJAAQAIAAACAKQADAJAAAhQAAAggDAJQgCAKgIAAQgJAAgCgTIgBgCQgBgLgGgEQgFgEgOAAIgbAAQgGAAgBADQgBADAAALIAAANIABAxQABAKADACIAHAEQALAEAAAHQAAAIgKADQgJACgbAAQgcAAgJgCg");
	this.shape_4.setTransform(36.8,0.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("Ag0BWQgIgDAAgHQAAgHAIgCIAFgDQAEgCACgFQACgHAAgNIAAgMIAAgNIAAgLQAAgegCgKQgBgJgEgDIgIgDQgKgDAAgGQAAgEADgDQADgDAIgDIAXgHIAQgDQAIAAADAXIAAAEIABAAQAJgOAJgHQAKgIAKAAQAMAAAHAIQAHAHAAAMQAAAMgFAHQgGAHgKAAIgIgCIgIgFIgEgGQgBgFgCAAQgMAAgFAQQgEARAAA0QAAAPABAHQACAIAFACIAHACQAKADAAAIQAAAGgJADQgKADgXgBQgaABgJgDg");
	this.shape_5.setTransform(10.4,3.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAmBYQgDgDAAgGIAAgMIAAgBIgBAAQgCAAgEAEIgDADQgHAIgLAFQgKAEgMAAQgOAAgLgFQgLgFgIgJQgIgKgDgOQgEgOAAgkIAAgMIAAgMIAAgEQAAgOgCgEQgBgEgHgCIgHgCQgJgDAAgGQAAgEAEgDQADgDAMgEIAXgHIATgCQAFAAACADQABAEAAAHIAAAHIgBBBQAAAiAHAOQAHANASAAQASAAAKgRQAIgSAAgpIAAgNQAAgOgCgEQgCgEgGgCIgHgCQgJgDAAgGQgBgEAEgDQADgDANgEIAWgHIASgCQAGAAACADQACADAAAIIgBAKIgCBGIABAeIABALQABAHAJAEIAAAAIAEABQAJADAAAGQAAAEgDADQgDACgIADIgYAIQgMADgGAAQgFAAgCgCg");
	this.shape_6.setTransform(-7.1,4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("Ag+BBQgZgaAAgmQAAgmAagaQAagaAmAAQAlAAAYAYQAYAYAAAmQAAAngaAbQgZAbglAAQgmAAgYgZgAgggzQgLAOAAAXQAAAiAPAXQAOAXAUAAQARAAALgOQAKgPAAgXQAAghgOgXQgPgXgUAAQgRAAgKAOg");
	this.shape_7.setTransform(-26.9,4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgkB6QgJgDAAgIQAAgHAKgEIAIgEQAGgEAAhGIABgQIgVghIghg0QgKgOgFgEIgJgEQgMgEAAgGQAAgHAJgDQAIgDAhAAQAiAAAIADQAIADAAAHQAAAGgNAFIgBABIgGADIgBAFQAAAEAHANIAiA1IAegtQAJgPAAgFQAAgFgCgDQgDgDgIgDQgGgCgCgDQgDgCAAgEQAAgHAIgDQAGgDAdAAQAcAAAHADQAIADAAAHQAAAGgKAFIgNAGQgIAGgQAZQgRAZgZArIAAAeQABA6AFADIAIAEQAKAEAAAHQAAAIgJADQgJADgcAAQgaAAgKgDg");
	this.shape_8.setTransform(-47.8,0.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("Ag0BWQgIgDAAgHQAAgHAIgCIAFgDQAEgCACgFQACgHAAgNIAAgMIAAgNIAAgLQAAgegCgKQgBgJgEgDIgIgDQgKgDAAgGQAAgEADgDQADgDAIgDIAXgHIAQgDQAIAAADAXIAAAEIABAAQAJgOAJgHQAKgIAKAAQAMAAAHAIQAHAHAAAMQAAAMgFAHQgGAHgKAAIgIgCIgIgFIgEgGQgBgFgCAAQgMAAgFAQQgEARAAA0QAAAPABAHQACAIAFACIAHACQAKADAAAIQAAAGgJADQgKADgXgBQgaABgJgDg");
	this.shape_9.setTransform(-74.6,3.9);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("Ag+BBQgZgaAAgmQAAgmAagaQAagaAmAAQAlAAAYAYQAYAYAAAmQAAAngaAbQgZAbglAAQgmAAgYgZgAgggzQgLAOAAAXQAAAiAPAXQAOAXAUAAQARAAALgOQAKgPAAgXQAAghgOgXQgPgXgUAAQgRAAgKAOg");
	this.shape_10.setTransform(-91.3,4);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgwB8QgJgDABgHQAAgFAHgDIAFgCQAEgCACgGQABgGABgOIAAgRIAAhTIgUAAQgEAAgCgBQgBgCAAgFIAAgEQAAgFACgBQABgCAFAAIASAAIgCgOIgBgMQAAgbAQgOQAQgPAbAAQAVAAAMAJQAMAJAAAOQAAAIgEAEQgFAEgJAAQgFAAgEgCQgFgDgDgEIgDgHQgGgMgLAAQgGAAgDAEQgEAEAAAHIAEAUQADAPAAAMIAZAAQAFAAACABQABACAAAFIAAAEQAAAEgBACQgDACgEAAIgZAAIAABYQAAAXACAGQABAHAEACIAHACQAKAEAAAHQAAAGgJADQgIADgZAAQgYAAgJgDg");
	this.shape_11.setTransform(-104.4,0);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.foryourfeast, new cjs.Rectangle(-112.9,-22.5,225.8,45.1), null);


(lib.Path_10 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#231F20").s().p("AizEbQgWAAgIgFQgIgFAAgOQAAgKAGgGQAGgHAJAAIARAAQAKAAAEgLQADgJAAgZIAAl7QAAgZgDgIQgCgGgEgDQgEgEgEAAIgRAAQgJAAgHgHQgGgHAAgJQAAgOAJgGQAIgFAWAAIFSAAQAZAAAFAVIAMA7QAEAQgGAJQgFAJgMAAQgOAAgHgOIgJgSQgGgPgPgFQgMgEggAAIhQAAQghAAgJAIQgIAJAAAiIAABlQAAAZAIAFQAFAEAdAAIAnAAQAaAAAIgEQAHgDACgNIABgFQADgVAUAAQANAAAFAIQAFAJAAAWIAABHQAAAWgFAJQgFAJgNAAQgTAAgEgWIgBgGQgCgNgHgDQgIgEgbAAIgmAAQgdAAgFAEQgIAFAAAZIAABsQAAAiADALQADALAKAEQAQAGAhAAIBVgBQAvAAAPgfIAHgQQAJgQAOAAQAMAAAFAJQAFAJgDAQIgNBCQgFAVgZAAg");
	this.shape.setTransform(21.9,28.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Path_10, new cjs.Rectangle(0,0,43.9,56.7), null);


(lib.Path_9 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#231F20").s().p("AgNBlQgFgDAAgHIAAiTQAAgLgLABIgyAAQgLgBAAgOQAAgUAKgBICfAAQAMABAAARQAAARgLABIgyAAQgLAAAAAKIAACTQAAAHgFADQgEACgKAAQgJAAgEgCg");
	this.shape.setTransform(9.1,10.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Path_9, new cjs.Rectangle(0,0,18.2,20.5), null);


(lib.Path_8 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#231F20").s().p("AhMBmQgNAAAAgPIAAiuQAAgOANAAICbAAQAGAAADAEQACAEAAAJQAAASgMAAIh5AAQgIAAAAAKIAAAcQAAAIAKABIBFAAQALgBAAATQAAAQgKAAIhFAAQgFAAgDADQgDADAAAFIAAAeQAAAKAKAAIB3AAQALAAAAASQAAASgLAAg");
	this.shape.setTransform(9,10.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Path_8, new cjs.Rectangle(0,0,18,20.4), null);


(lib.Path_7 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#231F20").s().p("Ah+EYQgKgJgIgYIhIjYQgCgFgEAAQgEAAgCAFIhNDYIgJAWQgDAGgFAFQgMAJgRAAQgTAAgKgJQgLgJgJgYIimm+QgKgagHgHQgHgHgUgFQgOgCgFgFQgFgFAAgKQAAgWAdAAICvAAQAcAAAAAWQAAALgHAFQgHAFgRABQgOACgGAFQgGAFAAAKQAAAKADAJIBzFGQACAFAFAAQAEAAACgGIA/i2QAIgagHgWIgehbIgHgTQgEgJgHgFQgGgEgPgEQgNgDgGgFQgFgFAAgKQAAgZAeAAICmAAQAdAAAAAWQAAAUgcADQgQACgGAFQgGAFAAALQAAALAIAZIBgEsQACAGAEgBQAEAAABgGIBek6QADgMAAgIQAAgSgdgEQgbgCAAgWQAAgMAIgGQAHgFARAAIElAAQAVAAAJAFQAIAFAAAOQAAAKgGAHQgGAHgJAAIgRAAQgLAAgFALQgCAKAAAXIAABuQAAAdAFAHQAGAGAYAAIBzAAQAXAAAHgIQADgDAAgHIABgeIAAhoQAAgbgCgGQgCgFgFgDQgEgDgFAAIgQAAQgKAAgGgHQgHgHAAgKQAAgOAJgFQAIgFAWAAICaAAQAWAAAJAFQAJAFAAAOQAAAKgHAHQgGAHgJAAIgSAAQgEAAgEADQgFAEgBAEQgDAHAAAaIAAF8QAAAaADAIQABAFAFADQAEACAEAAIASAAQAJAAAGAHQAHAHAAAKQAAAOgJAFQgIAGgXAAIiaAAQgVAAgJgGQgIgFAAgOQAAgJAGgIQAHgHAJAAIAQAAQALAAAFgKQACgHAAgbIAAh8IgBgdQAAgHgDgEQgGgHgYAAIhzAAQgYAAgGAGQgFAHAAAdIAACBQAAAXACALQAEAKAMAAIARAAQAIAAAGAIQAGAHAAAKQAAANgIAGQgIAFgVAAIiaAAQgWAAgIgGQgJgFAAgOQAAgJAGgIQAHgHAJAAIARAAQAEAAAFgCQAEgDABgFQADgHAAgbIAAl8QAAgxgjAFQgMABgHAJQgIAJgGAWIiHGzQgJAfgKALQgKALgUAAQgTAAgLgJg");
	this.shape.setTransform(63.5,28.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Path_7, new cjs.Rectangle(0,0,127,57.9), null);


(lib.Path_6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#231F20").s().p("AhTEbIgTgEQgIAAgKAJQgKAHgJABQgLAAgGgHQgGgGgEgPIgVhWQgCgFAAgMQAAgKAIgJQAHgHAMAAQANAAAIAMIAMAQQAWAgAiASQAiARAkABQAogBAagUQAZgVAAgjQAAgggbgfQgZgbhAguQg/grgPgMQgSgOgTgWQggglAAg0QAAg+ArglQArglBGgBQAnABAhAHIAWAFIALACQAIAAAMgHQAJgIAJAAQASAAAGAYIAUBcQACAEAAAHQAAAKgHAFQgHAGgLAAQgMAAgKgOQgOgVgHgIQgGgGgOgLQgjgbgtAAQgcAAgSAPQgRAPAAAaQAAAXAJANQANASAaAUIApAfQAzAjAWARQAXATAUATQAWAWAMAfQAMAeAAAhQAABJgyAtQgzAthUAAQgxAAgngNg");
	this.shape.setTransform(19,29.6);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Path_6, new cjs.Rectangle(0,0,38.1,59.1), null);


(lib.Path_5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#231F20").s().p("ABaBkQgGgCAAgFIgOhsQgCgGgFAAQgDAAgDAEIgxA+QgEAFgFAAQgGAAgFgGIgtg8QgCgDgEAAQgFAAgBAIIgOBnQgCALgTAAQgGAAgFgDQgGgCAAgGIAViwQACgKADgDQAEgEALAAQAKAAAFAJIA4BOQAGAJADgBQAFAAAGgIIA7hQQAFgIAKAAQAHAAADADQAEACACAJIAUC0QABALgXAAQgFAAgEgDg");
	this.shape.setTransform(12.2,10.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Path_5, new cjs.Rectangle(0,0,24.3,20.6), null);


(lib.Path_4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#231F20").s().p("AA6BlQgFgBgEgFIhAhFQgKgJgUAAQgFAAgEAEQgDAFAAAGIAAA7QAAAIgGACQgFACgKAAQgRAAAAgMIAAi0QAAgIAFgCQAFgDAKAAQASAAAAAMIAAA3QAAANAJAAQALAAAGgCQADgCAFgEIBJhDQAMgLANALQAMAMgKAJIhAA7QgJAHAJAKIBOBVQAIAJgGAFQgEAEgOAAQgMAAgFgCg");
	this.shape.setTransform(9.6,10.4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Path_4, new cjs.Rectangle(0,0,19.1,20.7), null);


(lib.Path_3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

}).prototype = getMCSymbolPrototype(lib.Path_3, null, null);


(lib.Path_2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#231F20").s().p("Ai5EbQgWAAgIgFQgJgFAAgOQAAgKAGgHQAHgHAJAAIARAAQAKAAAFgLQACgKAAgXIAAl7QAAgYgDgJQgBgFgFgEQgEgEgEAAIgRAAQgIAAgHgHQgHgHAAgJQAAgOAJgGQAJgFAVAAIFvAAQAZAAAFAVIAMA7QAEAQgFAJQgFAJgMAAQgPAAgHgOIgIgSQgGgPgPgFQgMgEggAAIhtAAQgiAAgIAIQgJAJAAAiIAABlQAAAZAIAFQAEAEAeAAIBGAAQAaAAAIgEQAHgDACgNIABgFQADgVATAAQAOAAAFAIQAFAJAAAWIAABHQAAAWgFAJQgFAJgOAAQgSAAgEgWIgBgGQgCgNgHgDQgIgDgbAAIhFAAQgdAAgFADQgIAFAAAaIAACKQAAAbACAGQADAFAFADQAFADAFAAIAUAAQAJAAAGAHQAGAHAAAKQAAAOgJAFQgIAFgYAAg");
	this.shape.setTransform(22.5,28.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Path_2, new cjs.Rectangle(0,0,45.1,56.7), null);


(lib.Path_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#231F20").s().p("AipF/QhPhTAAiLQAAhZAghEQAghCA6gnQAZgTAmgSQAngUAmgNQAJgEgCgJQgCgKgNADQgVAEgZAAQgggBgYgJQgXgJgcgSQgggUgKgEQgugWg6AZQgWAJgLgLQgMgLAGgXQAXhVBDg4QBKg9BQAXQA0APAlA0QAnA2AeALQATAGAAAPQAAAOgRADQgbAFgjgQQgfgPgegbQgfgdgvgCQgrgCgcAVQgLAJADAGQAEAHALgCQAfgHAdAGQAoAHAbAgQAkAoAuAPQA4ASAugeIAZgXQAOgMALADQAQAEgCAUQgBAUgTAZQgiAsg9AeQhFAjgeAeQgwAvgTA9QgQAzAABRQAABxArBAQAqBBBKAAQBJAAArhCQAqhCAAhwQAAhfgXg4QgZg6g2gUQgbgLAFgTQAFgUAigDQA2gHA8AtQBoBMAACkQAACOhPBVQhQBUiHAAQiDAAhPhUg");
	this.shape.setTransform(33.5,46.7);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Path_1, new cjs.Rectangle(0,0,67.1,93.5), null);


(lib.Path = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#231F20").s().p("AihEbQgWAAgIgFQgIgFAAgOQAAgKAGgGQAGgHAJAAIARAAQAEAAAEgDQAFgEABgEQADgJAAgXIAAl+QAAgYgDgKQgBgEgFgEQgEgDgEAAIgRAAQgKAAgGgGQgHgHAAgKQAAgOAJgGQAJgFAWAAICdAAQAWAAAIAFQAJAGAAAOQAAAKgGAHQgHAGgJAAIgRAAQgOAAgEALQgDAGAAAcIAAFjQAAAcACAKQACAJAIAFQAGAEALACQAMABAaAAIAvAAQAwAAAPgfIAHgQQAIgQAPAAQAMAAAFAJQAFAJgEAQIgNBCQgFAVgZAAg");
	this.shape.setTransform(20.2,28.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Path, new cjs.Rectangle(0,0,40.4,56.7), null);


(lib.CompoundPath_5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#231F20").s().p("AjmEaQgWgDgGgEQgKgFAAgNQAAgKAGgHQAFgHAKAAIARAAQAKAAAEgLQADgJAAgYIAAl5QAAgZgDgIQgEgMgKAAIgRAAQgKAAgFgGQgGgIAAgJQAAgNAKgFQAGgEAWgDQBdgNBrAAQBOAAA1ASQA0ASAnAoQAmAlATA4QAUA5AABEQAABNgZA9QgZA+gwAlQgkAegxAOQgxAOhDAAQh0AAhUgNgAgvjrQgdAEgIAMQgLAMABAhIAAFjQgBAgAVAMQANAHAnACQBNAFArhAQAsg/gBhxQAAhvgqg/Qgqg+hMAAIgcACg");
	this.shape.setTransform(26.9,29.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.CompoundPath_5, new cjs.Rectangle(0,0,53.8,59), null);


(lib.CompoundPath_4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#231F20").s().p("AgeAfQgNgMAAgTQAAgRANgNQANgNARAAQASAAANANQANANAAARQAAATgNAMQgNANgSAAQgRAAgNgNgAgYgYQgKAKAAAOQAAAQAKAKQAKAKAOAAQAPAAAKgKQAJgKAAgQQAAgOgJgKQgKgKgPAAQgOAAgKAKg");
	this.shape.setTransform(4.4,4.4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.CompoundPath_4, new cjs.Rectangle(0,0,8.8,8.9), null);


(lib.CompoundPath_3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#231F20").s().p("AAvBeIgggxQgGgJgJAAIguAAQgEAAgDADQgDADAAAEIAAAxQAAAGgKABIgPABQgNAAAAgMIABi5QAAgIAIAAIBrAAQAgAAAUATQAVATgBAfQABAYgPAPIgWATQgIAGAEAGIAiAzQAFAHgFAEQgFAEgOAAQgRAAgFgJgAg4g4IAAAuQAAAFAEAEQAEABAFAAIA+AAQAQAAALgHQAMgJAAgRQAAgPgMgKQgLgIgQAAIg+AAQgNAAAAAKg");
	this.shape.setTransform(9.5,10.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.CompoundPath_3, new cjs.Rectangle(0,0,18.9,20.6), null);


(lib.CompoundPath_2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#231F20").s().p("AAJAaIgNgVIgGAAIAAAVIgJAAIAAgzIATAAQARAAAAAQQABAMgNACIAOAVgAgKgCIAHAAQAMAAAAgHQAAgIgKAAIgJAAg");
	this.shape.setTransform(2,2.6);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.CompoundPath_2, new cjs.Rectangle(0,0,3.9,5.2), null);


(lib.CompoundPath_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#231F20").s().p("ABnDxQhFg1gYhfIgBgDQgCgKgHgBQgGABgCAKIgBACQgYBfhHA2QhHA2hoAAQh/AAhLhQQhMhQAAiGQAAiGBMhRQBLhQCAAAQBpAABHA3QBHA2AXBgQADALAFgBQAHAAADgLIAAAAQAXhgBGg1QBHg3BoAAQB/AABMBPQBNBQAACFQAACIhNBQQhMBRiBAAQhmAAhHg2gACmiqQgoA/AABuQAABsAoA9QApA+BIAAQBGAAAog/QApg/ABhrQAAhrgqhAQgqg/hGAAQhGAAgpA/gAmFiqQgpA/AABuQAABsApA9QAoA+BIAAQBGAAApg/QApg/AAhrQAAhrgqhAQgpg/hGAAQhGAAgpA/g");
	this.shape.setTransform(55.8,29.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.CompoundPath_1, new cjs.Rectangle(0,0,111.5,59), null);


(lib.CompoundPath = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#231F20").s().p("ABCBfIgNgbQgEgGgGAAIhTAAQgJAAgEAMIgMAVQgDAIgSAAQgWAAAFgMIBZi4QAFgKAKAAQALABAFAIIBYC7QACAGgJADQgGABgIAAQgPABgDgJgAgEgdIgYAyQgCADACACQABADAEAAIAwAAQABAAAAAAQABAAABgBQAAAAABAAQAAgBABAAQACgCgCgDIgYgzQgCgEgDABQgDAAgCADg");
	this.shape.setTransform(10.5,10.4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.CompoundPath, new cjs.Rectangle(0,0,21,20.7), null);


(lib.findanevent = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgGAyIAAhXIggAAIAAgLIBNAAIAAALIggAAIAABXg");
	this.shape.setTransform(48.7,0.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAYAyIgzhQIAABQIgOAAIAAhiIASAAIAzBNIAAhNIAOAAIAABig");
	this.shape_1.setTransform(39.4,0.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AggAyIAAhiIA/AAIAAALIgxAAIAAAeIAuAAIAAALIguAAIAAAhIAzAAIAAANg");
	this.shape_2.setTransform(30,0.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgFAyIgnhiIAPAAIAdBQIABAAIAdhQIAPAAIgmBig");
	this.shape_3.setTransform(21.1,0.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AggAyIAAhiIA/AAIAAALIgxAAIAAAeIAuAAIAAALIguAAIAAAhIAzAAIAAANg");
	this.shape_4.setTransform(12.7,0.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAYAyIgzhQIAABQIgOAAIAAhiIASAAIAzBNIAAhNIAOAAIAABig");
	this.shape_5.setTransform(-0.7,0.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAhAyIgKgZIguAAIgKAZIgPAAIArhiIAMAAIAqBigAASANIgSguIgSAuIAkAAg");
	this.shape_6.setTransform(-11.1,0.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgrAyIAAhiIAiAAQAJAAAJACQAKADAIAGQAHAGAFAKIAEAKIABALIgBAMIgEAKIgFAJIgHAGQgIAHgKACQgLAEgHAAgAgdAlIASAAQAIAAAHgCQAIgDAFgFQAGgEADgHIACgIIABgIIgBgIIgCgIQgDgGgGgFQgFgFgIgCQgHgCgIgBIgSAAg");
	this.shape_7.setTransform(-24.6,0.2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAZAyIg0hQIAABQIgOAAIAAhiIASAAIAzBNIAAhNIAOAAIAABig");
	this.shape_8.setTransform(-35.6,0.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgGAyIAAhiIANAAIAABig");
	this.shape_9.setTransform(-42.8,0.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgeAyIAAhiIA9AAIAAALIgvAAIAAAfIAsAAIAAAMIgsAAIAAAsg");
	this.shape_10.setTransform(-48.4,0.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.findanevent, new cjs.Rectangle(-54.8,-10.6,109.6,21.2), null);


(lib.deliciousdesserts = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgNBaIgSgEIgFAEIgFABIgEgBIgDgDQgGgEgFgOQgFgOAAgNQAAgGADgDQADgEAEAAQAIAAAIAOIAHAKQAFAHAJAFQAJADAJABQALgBAIgFQAGgGAAgJQAAgPgcgOIgKgFQgbgNgJgLQgKgLAAgRQAAgWAQgOQAPgPAZAAIAMABIAMADIAIgEIAFgBQAJAAAIAOQAIANAAAPQAAAGgCAEQgEADgFAAQgDAAgEgDQgEgDgGgIQgFgMgHgEQgIgDgJAAQgJgBgHAGQgFAFgBAKQAAAHAHAGQAGAHAUAKIACABQAxAXAAAcQAAAYgSARQgTAQgcAAg");
	this.shape.setTransform(137.3,4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgIBoQgJgDgGgGQgGgFgDgKQgCgJAAgaIAAhcIgQAAIgFgBIgCgFIAAgEQAAgGASgPIAHgGIAHgGQASgQAHAAIAEACQABAAAAABQABAAAAABQAAAAAAABQAAAAAAABIAAAgIAnAAQAEAAACACQABABAAAFIAAAEQAAAFgBACQgCACgEAAIgkAAIgDABIgBAEIAABVQAAAXAEAFQAEAGAKAAQAGAAAIgDIAMgDQAEAAACADQADACAAADQAAAKgPAJQgPAJgSAAQgKAAgIgDg");
	this.shape_1.setTransform(123.8,2.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("Ag0BWQgIgDAAgHQAAgHAIgCIAFgDQAEgCACgFQACgHAAgNIAAgMIAAgNIAAgLQAAgegCgKQgBgJgEgDIgIgDQgKgDAAgGQAAgEADgDQADgDAIgDIAXgHIAQgDQAIAAADAXIAAAEIABAAQAJgOAJgHQAKgIAKAAQAMAAAHAIQAHAHAAAMQAAAMgFAHQgGAHgKAAIgIgCIgIgFIgEgGQgBgFgCAAQgMAAgFAQQgEARAAA0QAAAPABAHQACAIAFACIAHACQAKADAAAIQAAAGgJADQgKADgXgBQgaABgJgDg");
	this.shape_2.setTransform(111.4,3.9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("Ag3BBQgZgZAAglQAAgoAZgaQAagaAmAAQAhAAAUATQATATAAAgQAAALgDADQgDAEgNAAIhBAAQgGAAgDgDQgDgDAAgFQAAgEADgDQADgCAFAAIAkAAIAJgBQACgCAAgEQAAgQgLgMQgMgLgPAAQgVAAgKASQgJASAAAZQAAAaANAUQAOAUAVAAQANAAAJgDQAJgDAIgGIAGgFQAJgHAFAAQADAAADADQACACAAAEQAAAEgEAGQgEAGgIAGQgPAMgOAGQgOAFgQAAQgkAAgYgZg");
	this.shape_3.setTransform(95.3,4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgNBaIgSgEIgFAEIgGABIgDgBIgEgDQgFgEgFgOQgFgOAAgNQAAgGADgDQADgEAEAAQAIAAAIAOIAHAKQAFAHAJAFQAJADAJABQALgBAHgFQAHgGAAgJQAAgPgcgOIgKgFQgbgNgKgLQgJgLAAgRQAAgWAQgOQAPgPAaAAIALABIAMADIAIgEIAGgBQAIAAAIAOQAIANAAAPQAAAGgDAEQgCADgGAAQgEAAgDgDQgEgDgGgIQgFgMgIgEQgHgDgJAAQgJgBgHAGQgFAFAAAKQgBAHAHAGQAGAHAUAKIADABQAwAXAAAcQAAAYgSARQgTAQgcAAg");
	this.shape_4.setTransform(78.6,4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgNBaIgSgEIgFAEIgGABIgDgBIgEgDQgFgEgFgOQgFgOAAgNQAAgGADgDQADgEAEAAQAIAAAIAOIAHAKQAFAHAJAFQAJADAJABQALgBAIgFQAGgGAAgJQAAgPgcgOIgKgFQgbgNgKgLQgJgLAAgRQAAgWAQgOQAPgPAZAAIAMABIAMADIAIgEIAGgBQAIAAAIAOQAIANAAAPQAAAGgDAEQgCADgGAAQgEAAgDgDQgEgDgGgIQgGgMgGgEQgIgDgJAAQgJgBgHAGQgFAFAAAKQgBAHAHAGQAGAHAUAKIADABQAwAXAAAcQAAAYgSARQgTAQgcAAg");
	this.shape_5.setTransform(63.7,4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("Ag3BBQgZgZAAglQAAgoAZgaQAagaAmAAQAhAAAUATQATATAAAgQAAALgDADQgDAEgNAAIhBAAQgGAAgDgDQgDgDAAgFQAAgEADgDQADgCAFAAIAkAAIAJgBQACgCAAgEQAAgQgLgMQgMgLgPAAQgVAAgKASQgJASAAAZQAAAaANAUQAOAUAVAAQANAAAJgDQAJgDAIgGIAGgFQAJgHAFAAQADAAADADQACACAAAEQAAAEgEAGQgEAGgIAGQgPAMgOAGQgOAFgQAAQgkAAgYgZg");
	this.shape_6.setTransform(47.1,4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AglB8IgWAAIgOAAIgPAAQgVAAgGgCQgGgDgBgHQABgHAIgEQAKgDABgCQADgEABgaIABhDIgBg/QgBgbgDgDQgBgCgKgEQgIgEgBgHQAAgHAIgCQAHgEAUAAIAQABIARAAIAXgBIATAAQBAAAAkAhQAiAhAAA9QAAA8gkAfQgjAfhEAAgAglhiQgIADgCAFQgCAHgCAUIgBA1IABBBQACAbACAGQACAFALAEQALADAQAAQAnAAAUgXQAUgYAAgxQAAgzgXgaQgWgbgrAAQgOAAgHACg");
	this.shape_7.setTransform(24.6,0.2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgNBaIgSgEIgFAEIgGABIgDgBIgEgDQgFgEgFgOQgFgOAAgNQAAgGADgDQADgEAEAAQAIAAAIAOIAHAKQAFAHAJAFQAJADAJABQALgBAIgFQAGgGAAgJQAAgPgcgOIgKgFQgbgNgKgLQgJgLAAgRQAAgWAQgOQAPgPAZAAIAMABIAMADIAIgEIAGgBQAIAAAIAOQAIANAAAPQAAAGgDAEQgCADgGAAQgEAAgDgDQgEgDgGgIQgGgMgGgEQgIgDgJAAQgJgBgHAGQgFAFAAAKQgBAHAHAGQAGAHAUAKIADABQAwAXAAAcQAAAYgSARQgTAQgcAAg");
	this.shape_8.setTransform(-5.6,4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AAmBYQgDgDAAgGIAAgMIAAgBIgBAAQgCAAgEAEIgDADQgIAIgKAFQgKAEgMAAQgNAAgLgFQgMgFgHgJQgJgKgDgOQgDgOgBgkIAAgMIAAgMIAAgEQAAgOgBgEQgDgEgGgCIgHgCQgJgDAAgGQAAgEAEgDQADgDAMgEIAYgHIASgCQAFAAACADQACAEAAAHIgBAHIgBBBQgBAiAIAOQAHANASAAQATAAAIgRQAJgSAAgpIAAgNQAAgOgCgEQgCgEgGgCIgHgCQgKgDAAgGQAAgEAEgDQADgDANgEIAWgHIASgCQAGAAACADQACADAAAIIgBAKIgBBGIAAAeIABALQACAHAIAEIAAAAIAEABQAJADAAAGQAAAEgDADQgDACgIADIgYAIQgMADgGAAQgFAAgCgCg");
	this.shape_9.setTransform(-23.5,4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("Ag+BBQgZgaAAgmQAAgmAagaQAagaAmAAQAlAAAYAYQAYAYAAAmQAAAngaAbQgZAbglAAQgmAAgYgZgAgggzQgLAOAAAXQAAAiAPAXQAOAXAUAAQARAAALgOQAKgPAAgXQAAghgOgXQgPgXgUAAQgRAAgKAOg");
	this.shape_10.setTransform(-43.3,4);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgeB8QgJgDABgIQgBgGAJgDIAEgCQAFgCACgGQABgGAAgNIAAgMIAAgNIAAgSQAAgcgBgHQgBgIgEgCIgIgDQgLgDAAgGQAAgEAEgDQADgDAIgDIAagIIARgEQAFAAABAEQADADAAAIIAAAKIgBAIIgBArIAAABIgBArQAAAQACAHQABAHAEACIAHACQAJAEAAAGQAAAHgJADQgIACgXAAQgZAAgJgCgAgVhWQgHgGAAgJQAAgKAIgHQAIgHAMAAQAKAAAHAGQAIAHAAAJQAAAJgIAHQgIAHgLAAQgLAAgIgGg");
	this.shape_11.setTransform(-58,0.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("Ag2BBQgZgZAAglQAAgnAagbQAagaAmAAQAdAAAUAPQAUAOAAAUQAAAIgGAGQgGAFgIAAQgJAAgFgFQgGgEgGgOQgFgMgHgFQgGgFgLAAQgTAAgLAPQgLAPAAAaQAAAeAPAUQAQATAYAAQAJAAAIgCQAHgDAHgEIAHgFQAJgHAFAAQAEAAACACQACACAAADQAAAFgEAGQgDAGgGAFQgOAMgOAFQgPAGgRAAQgkAAgYgZg");
	this.shape_12.setTransform(-71.6,4);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgeB8QgJgDABgIQgBgGAJgDIAEgCQAFgCACgGQACgGAAgNIgBgMIAAgNIAAgSQAAgcgBgHQgBgIgEgCIgIgDQgLgDAAgGQAAgEADgDQAEgDAIgDIAagIIARgEQAEAAACAEQACADABAIIAAAKIgBAIIgBArIAAABIgBArQAAAQABAHQACAHAEACIAHACQAIAEABAGQAAAHgJADQgIACgXAAQgZAAgJgCgAgVhWQgHgGAAgJQAAgKAIgHQAIgHAMAAQAKAAAIAGQAHAHAAAJQAAAJgIAHQgIAHgLAAQgLAAgIgGg");
	this.shape_13.setTransform(-85.5,0.1);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgcB8QgJgDAAgHQAAgGAHgDIAJgEQADgDABgLIABgiIAAgbIAAggIAAgNQAAgsgBgMQgCgMgEgDIgKgEQgLgDAAgGQAAgEADgDQAEgDAMgEIAXgGIARgDQAFAAACAEQADACAAAJIgBANQgCA+AAA9IABA8QABAMADAEIAKAEQAIADAAAHQAAAGgJADQgIADgXAAQgZAAgIgDg");
	this.shape_14.setTransform(-95.5,0);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("Ag3BBQgZgZAAglQAAgoAZgaQAagaAmAAQAhAAAUATQATATAAAgQAAALgDADQgDAEgNAAIhBAAQgGAAgDgDQgDgDAAgFQAAgEADgDQADgCAFAAIAkAAIAJgBQACgCAAgEQAAgQgLgMQgMgLgPAAQgVAAgKASQgJASAAAZQAAAaANAUQAOAUAVAAQANAAAJgDQAJgDAIgGIAGgFQAJgHAFAAQADAAADADQACACAAAEQAAAEgEAGQgEAGgIAGQgPAMgOAGQgOAFgQAAQgkAAgYgZg");
	this.shape_15.setTransform(-109.2,4);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AglB8IgVAAIgPAAIgPAAQgVAAgGgCQgHgDABgHQAAgHAJgEQAIgDADgCQACgEABgaIABhDIgBg/QgBgbgCgDQgDgCgIgEQgJgEAAgHQAAgHAGgCQAIgEAUAAIAPABIASAAIAXgBIAUAAQA/AAAkAhQAiAhABA9QgBA8gjAfQgkAfhFAAgAglhiQgIADgCAFQgCAHgCAUIgBA1IABBBQACAbACAGQABAFAMAEQAMADAPAAQAnAAAUgXQAUgYAAgxQAAgzgWgaQgXgbgrAAQgOAAgHACg");
	this.shape_16.setTransform(-131.7,0.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.deliciousdesserts, new cjs.Rectangle(-146.9,-22.5,293.8,45.1), null);


(lib.date = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgWA3QgKgEgIgHIgBgDIABgEIADgEIAEgDIAEgBIAFACIAFADIAHAEQAFABAFAAQAEAAAFgCQAEgBAEgDQACgDADgFQACgEAAgFQgBgFgBgEIgFgGIgHgEQgEgCgEAAQgFAAgFACIgFADIgGADIgFABIgGAAQgDgBgBgDIAFgyQAAgCACgDIAGgCIAbAAIAbABQAEAAABADIACAGQAAADgCADQgBACgDABIgkAAQgGAAgCAEQgCADABAFQAAABAAAAQAAABAAAAQAAABAAAAQABAAAAABQAAAAABAAQAAABABAAQAAAAABAAQAAAAAAAAIAHgBIAGAAQAIAAAIADQAHADAFAFQAFAFADAGQACAHAAAJQAAAJgDAIQgEAIgFAGQgHAFgIADQgIADgJAAQgLAAgJgDg");
	this.shape.setTransform(34.6,-0.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgOAJIgCgBIgCgCIgBgEIAAgCIAAgCIABgDIACgCIACgBIAcAAIADABIACACIAAADIABACIgBAEQgBADgCACIgDAAg");
	this.shape_1.setTransform(22.4,-0.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAJA6QAAAAAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBIAAgSQAAgBgBAAQAAgBAAAAQAAgBAAAAQgBgBAAAAQAAgBgBAAQAAgBgBAAQAAAAgBAAQgBgBgBAAIgkAAIgFgBQAAAAAAAAQgBgBAAAAQAAgBAAAAQgBgBAAAAIABgFIAihLIADgEIAFgBIACABIAEACIADACIAAADIgBAFIgFAKIgEAMIgGANIgEALIgDAEIAAACIAAACIABACQAAABABAAQAAAAAAABQABAAAAAAQABAAABAAIADAAIAGgBIAEgBQABAAAAgBQABAAAAgBQAAAAAAgBQABgBAAAAIAAgRIABgEIADgBIAEgBIADAAIACAAIADABIADACIAAADIAAARIABADQAAABABAAQAAABABAAQAAAAABAAQAAAAABAAIAIAAQAEADAAADIABAGQgBAFgBABIgEABIgFAAQgDAAgCADIgBACIgBACIABAMQAAAEgBACQAAABAAABQgBAAAAAAQgBABAAAAQgBAAgBAAIgIACg");
	this.shape_2.setTransform(10.3,-0.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgGAHQgEgDAAgEQAAgEAEgDQADgDADAAQAFAAADADQADADAAAEQAAAEgDADQgDAEgFAAQgDAAgDgEg");
	this.shape_3.setTransform(-1.7,4.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgBA4IgEgIIgFgNIgIgQIgIgSIgIgRIgGgPIgEgMIgCgFIABgDIAEgDIAEgCIAEAAQABAAAAAAQABAAAAAAQABABAAAAQABAAABAAIACAFIAYA4IABABIABABQAAAAABAAQAAAAABgBQAAAAAAAAQABgBAAgBIAXg4IADgEQABAAAAgBQABAAAAAAQABAAAAAAQABgBABAAIADABIAFABIADADQABAAAAAAQAAABABAAQAAABAAAAQAAAAAAABIgCAFIgFALIgGAQIgIARIgIATIgIAQIgFAOIgDAGIgBACIgBABQAAAAAAgBQgBAAAAAAQAAAAAAgBQAAAAAAAAg");
	this.shape_4.setTransform(-9,-0.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgLA5IgMgDIgKgFIgJgHQgIgIgFgLIgEgLIgBgMIABgLIAEgLQAFgLAIgIIAJgHIAKgGIAMgDIALgBIAMABIAMADQALAFAIAIQAIAIAFALQAFALAAALIgCAMIgDALQgFALgIAIQgIAIgLAEIgMADQgGACgGAAQgFAAgGgCgAgOgjQgHADgFAFQgGAGgDAGQgDAIAAAHQAAAIADAIQADAGAGAFQAFAGAHADQAHADAHAAQAHAAAHgDQAHgDAGgGQAFgFADgGQAEgIAAgIQAAgHgEgIQgDgGgFgGQgGgFgHgDQgHgDgHAAQgHAAgHADg");
	this.shape_5.setTransform(-20.7,-0.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAhA7QgCgBgCgDIgug/QAAAAgBgBQAAAAAAAAQgBAAAAAAQgBAAAAAAIgDABQgBAAAAABQAAAAAAAAQgBABAAAAQAAABAAAAIAAA6QgBACgDABIgFABIgHAAQgDgBgCgDIAAhrQAAAAAAgBQAAAAABAAQAAgBAAAAQAAAAABAAIADgCIAEgBIADAAQAFAAADAEIAuA9IADABIACAAIABgCIAAg6QAAAAABgBQAAAAAAgBQAAAAABAAQAAAAABAAIADgCIAEAAIAEAAQAFAAACAEIAABsQAAABgBAAQAAABgBAAQAAABAAAAQgBAAAAABQgBAAAAAAQgBAAAAABQgBAAgBAAQAAAAgBAAg");
	this.shape_6.setTransform(-33.4,-0.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.date, new cjs.Rectangle(-41.4,-10.2,82.9,20.6), null);


(lib.ctarectangle = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D63900").s().p("AqiCoIAAlPIVFAAIAAFPg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.ctarectangle, new cjs.Rectangle(-67.5,-16.7,135,33.6), null);


(lib.blackrectangleinbox = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("EgXbgkQMAu3AAAMAAABIhMgu3AAAg");
	this.shape.setTransform(0,0,1.063,1.032);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-160.5,-240.5,321,481);


(lib.atasteofwholefoods = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgIBoQgJgDgGgGQgGgFgDgKQgCgJAAgaIAAhcIgQAAIgFgBIgCgFIAAgEQAAgGASgPIAHgGIAHgGQASgQAHAAIAEACQABAAAAABQAAAAABAAQAAABAAABQAAAAAAABIAAAgIAnAAQAEAAACACQABABAAAFIAAAEQAAAFgBACQgCACgEAAIgkAAIgDABIgBAEIAABVQAAAXAEAFQAEAGAKAAQAGAAAIgDIAMgDQAEAAACADQADACAAADQAAAKgPAJQgPAJgSAAQgKAAgIgDg");
	this.shape.setTransform(50.3,21.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("Ag3BBQgZgZAAglQAAgoAZgaQAagaAmAAQAhAAAUATQATATAAAgQAAALgDADQgDAEgNAAIhBAAQgGAAgDgDQgDgDAAgFQAAgEADgDQADgCAFAAIAkAAIAJgBQACgCAAgEQAAgQgLgMQgMgLgPAAQgVAAgKASQgJASAAAZQAAAaANAUQAOAUAVAAQANAAAJgDQAJgDAIgGIAGgFQAJgHAFAAQADAAADADQACACAAAEQAAAEgEAGQgEAGgIAGQgPAMgOAGQgOAFgQAAQgkAAgYgZg");
	this.shape_1.setTransform(34.9,23.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AA4B+IgHgBQgHgDgRgUIgHgKIgDgEQgqg2gDAAQgBAAAAAAQgBAAAAABQAAAAAAAAQgBABAAAAIAAAHIAAAIIABAkQABAKACADIAKAFQAIAEAAAGQAAAGgJADQgIADgXAAQgaAAgIgDQgJgCAAgIQAAgGAJgDIAEgCQAFgCACgJQABgJAAgUIAAgVIAAgbIAAgUIgBhBQgBgPgDgEQgCgBgHgDIgGgBIgHgEIgBgEQAAgFADgDQAEgCAMgFIAXgHIASgCQAFAAACAEQADADAAAIIgBAhIgBAtIAAAqIAAAJQABABAAAAQAAAAAAABQABAAAAAAQAAAAABAAIAHgEIANgKIAQgRQAEgEAAgDQAAgBgGgEQgFgDAAgFQAAgIAIgEQAJgDAYAAQAQAAAIADQAIAEAAAHQAAAIgNADQgMADgGADQgGADgPAPIgCADIgGAGIgCADQAAADAPAVIACACIAeAkQAMAPAHAEQAEADALAEQALADAAAHQAAAHgIAEQgIADgSAAg");
	this.shape_2.setTransform(16.8,19.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("Ag0BWQgIgDAAgIQAAgFAIgEIAFgCQAEgCACgGQACgFAAgOIAAgLIAAgOIAAgLQAAgegCgKQgBgKgEgCIgIgDQgKgDAAgGQAAgEADgDQADgDAIgDIAXgHIAQgEQAIABADAXIAAADIABABQAJgOAJgHQAKgIAKAAQAMAAAHAIQAHAHAAAMQAAAMgFAHQgGAHgKAAIgIgBIgIgGIgEgGQgBgFgCAAQgMAAgFARQgEAQAAA0QAAAPABAHQACAIAFACIAHACQAKADAAAIQAAAGgJADQgKACgXABQgagBgJgCg");
	this.shape_3.setTransform(0.3,23);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAfBRIgKgJIgHAEQgUAOgWAAQgZAAgQgOQgPgPAAgYQgBgbAVgPQAUgPAkAAQAIAAAFACQAEADAAAGQAAAKgMAAQgQAAgLAIQgLAIAAAPQABAOAIAIQAKAIAPAAQAQAAAHgHQAHgIAAgSIAAhBQAAgPgGgIQgHgIgLAAQgJAAgHADQgIAEgGAIIgEAEQgKAOgMAAQgHAAgEgFQgEgEAAgIQAAgQAUgLQAUgLAgAAQASAAAOAFQAOAFAHAKQAFAGADALQABAKAAAZIAAA3QABAKABAFQACAEAEABIAEACQAMADAAAGQAAAIgMAHQgMAGgPAAQgHAAgJgJg");
	this.shape_4.setTransform(-15.7,23.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("ABBB6QgKgDAAgIQAAgHALgEIAHgEQAEgCABgIQABgHAAgXIAAgJIAAhJIgBgsIgWA5QgzCEgLAAQgFAAgKgSQgKgSgYg4IgmhXIgBBEIgBAvIABAgQABAHADACIAHAEQALAEAAAHQAAAIgJADQgJADgVAAQgTAAgIgDQgJgEAAgHQAAgGAKgEQAJgFABgDQACgJADgsQADgsAAg2IAAgGQAAgSgCgGQgBgGgEgDIgIgDQgMgFAAgHQAAgGAIgDQAIgDAZAAIAZABIAHABQADADAMAfIAKAYIAFAMQAqBoADAAQADAAAQgmQAPgkAWg9IADgKQAGgTAGgGQADgDAGgBIAYgCQAXAAAIADQAIADAAAGQAAAIgKADIgFACQgFADgCAHQgCAHAAAaIACBiQACAsABAHQABAEAIADIAEABIAHAEQACACAAAEQAAAIgKADQgKADgcAAQgaAAgJgDg");
	this.shape_5.setTransform(-40.8,19.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgNBaIgSgDIgFADIgGABIgDgBIgEgDQgFgEgFgOQgFgOAAgNQAAgFADgEQADgEAEAAQAIAAAIAOIAHAKQAFAIAJADQAJAFAJAAQALgBAIgFQAGgGAAgJQAAgQgcgNIgKgFQgbgOgKgKQgJgLAAgRQAAgWAQgOQAPgPAZAAIAMABIAMADIAIgEIAGgBQAIAAAIAOQAIAOAAAPQAAAFgDAEQgCAEgGgBQgEABgDgEQgEgDgGgIQgGgMgGgEQgIgDgJAAQgJgBgHAGQgFAFAAAKQgBAHAHAGQAGAHAUAKIADABQAwAXAAAcQAAAYgSARQgTAQgcAAg");
	this.shape_6.setTransform(96.5,-24.9);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AhLBpQgUgYAAglQAAgqAXgaQAXgbAlAAIAMACQAFACADADQADAEAAAEQAAAKgLAAIgFgBIgEAAQgTAAgMAQQgLAOAAAcQAAAdAMASQANATATAAQASgBAKgJQAKgLAAgTIAAgvIAAhPQAAgMgDgFQgCgEgGgDIgFgCQgLgCAAgHQAAgEAEgDQAFgEANgEIATgGIAQgCQAGAAADADQACADAAAIIAAAJIgCBqIABBIQABARADACIAMAEQAJACAAAGQAAAIgZAJIgRAEIgNABQgFAAgCgCQgCgDAAgGIAAgJIgBgCIgBgCIgFAEIgIAGQgKAHgJAEQgKAEgKAAQghAAgUgXg");
	this.shape_7.setTransform(79.5,-28.7);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("Ag+BBQgZgaAAgmQAAgmAagaQAagaAmAAQAlAAAYAYQAYAYAAAmQAAAngaAbQgZAbglAAQgmAAgYgZgAgggzQgLAOAAAXQAAAiAPAXQAOAXAUAAQARAAALgOQAKgPAAgXQAAghgOgXQgPgXgUAAQgRAAgKAOg");
	this.shape_8.setTransform(58.9,-24.9);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("Ag+BBQgZgaAAgmQAAgmAagaQAagaAmAAQAlAAAYAYQAYAYAAAmQAAAngaAbQgZAbglAAQgmAAgYgZgAgggzQgLAOAAAXQAAAiAPAXQAOAXAUAAQARAAALgOQAKgPAAgXQAAghgOgXQgPgXgUAAQgRAAgKAOg");
	this.shape_9.setTransform(39.5,-24.9);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AhXB8QgKgEAAgIQAAgGAKgEQAJgDABgCQACgEACgaIAChDIgCg/QgCgbgCgDQgBgCgJgEQgKgEAAgHQAAgHAJgCQAHgDAeAAIBpAAIARgCIAJgBIAEAAIAEADQADAGADAMQAEAMAAAJQAAAIgEAEQgCAEgGAAQgFAAgHgMIgGgIQgEgGgHgDQgIgCgMAAIgXAAQgQAAgIABQgJACgDAFQgDADgBALIgBAhIAAAPQAAAIABACQABACAFAAIAcAAQAOAAAFgEQAGgEABgLIABgDQACgSAJAAQAIAAACAKQADAJAAAhQAAAggDAJQgCAKgIAAQgJAAgCgTIgBgCQgBgLgGgEQgFgEgOAAIgbAAQgGAAgBADQgBADAAALIAAANIABAwQABALADACIAHAEQALAEAAAHQAAAHgKAEQgJACgbAAQgcAAgJgCg");
	this.shape_10.setTransform(19.7,-28.8);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("Ag3BBQgZgZAAglQAAgoAZgaQAagaAmAAQAhAAAUATQATATAAAgQAAALgDADQgDAEgNAAIhBAAQgGAAgDgDQgDgDAAgFQAAgEADgDQADgCAFAAIAkAAIAJgBQACgCAAgEQAAgQgLgMQgMgLgPAAQgVAAgKASQgJASAAAZQAAAaANAUQAOAUAVAAQANAAAJgDQAJgDAIgGIAGgFQAJgHAFAAQADAAADADQACACAAAEQAAAEgEAGQgEAGgIAGQgPAMgOAGQgOAFgQAAQgkAAgYgZg");
	this.shape_11.setTransform(-9.7,-24.9);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgcB8QgJgDAAgHQAAgGAHgDIAJgEQADgDABgLIABgiIAAgbIAAggIAAgNQAAgsgBgMQgCgMgEgDIgKgDQgLgEAAgFQAAgFADgDQAEgDAMgEIAXgGIARgDQAFAAACAEQADADAAAIIgBANQgCA+AAA9IABA8QABAMADAEIAKAEQAIADAAAHQAAAGgJADQgIADgXAAQgZAAgIgDg");
	this.shape_12.setTransform(-23.9,-28.9);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("Ag+BBQgZgaAAgmQAAgmAagaQAagaAmAAQAlAAAYAYQAYAYAAAmQAAAngaAbQgZAbglAAQgmAAgYgZgAgggzQgLAOAAAXQAAAiAPAXQAOAXAUAAQARAAALgOQAKgPAAgXQAAghgOgXQgPgXgUAAQgRAAgKAOg");
	this.shape_13.setTransform(-38.1,-24.9);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AAYB8QgJgDAAgGQAAgHAJgDIAHgDQAEgCABgHQACgIAAgSQAAg4gHgNQgHgOgSAAQgJAAgIAGQgJAFgEAJQgEAHgBANQgCAOAAAhQAAASACAGQABAFAEACIAGADQAJADAAAHQAAAGgJADQgIADgWAAQgcAAgIgDQgIgDAAgHQAAgGAIgDIAFgCQAEgDACgHQACgHAAgTIAAgcIAAgbIgBhNQgBgTgDgEQgBgCgLgDQgKgDAAgGQAAgFAEgDQAFgDAPgGIARgFIAQgCQAGAAACAEQADADAAAIIgBAHIgBBFIAAAIIABAEIACACIAEgEIAGgHQAJgJAKgEQAJgEAKAAQAeAAAPATQAOATAAAmIAAAQIABAfIAAAKQAAAJABAEQACAEAEACIAEACQAJADAAAGQAAAHgIADQgJADgbAAQgXAAgIgDg");
	this.shape_14.setTransform(-58.4,-28.9);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAYA8IglhfQgLgfgHgPQgHgOgGgFIgKgEQgJgDABgHQAAgHAHgCQAJgDAgAAQAgAAAIADQAIACAAAHQAAAHgNAFIgBAAQgFACgCACQgBADAAAEQAAAGAIAXIAdBLIALAcQAEAHADAAQADAAADgFIALgaIADgHQAkhVAAgLQAAgFgCgEQgDgEgGgCIgDgCQgKgEAAgHQAAgHAGgCQAHgDAcAAQAcAAAHADQAHACAAAHQAAAHgKAEIgHAEQgNAIgWA7IgPAjIggBRIgHAQQgKAbgIAAQgIAAgahDgAhGBxIgDgGQgWgwgihYIgQgpIgKgVQgFgHgFgDIgFgCQgLgEAAgHQAAgHAIgCQAJgDAgAAQAhAAAIADQAIACAAAHQAAAHgNAFIgBAAQgFACgCACQgCADAAAEQAAAFAHAVIAeBMIAMAfQAEAGADAAQADAAAEgIIAIgUQAEgLAJAAQALAAAAALIgDALIgVA3IgGANQgKAcgIAAQgFAAgGgOg");
	this.shape_15.setTransform(-86.3,-28.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.atasteofwholefoods, new cjs.Rectangle(-106.1,-51.4,212.3,93.1), null);


(lib.atasteofturkey = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.interstitialturkey();
	this.instance.parent = this;
	this.instance.setTransform(-108.5,-110);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.atasteofturkey, new cjs.Rectangle(-108.5,-110,217,220), null);


(lib.atasteoftable = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.interstitialatasteoftable();
	this.instance.parent = this;
	this.instance.setTransform(-160,-240);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.atasteoftable, new cjs.Rectangle(-160,-240,320,480), null);


(lib.atasteofpotatoes = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.interstitialmashedpotatoes();
	this.instance.parent = this;
	this.instance.setTransform(-67.5,-109.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.atasteofpotatoes, new cjs.Rectangle(-67.5,-109.5,135,219), null);


(lib.atasteofgreens = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.interstitialgreens();
	this.instance.parent = this;
	this.instance.setTransform(-63.5,-60);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.atasteofgreens, new cjs.Rectangle(-63.5,-60,127,120), null);


(lib.atasteofcranberries = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.interstitialcranberries();
	this.instance.parent = this;
	this.instance.setTransform(-80.5,-34.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.atasteofcranberries, new cjs.Rectangle(-80.5,-34.5,161,69), null);


(lib.atasteof = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgwB8QgJgDAAgHQAAgFAIgDIAFgCQAEgCACgGQABgGAAgOIAAgRIAAhTIgTAAQgEAAgBgBQgCgCAAgFIAAgEQAAgFACgBQABgCAEAAIASAAIgBgOIgBgMQABgbAQgOQAPgPAcAAQATAAAMAJQANAJAAAOQAAAIgFAEQgEAEgIAAQgGAAgEgCQgEgDgDgEIgEgHQgGgMgKAAQgHAAgDAEQgEAEAAAHIAEAUQADAPABAMIAZAAQAEAAABABQACACAAAFIAAAEQAAAEgCACQgCACgDAAIgZAAIAABYQgBAXACAGQACAHADACIAGACQALAEAAAHQAAAGgIADQgJADgYAAQgaAAgIgDg");
	this.shape.setTransform(76.5,-2.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("Ag+BBQgZgaAAgmQAAgmAagaQAagaAmAAQAlAAAYAYQAYAYAAAmQAAAngaAbQgZAbglAAQgmAAgYgZgAgggzQgLAOAAAXQAAAiAPAXQAOAXAUAAQARAAALgOQAKgPAAgXQAAghgOgXQgPgXgUAAQgRAAgKAOg");
	this.shape_1.setTransform(60.4,1.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("Ag3BBQgZgZAAglQAAgoAZgaQAagaAmAAQAhAAAUATQATATAAAgQAAALgDADQgDAEgNAAIhBAAQgGAAgDgDQgDgDAAgFQAAgEADgDQADgCAFAAIAkAAIAJgBQACgCAAgEQAAgQgLgMQgMgLgPAAQgVAAgKASQgJASAAAZQAAAaANAUQAOAUAVAAQANAAAJgDQAJgDAIgGIAGgFQAJgHAFAAQADAAADADQACACAAAEQAAAEgEAGQgEAGgIAGQgPAMgOAGQgOAFgQAAQgkAAgYgZg");
	this.shape_2.setTransform(32,1.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgIBoQgJgDgGgGQgGgFgDgKQgCgJAAgaIAAhcIgQAAIgFgBIgCgFIAAgEQAAgGASgPIAHgGIAHgGQASgQAHAAIAEACQABAAAAABQAAAAABAAQAAABAAABQAAAAAAABIAAAgIAnAAQAEAAACACQABABAAAFIAAAEQAAAFgBACQgCACgEAAIgkAAIgDABIgBAEIAABVQAAAXAEAFQAEAGAKAAQAGAAAIgDIAMgDQAEAAACADQADACAAADQAAAKgPAJQgPAJgSAAQgKAAgIgDg");
	this.shape_3.setTransform(16.9,-0.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgNBaIgSgDIgFADIgGABIgDgBIgEgCQgFgFgFgOQgFgOAAgNQAAgFADgEQADgEAEAAQAIAAAIAOIAHAKQAFAIAJADQAJAFAJAAQALgBAHgFQAHgGAAgKQAAgPgcgNIgKgFQgbgOgKgKQgJgLAAgQQAAgXAPgOQAQgPAaAAIAKABIANADIAIgEIAGgBQAIAAAIAOQAIAOAAAPQAAAFgDAEQgCAEgGgBQgEABgDgEQgEgDgFgIQgGgMgIgDQgHgEgJgBQgJAAgHAGQgFAFAAAKQAAAHAGAGQAGAHAVAKIACABQAwAYAAAbQAAAZgTAPQgSARgcAAg");
	this.shape_4.setTransform(3.1,1.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAfBRIgKgJIgHAEQgUAOgWAAQgZAAgQgOQgQgPAAgYQABgbATgPQAVgPAkAAQAIAAAEACQAFADAAAGQAAAKgMAAQgQAAgLAIQgLAIAAAPQAAAOAJAIQAKAIAPAAQAQAAAHgHQAHgIAAgSIAAhBQAAgPgGgIQgHgIgMAAQgIAAgHADQgHAEgHAIIgEAEQgLAOgLAAQgHAAgEgFQgEgEAAgIQAAgQAUgLQAUgLAgAAQASAAANAFQAPAFAHAKQAFAGACALQADAKAAAZIAAA3QAAAKABAFQACAEADABIAFACQAMADgBAGQAAAIgLAHQgLAGgQAAQgIAAgIgJg");
	this.shape_5.setTransform(-13.3,1.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgkB7QgKgDAAgIQAAgHAKgDQAJgEACgCQACgDABgdIABhRIAAgtIgCgcQgBgFgDgBQgCgCgIAAIgHAAQgMAAgHADQgGADgFAHIgGALIgEAMIgGAFQgCACgDAAQgGAAgCgEQgDgFAAgKQAAgXAGgOQAFgOAJAAIACAAQANACAVAAIBlAAQAVAAAOgCIABAAQAJAAAGAOQAEAOAAAXQAAAKgBAFQgDAEgGAAIgGgCIgEgFIgGgMIgFgLQgEgHgIgDQgGgDgNAAIgHAAQgGAAgEACQgDABAAAFIgBAcIgBAtIABBRQABAdACADQACACAJAEQAKADgBAHQAAAIgKADQgJADgbAAQgaAAgKgDg");
	this.shape_6.setTransform(-33.9,-2.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAlB8QgKgDABgIQAAgGAMgFIADgBQAEgBACgDQACgCAAgEIgDgPIgGgSIgDgFIgCgCIgPgBIgZgBIgPAAQgPAAAAgLQABgPAPAAIAIAAIASABIASAAIgSguIgQgpIgFAAIgSArIgRAtIgRAsQgDAKgBAGQAAAFACAEQADAEAFACIAGACQAKAEAAAHQAAAIgIADQgJADgaAAQgaAAgJgDQgJgDAAgIQAAgHALgEIAGgDQANgIALgeIAEgKIAZg9IAHgQQAZg9AFgaQACgIAEgDQADgCAKAAQAFAAAFADQADACADAHIAbA5IAiBRIAIAUQAUAyALAGIAGADQALADAAAHQAAAIgLADQgKADgeAAQgfAAgLgDg");
	this.shape_7.setTransform(-67.2,-2.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.atasteof, new cjs.Rectangle(-82,-24.9,164,45.1), null);


(lib.whitelogo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AqoZMQk7iFjyjyQjxjyiFk6QiKlFAAlkQAAljCKlFQCFk6DxjzQDzjxE6iFQFFiKFjAAQFkAAFFCKQE6CFDyDxQDyDyCFE7QCKFFAAFjQAAFkiKFFQiFE7jyDxQjxDyk7CFQlFCKlkAAQljAAlFiKgALRMiQAAAOALAAIAyAAQALAAAAALIAACTQAAAIAGACQADACAKAAQAKAAAEgCQAFgCAAgIIAAiTQAAgLAMAAIAxAAQALAAAAgSQAAgRgMAAIigAAQgKAAAAAVgADSONIBCBFQADAEAFACQAGACALAAQAOAAAEgFQAGgEgIgJIhOhWQgJgKAKgIIBAg6QAJgJgMgMQgNgMgLALIhLBEQgFAEgDABQgGADgKAAQgKAAAAgNIAAg3QAAgMgRAAQgLAAgEADQgFACgBAIIAAC1QAAAMARAAQALAAAEgCQAGgDAAgHIAAg7QAAgHADgEQAEgEAFAAQAVgBAJAKgAhvOXQAKAAAGAJIAgAxQAFAJARAAQAOAAAFgFQAFgEgFgGIgigzQgEgGAHgGQAPgKAIgJQAOgQAAgYQABgfgVgTQgUgTggAAIhsAAQgIAAAAAIIgBC6QAAAMANAAIAPgBQAKgBAAgGIAAgxQAAgEADgDQADgDAEAAgAmPOxQAGAAAEAGIAMAbQAEAIAPAAQAIAAAGgCQAJgDgDgGIhXi8QgFgIgLAAQgMAAgEAKIhZC4QgGAMAXAAQASABADgIIAMgWQAEgLAIAAgArGNjIAOBtQAAAFAFACQAFADAEAAQAYAAgBgLIgVi2QgCgIgDgCQgEgDgGAAQgLAAgEAIIg8BQQgFAIgFAAQgFABgGgJIg3hOQgFgJgLAAQgKAAgEAEQgDADgCAKIgVCxQAAAGAGACQAFADAGAAQATAAACgLIANhoQACgIAEAAQAEAAADADIAtA9QAFAGAGAAQAGAAAEgFIAxg/QADgEADAAQAFAAACAGgAGyMaIAACwQAAAOANAAICcAAQAKAAAAgRQAAgSgKgBIh6AAQgJAAAAgKIAAgeQAAgFADgDQADgCAFAAIBGAAQAKAAAAgSQAAgSgLAAIhHAAQgJAAAAgJIAAgbQAAgKAIAAIB7AAQALAAAAgSQAAgKgCgDQgCgFgHABIicAAQgNAAAAANgAT5IwQgNANAAATQAAASANAMQANAOASAAQATAAAMgOQANgMAAgSQAAgTgNgNQgMgNgTAAQgSAAgNANgAP5JKQAnALAyAAQBUAAAzgsQAygtAAhKQAAgggMgfQgMgegWgWQgUgVgWgSQgXgRgzgkIgpgdQgbgVgNgSQgJgOAAgVQAAgaARgQQASgQAeAAQAtAAAiAcQAOAKAHAHQAGAHAOAVQAKAPAMAAQALAAAHgGQAHgGAAgIQAAgIgCgEIgUhcQgFgXgTAAQgJAAgJAGQgMAIgHAAIgMgCIgWgFQghgIgoABQhFAAgrAlQgsAmABA9QAAA0AfAmQAUAVARAPQAPALA/AsQBBAuAZAbQAcAggBAfQABAjgaAUQgaAWgpAAQgkAAgigSQghgTgWgfIgNgRQgIgLgNAAQgMAAgHAIQgIAHAAAMQAAAKACAHIAWBUQAEAQAFAGQAGAHALgBQAJAAALgIQAJgIAJAAIASAFgAjHGJIABACQAYBeBFA2QBHA2BkAAQCCAABMhRQBMhQAAiJQAAiFhMhPQhNhQh+AAQhoAAhHA3QhFA1gYBgIAAAAQgCALgHABQgHAAgCgLQgYhghHg2QhHg3hoAAQiAAAhMBRQhLBQAACIQAACFBLBQQBMBQB+AAQBoAABIg2QBHg2AYhfIAAgBQACgMAIAAQAGABADALgAFnIeQgGAGAAAKQAAAOAJAEQAIAEAUADQBVANB0AAQBFABAxgOQAvgOAlgeQAwgmAZg9QAZg9AAhOQAAhFgTg4QgVg5glglQgngng1gSQg1gThOABQhrAAheAMQgUAEgIAEQgJAEAAAOQAAAJAGAHQAGAHAIAAIARAAQALAAAEALQADAJAAAYIAAF6QAAAYgDAJQgEAMgLAAIgRAAQgIAAgGAHgAyyIfQgHAIABAJQAAAOAJAFQAIAFAWABICcAAQAYgBAJgFQAJgFAAgOQAAgKgHgHQgGgGgKAAIgTAAQgFgBgFgDQgGgDgCgFQgCgGAAgbIAAiKQAAgZAIgGQAEgDAeAAIBGAAQAbAAAHAEQAIADABANIABAFQAFAWASAAQANAAAGgIQAFgKAAgWIAAhIQAAgVgFgJQgGgJgNAAQgTAAgEAVIgBAGQgBAMgIAEQgHADgaAAIhHAAQgeAAgEgDQgIgGAAgZIAAhlQAAgiAIgJQAJgIAjAAIBtAAQAfAAANAEQAPAFAFAPIAIASQAIAOAOAAQAMAAAFgIQAGgKgEgPIgMg8QgFgVgZAAIlwAAQgVAAgJAGQgJAFAAAOQAAAJAGAIQAIAGAIAAIARAAQAEAAAEAEQAFAEAAAGQAEAIAAAYIAAF8QAAAXgCAKQgGAMgJAAIgSAAQgIAAgHAGgACorXQABAJgIAEQgoANgnAUQglASgaATQg5AoggBCQgfBEAABZQgBCLBPBTQBOBUCFABQCGAABQhVQBPhVAAiOQABilhohMQg9gtg2AHQgiAEgEAUQgFATAaAKQA2AUAZA8QAXA3ABBfQAABwgrBCQgrBChJAAQhLAAgqhBQgrhAAAhxQAAhRAQgzQATg+AwgvQAegeBGgiQA+gfAhgsQATgYABgVQACgTgQgFQgLgDgOANIgZAWQguAeg4gRQgvgPgjgpQgcgfgogIQgcgGgfAHQgLACgEgGQgCgHALgJQAbgUArABQAuADAfAcQAeAbAgAPQAjARAbgGQARgDAAgOQAAgPgTgGQgegLgng1Qgmg0g0gQQhOgWhLA9QhDA3gXBVQgGAXAMALQALALAWgJQA6gZAuAWQAKAFAgAUQAcARAWAJQAYAKAhAAQAYAAAWgEIAFgBQAJAAACAIgAvClPIBIDYQAHAXALAJQALAJATAAQATABALgLQAKgLAJggICImzQAGgXAIgJQAHgIALgCQAjgFAAAxIAAF+QAAAbgCAGQgBAFgFADQgEACgFAAIgQAAQgJABgHAGQgGAIgBAJQAAAPAJAEQAJAGAVAAICbAAQAVAAAIgFQAIgGAAgNQAAgKgGgHQgGgIgJAAIgQAAQgMAAgEgKQgCgLAAgWIAAiCQgBgcAGgIQAGgGAXAAIBzAAQAYAAAHAHQACAFABAGIAAAeIAAB8QAAAbgBAGQgGAKgKAAIgRAAQgIABgHAGQgGAIAAAJQAAAPAIAEQAJAGAVAAICaAAQAWAAAJgGQAJgEAAgPQAAgKgHgHQgGgGgKgBIgRAAQgEAAgFgCQgEgDgBgFQgDgIAAgZIAAl+QAAgaADgHQABgEAEgDQAFgEAEAAIARAAQAKAAAGgGQAHgIAAgKQgBgOgIgFQgJgFgWAAIiaAAQgWAAgIAFQgJAFAAAOQAAAKAGAIQAHAGAJAAIARAAQAFAAADADQAFADADAFQABAGAAAbIAABpIAAAdQgBAHgCADQgHAJgYgBIhzAAQgXAAgGgGQgGgHABgdIAAhuQAAgXACgKQAFgLALAAIAQAAQAKAAAFgGQAHgIAAgKQgBgOgHgFQgJgFgVAAIkmAAQgRAAgIAGQgHAFgBANQAAAVAcACQAeAEAAATQAAAHgEANIheE7QgBAFgFABQgDAAgCgGIhgktQgIgZgBgKQAAgMAHgEQAFgGARgCQAcgDgBgUQABgWgdAAIimAAQgfAAAAAaQABAJAFAFQAGAFANADQAPAEAGAEQAHAFADAJIAHAUIAfBaQAHAWgIAaIg/C3QgCAGgEAAQgFAAgCgEIhzlIQgDgIAAgLQAAgKAGgFQAGgFAOgBQARgBAGgGQAIgEgBgMQABgWgcAAIivAAQgdAAAAAWQAAAKAFAFQAFAGANACQAVAEAHAHQAHAIAJAaICnG/QAJAYALAIQAKAKATgBQARABALgKQAFgEADgHIAJgVIBOjZQABgFAEAAQAFAAACAGgAOkiCQgGAHAAAJQAAAOAJAFQAHAGAWAAIFjAAQAZAAAFgVIANhDQADgPgFgKQgEgIgNAAQgOAAgIAQIgHAQQgPAfgwAAIhUABQgigBgRgFQgKgEgDgLQgDgMAAghIAAhsQAAgZAIgFQAGgEAdAAIAmAAQAbAAAIAEQAHADACANIABAFQAEAXATAAQANgBAGgIQAEgKAAgWIAAhHQAAgWgEgJQgGgIgNgBQgTABgEAUIgBAGQgCAMgHAEQgHADgbAAIgnAAQgdAAgGgDQgIgFAAgaIAAhlQAAghAIgJQAJgJAjAAIBQAAQAfABANAEQAPAFAFAPIAJASQAHAOAOAAQANAAAEgJQAGgJgEgQIgMg7QgEgWgaAAIlTAAQgVABgJAFQgJAGAAAOQAAAJAGAHQAIAHAIAAIARAAQAEAAAEAEQAFADABAGQADAIAAAZIAAF8QAAAZgDAIQgCAFgDADQgEAEgFAAIgRAAQgJAAgGAGgAHyiCQgFAHAAAJQAAAOAIAFQAIAGAVAAIE/AAQAZAAAGgVIAMhDQAEgPgFgKQgFgIgMAAQgPAAgIAQIgHAQQgPAfgvAAIgwAAQgaAAgMgCQgMgBgGgEQgIgFgCgKQgCgJAAgcIAAllQABgbACgGQAEgLAOAAIASAAQAJAAAHgGQAGgHABgKQgBgOgIgGQgJgFgXgBIidAAQgWABgJAFQgJAGAAAOQAAAKAHAHQAGAGAKAAIARAAQAEAAAFADQAEADABAFQADAKABAXIAAGAQgBAXgDAIQgBAFgEADQgFAEgEAAIgRAAQgJAAgGAGg");
	this.shape.setTransform(0,0,0.217,0.217);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgYAZQgKgKAAgPQAAgOAKgLQAKgJAOgBQAPABAKAJQAKALAAAOQAAAPgKAKQgKALgPgBQgOABgKgLgAAWAZIgPgVQANgCAAgMQAAgQgRAAIgTAAIAAAzIAJAAIAAgVIAFAAIAOAVIAKAAg");
	this.shape_1.setTransform(28.3,12.8,0.217,0.217);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgrAiQgFAAgEgDQgEgEAAgFIAAgtQAAgKANAAIA+AAQAQAAALAJQALAJAAAPQAAAQgLAJQgLAJgQAAg");
	this.shape_2.setTransform(-2.4,18.4,0.217,0.217);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgJAHIAAgNIAIAAQALAAAAAGQAAAHgNAAg");
	this.shape_3.setTransform(28.3,12.6,0.217,0.217);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhvCtQgog/AAhrQAAhuAog/QApg/BGAAQBFAAAqBAQApA+AABsQAABrgpA/QgpA/hGAAQhGAAgpg9g");
	this.shape_4.setTransform(-10.6,6.5,0.217,0.217);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgYAfQgDAAgCgCQgBgDABgDIAZgxQACgEACAAQADAAACADIAZAzQABADgCACQAAABgBAAQAAAAgBABQAAAAgBAAQAAAAgBAAg");
	this.shape_5.setTransform(-9.6,19.1,0.217,0.217);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgtDsQgngCgNgHQgUgMgBggIAAljQAAghALgMQAIgMAdgEIAdgDQBKAAArA/QArA+AABvQgBBxgqBAQgqA8hFAAIgKgBg");
	this.shape_6.setTransform(14,6.5,0.217,0.217);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AhvCtQgog/AAhrQAAhuAog/QApg/BGAAQBFAAAqBAQApA+AABsQAABrgpA/QgpA/hFAAQhHAAgpg9g");
	this.shape_7.setTransform(1.5,6.5,0.217,0.217);

	this.instance = new lib.Path();
	this.instance.parent = this;
	this.instance.setTransform(15,-8.1,0.217,0.217,0,0,0,20.3,28.4);
	this.instance.alpha = 0.789;

	this.instance_1 = new lib.Path_1();
	this.instance_1.parent = this;
	this.instance_1.setTransform(3.2,-11.7,0.217,0.217,0,0,0,33.5,46.8);
	this.instance_1.alpha = 0.789;

	this.instance_2 = new lib.Path_2();
	this.instance_2.parent = this;
	this.instance_2.setTransform(-21.3,6.6,0.217,0.217,0,0,0,22.6,28.4);
	this.instance_2.alpha = 0.789;

	this.instance_3 = new lib.Path_3();
	this.instance_3.parent = this;
	this.instance_3.setTransform(-12.2,36,0.217,0.217,0,0,0,0.2,0.2);
	this.instance_3.alpha = 0.789;

	this.instance_4 = new lib.CompoundPath();
	this.instance_4.parent = this;
	this.instance_4.setTransform(-9.6,19.2,0.217,0.217,0,0,0,10.6,10.4);
	this.instance_4.alpha = 0.789;

	this.instance_5 = new lib.Path_4();
	this.instance_5.parent = this;
	this.instance_5.setTransform(4.9,19.2,0.217,0.217,0,0,0,9.7,10.4);
	this.instance_5.alpha = 0.789;

	this.instance_6 = new lib.Path_5();
	this.instance_6.parent = this;
	this.instance_6.setTransform(-16.9,19.2,0.217,0.217,0,0,0,12.2,10.4);
	this.instance_6.alpha = 0.789;

	this.instance_7 = new lib.Path_6();
	this.instance_7.parent = this;
	this.instance_7.setTransform(23.9,6.6,0.217,0.217,0,0,0,19.2,29.5);
	this.instance_7.alpha = 0.789;

	this.instance_8 = new lib.CompoundPath_1();
	this.instance_8.parent = this;
	this.instance_8.setTransform(-4.5,6.6,0.217,0.217,0,0,0,55.8,29.5);
	this.instance_8.alpha = 0.789;

	this.instance_9 = new lib.CompoundPath_2();
	this.instance_9.parent = this;
	this.instance_9.setTransform(28.4,12.8,0.217,0.217,0,0,0,2.1,2.6);
	this.instance_9.alpha = 0.789;

	this.instance_10 = new lib.Path_7();
	this.instance_10.parent = this;
	this.instance_10.setTransform(-16.2,-7.9,0.217,0.217,0,0,0,63.4,29.1);
	this.instance_10.alpha = 0.789;

	this.instance_11 = new lib.CompoundPath_3();
	this.instance_11.parent = this;
	this.instance_11.setTransform(-2.4,19.2,0.217,0.217,0,0,0,9.7,10.4);
	this.instance_11.alpha = 0.789;

	this.instance_12 = new lib.Path_8();
	this.instance_12.parent = this;
	this.instance_12.setTransform(11.4,19.2,0.217,0.217,0,0,0,9,10.4);
	this.instance_12.alpha = 0.789;

	this.instance_13 = new lib.Path_9();
	this.instance_13.parent = this;
	this.instance_13.setTransform(17.6,19.2,0.217,0.217,0,0,0,9.2,10.2);
	this.instance_13.alpha = 0.789;

	this.instance_14 = new lib.CompoundPath_4();
	this.instance_14.parent = this;
	this.instance_14.setTransform(28.3,12.9,0.217,0.217,0,0,0,4.6,4.6);
	this.instance_14.alpha = 0.789;

	this.instance_15 = new lib.CompoundPath_5();
	this.instance_15.parent = this;
	this.instance_15.setTransform(13.5,6.6,0.217,0.217,0,0,0,27,29.5);
	this.instance_15.alpha = 0.789;

	this.instance_16 = new lib.Path_10();
	this.instance_16.parent = this;
	this.instance_16.setTransform(24.8,-8.1,0.217,0.217,0,0,0,21.9,28.4);
	this.instance_16.alpha = 0.789;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_16},{t:this.instance_15},{t:this.instance_14},{t:this.instance_13},{t:this.instance_12},{t:this.instance_11},{t:this.instance_10},{t:this.instance_9},{t:this.instance_8},{t:this.instance_7},{t:this.instance_6},{t:this.instance_5},{t:this.instance_4},{t:this.instance_3},{t:this.instance_2},{t:this.instance_1},{t:this.instance},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.whitelogo, new cjs.Rectangle(-37.9,-37.9,75.9,75.9), null);


// stage content:
(lib.interstitialatasteoffivenomask = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_48 = function() {
		//onhover event to reveal green cta rectangle over orange rectangle
		this.btn_main.addEventListener("mouseover", fl_MouseOverHandler.bind(this));
		this.btn_main.addEventListener("mouseout", fl_MouseOutHandler.bind(this));
		
		function fl_MouseOverHandler()
		{
			this.cta_rollover.gotoAndPlay(2);
		}
		
		function fl_MouseOutHandler()
		{
		this.cta_rollover.gotoAndPlay(13);
		}
	}
	this.frame_273 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(48).call(this.frame_48).wait(225).call(this.frame_273).wait(7));

	// button
	this.btn_main = new lib.mainbutton();
	this.btn_main.parent = this;
	this.btn_main.setTransform(160.4,240.1,1.553,0.731,0,0,0,0.2,0.1);
	new cjs.ButtonHelper(this.btn_main, 0, 1, 2, false, new lib.mainbutton(), 3);

	this.timeline.addTween(cjs.Tween.get(this.btn_main).wait(280));

	// white-logo
	this.instance = new lib.whitelogo();
	this.instance.parent = this;
	this.instance.setTransform(160,37);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(9).to({scaleX:0.11,scaleY:0.11},0).to({scaleX:1.34,scaleY:1.34,alpha:1},6,cjs.Ease.get(1)).to({scaleX:1.24,scaleY:1.24},8,cjs.Ease.get(1)).wait(257));

	// black-rectangle
	this.instance_1 = new lib.blackrectangleinbox("synched",0);
	this.instance_1.parent = this;
	this.instance_1.setTransform(160,240);
	this.instance_1.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(280));

	// fade-from-white
	this.instance_2 = new lib.whiterectanglefade();
	this.instance_2.parent = this;
	this.instance_2.setTransform(172.5,253.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({alpha:0},9).wait(271));

	// date
	this.instance_3 = new lib.date();
	this.instance_3.parent = this;
	this.instance_3.setTransform(160,288.4);
	this.instance_3.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(31).to({x:-127,alpha:1},0).to({x:170},10,cjs.Ease.get(1)).to({x:160},6,cjs.Ease.get(1)).wait(233));

	// tasting event near you
	this.instance_4 = new lib.TASTINGEVENTNEARYOU();
	this.instance_4.parent = this;
	this.instance_4.setTransform(160,111.3);
	this.instance_4.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(9).to({x:-127,y:109.7,alpha:1},0).to({x:180,y:111.3},10,cjs.Ease.get(1)).to({x:160},6,cjs.Ease.get(1)).wait(255));

	// a-taste-of
	this.instance_5 = new lib.atasteof();
	this.instance_5.parent = this;
	this.instance_5.setTransform(160,151.8);
	this.instance_5.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(17).to({x:-127},0).to({x:180,alpha:1},10,cjs.Ease.get(1)).to({x:160},6,cjs.Ease.get(1)).wait(165).to({alpha:0},6).wait(76));

	// whole-foods-market
	this.instance_6 = new lib.atasteofwholefoods();
	this.instance_6.parent = this;
	this.instance_6.setTransform(160,228.1);
	this.instance_6.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(24).to({x:-127,alpha:1},0).to({x:180},10,cjs.Ease.get(1)).to({x:160},6,cjs.Ease.get(1)).wait(30).to({alpha:0},5).wait(205));

	// savory-sides
	this.instance_7 = new lib.savorysides();
	this.instance_7.parent = this;
	this.instance_7.setTransform(160,200.7);
	this.instance_7.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(70).to({x:-127},0).to({x:180,alpha:1},10,cjs.Ease.get(1)).to({x:160},6,cjs.Ease.get(1)).wait(20).to({alpha:0},5).wait(169));

	// delicious-desserts
	this.instance_8 = new lib.deliciousdesserts();
	this.instance_8.parent = this;
	this.instance_8.setTransform(160,198.2);
	this.instance_8.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(106).to({x:-127,alpha:1},0).to({x:170},10).to({x:160},6).wait(30).to({alpha:0},5).wait(123));

	// thanksgiving
	this.instance_9 = new lib.thanksgiving();
	this.instance_9.parent = this;
	this.instance_9.setTransform(160,199.2);
	this.instance_9.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(152).to({x:-127,alpha:1},0).to({x:180},10,cjs.Ease.get(1)).to({x:160},6,cjs.Ease.get(1)).wait(30).to({alpha:0},6).wait(76));

	// try-new-flavors
	this.instance_10 = new lib.trynewflavors();
	this.instance_10.parent = this;
	this.instance_10.setTransform(160,150.8);
	this.instance_10.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(214).to({x:-127,alpha:1},0).to({x:180},10).to({x:160},6).wait(50));

	// for-your-feast
	this.instance_11 = new lib.foryourfeast();
	this.instance_11.parent = this;
	this.instance_11.setTransform(160,199.2);
	this.instance_11.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(222).to({x:-127,alpha:1},0).to({x:180},10).to({x:160},6).wait(42));

	// find an event
	this.instance_12 = new lib.findanevent();
	this.instance_12.parent = this;
	this.instance_12.setTransform(160,274.1);
	this.instance_12.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(43).to({x:13.5,y:330.1,alpha:1},0).to({x:178.6},10,cjs.Ease.get(1)).to({x:160},6,cjs.Ease.get(1)).wait(221));

	// cta-rectangle
	this.instance_13 = new lib.ctarectangle();
	this.instance_13.parent = this;
	this.instance_13.setTransform(158.6,274.8);
	this.instance_13.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(43).to({x:13.5,y:330.1,alpha:1},0).to({x:178.6},10,cjs.Ease.get(1)).to({x:158.6},6,cjs.Ease.get(1)).wait(221));

	// orange-fruit
	this.instance_14 = new lib.atasteofgreens();
	this.instance_14.parent = this;
	this.instance_14.setTransform(256.5,60);
	this.instance_14.alpha = 0;

	this.instance_15 = new lib.orangefruit();
	this.instance_15.parent = this;
	this.instance_15.setTransform(70,38.5);
	this.instance_15.alpha = 0;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_15},{t:this.instance_14}]}).to({state:[{t:this.instance_15}]},9).to({state:[{t:this.instance_15}]},10).wait(261));
	this.timeline.addTween(cjs.Tween.get(this.instance_15).wait(9).to({alpha:1},10).wait(261));

	// greens
	this.instance_16 = new lib.atasteofgreens();
	this.instance_16.parent = this;
	this.instance_16.setTransform(256.5,60);
	this.instance_16.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_16).wait(19).to({alpha:1},10).wait(251));

	// mashed-potatoes
	this.instance_17 = new lib.atasteofpotatoes();
	this.instance_17.parent = this;
	this.instance_17.setTransform(67.5,337.5);
	this.instance_17.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_17).wait(29).to({alpha:1},10).wait(241));

	// turkey
	this.instance_18 = new lib.atasteofturkey();
	this.instance_18.parent = this;
	this.instance_18.setTransform(211.5,370);
	this.instance_18.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_18).wait(39).to({y:390},0).to({alpha:1},10).wait(231));

	// cranberries
	this.instance_19 = new lib.atasteofcranberries();
	this.instance_19.parent = this;
	this.instance_19.setTransform(80.5,445.5);
	this.instance_19.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_19).wait(49).to({alpha:1},10).wait(221));

	// table
	this.instance_20 = new lib.atasteoftable();
	this.instance_20.parent = this;
	this.instance_20.setTransform(160,240);

	this.timeline.addTween(cjs.Tween.get(this.instance_20).wait(280));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(135.1,221.1,395,545);
// library properties:
lib.properties = {
	id: '85088BD5353243C8B4895C262600CED3',
	width: 320,
	height: 480,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	webfonts: {},
	manifest: [
		{src:"images/index_atlas_.png", id:"index_atlas_"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['85088BD5353243C8B4895C262600CED3'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;