(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.webFontTxtInst = {}; 
var loadedTypekitCount = 0;
var loadedGoogleCount = 0;
var gFontsUpdateCacheList = [];
var tFontsUpdateCacheList = [];
lib.ssMetadata = [
		{name:"index_atlas_", frames: [[747,273,115,72],[604,273,141,183],[694,458,100,137],[604,458,88,228],[0,0,300,600],[302,0,300,600],[604,0,248,271]]}
];



lib.updateListCache = function (cacheList) {		
	for(var i = 0; i < cacheList.length; i++) {		
		if(cacheList[i].cacheCanvas)		
			cacheList[i].updateCache();		
	}		
};		

lib.addElementsToCache = function (textInst, cacheList) {		
	var cur = textInst;		
	while(cur != null && cur != exportRoot) {		
		if(cacheList.indexOf(cur) != -1)		
			break;		
		cur = cur.parent;		
	}		
	if(cur != exportRoot) {		
		var cur2 = textInst;		
		var index = cacheList.indexOf(cur);		
		while(cur2 != null && cur2 != cur) {		
			cacheList.splice(index, 0, cur2);		
			cur2 = cur2.parent;		
			index++;		
		}		
	}		
	else {		
		cur = textInst;		
		while(cur != null && cur != exportRoot) {		
			cacheList.push(cur);		
			cur = cur.parent;		
		}		
	}		
};		

lib.gfontAvailable = function(family, totalGoogleCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], gFontsUpdateCacheList);		

	loadedGoogleCount++;		
	if(loadedGoogleCount == totalGoogleCount) {		
		lib.updateListCache(gFontsUpdateCacheList);		
	}		
};		

lib.tfontAvailable = function(family, totalTypekitCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], tFontsUpdateCacheList);		

	loadedTypekitCount++;		
	if(loadedTypekitCount == totalTypekitCount) {		
		lib.updateListCache(tFontsUpdateCacheList);		
	}		
};
// symbols:



(lib.halfpagecranberries = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.halfpagegreens = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.halfpageorange = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();



(lib.halfpagepotatoes = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(3);
}).prototype = p = new cjs.Sprite();



(lib.halfpagetable = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(4);
}).prototype = p = new cjs.Sprite();



(lib.halfpagetrace = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(5);
}).prototype = p = new cjs.Sprite();



(lib.halfpageturkey = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(6);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.wholefoodsmarket = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgJBxQgJgEgIgFQgGgHgDgKQgCgKAAgcIAAhkIgRAAIgGgBIgCgFIAAgFQAAgGAUgQIAHgHIAIgHQATgQAIAAIAFACQAAAAAAAAQABABAAAAQAAABAAAAQABABAAAAIAAAkIApAAQAFAAACABQABACAAAFIAAAFQAAAFgCACQgBACgFAAIgmAAIgDACIgBAEIAABdQAAAXAEAHQAEAFALABQAGAAAJgEIANgCQAEAAADACQADACAAAEQgBAKgQAKQgPAJgVAAQgKAAgJgCg");
	this.shape.setTransform(54.5,28.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("Ag8BGQgbgbAAgoQAAgrAcgcQAbgcAqAAQAjAAAWAUQAVAVAAAjQAAALgEAEQgDADgOAAIhHAAQgHAAgCgCQgEgDAAgFQAAgFAEgDQACgDAHAAIAmAAIAJgBQADgBAAgFQAAgSgMgMQgMgNgRAAQgWAAgLAUQgLATAAAcQAAAcAPAVQAPAWAXAAQAOAAAKgDQAJgDAJgHIAHgFQAJgHAFAAQAFgBACADQADADAAAEQAAAEgFAHQgEAGgJAGQgQAOgPAGQgPAGgSgBQgmAAgbgbg");
	this.shape_1.setTransform(37.9,30.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AA9CJIgIgBQgIgEgSgWIgIgKIgDgFQgtg6gEAAQAAAAgBAAQAAAAAAAAQgBAAAAABQAAAAAAABIgBAIIAAAIIABAnQABALADADIAKAFQAJAEAAAHQAAAHgJAEQgKADgYAAQgdgBgJgDQgJgDAAgIQAAgHAJgDIAFgCQAFgDACgIQACgKAAgWIAAgXIAAgdIAAgWIgBhGQgBgRgDgDQgCgDgJgCIgGgCIgHgDIgCgGQAAgEAEgDQAEgDANgFIAZgHIAUgDQAFAAADAEQACADAAAJIgBAkIgBAxIAAAuIABAKQAAAAAAAAQAAABABAAQAAAAAAAAQABAAAAAAIAIgEIAOgLIASgSQAEgFAAgDQAAgCgHgDQgGgEAAgFQAAgJAJgDQAKgDAbgBQARABAJADQAIADAAAIQAAAIgOAEQgOADgFAEQgHAEgQAPIgDACIgGAIIgCADQAAAEAQAVIACADIAgAnQAOAPAHAGQAFADAMAEQAMAEAAAHQAAAIgJAEQgJADgUABg");
	this.shape_2.setTransform(18.2,25.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("Ag4BcQgJgDAAgHQAAgHAJgDIAFgDQAFgCACgGQABgGAAgPIAAgMIAAgQIAAgKQABgigCgKQgBgLgFgCIgJgEQgKgDgBgHQABgEADgDQADgDAJgEIAZgHIAQgEQAKAAADAZIAAAEIABABQAJgPALgIQALgIAKAAQANAAAIAIQAHAIABANQAAANgHAIQgFAHgLAAIgKgCIgIgFIgDgIQgCgEgDgBQgNAAgFASQgEASAAA4QAAARABAHQADAJAFACIAHADQALADAAAIQAAAGgKADQgKAEgZAAQgdAAgJgEg");
	this.shape_3.setTransform(0.4,29.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAhBYIgJgKIgJAEQgWAQgXAAQgcAAgQgQQgRgQAAgaQgBgeAWgPQAWgRAnAAQAJAAAFADQAEACAAAHQABALgNAAQgTAAgLAJQgLAJAAAPQAAAPAJAJQAKAJARAAQARAAAIgIQAIgIAAgTIAAhHQAAgQgIgJQgGgJgNAAQgJAAgIAEQgIAEgHAIIgEAFQgMAPgMAAQgHAAgFgFQgFgFAAgIQAAgSAXgMQAVgMAiAAQAUAAAPAGQAPAFAIALQAGAHACALQADAMAAAbIAAA7QAAALACAFQABAFAEABIAFACQAMADAAAGQAAAJgMAIQgMAHgRAAQgJAAgJgKg");
	this.shape_4.setTransform(-16.9,30.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("ABGCEQgLgDAAgJQAAgHAMgFIAIgEQAEgCABgJQABgIAAgZIAAgKIAAhPIgBgvIgXA+Qg3CPgMAAQgGAAgLgUQgLgTgag9IgpheIgBBKIgBAyIABAjQABAIADACIAIAEQAMAFAAAHQAAAIgJAEQgKADgXAAQgUAAgKgEQgJgDAAgIQAAgHAKgEQAKgFABgEQADgJADgwQADgvAAg7IAAgGQAAgUgCgHQgCgGgEgDIgJgEQgMgEAAgIQAAgHAJgDQAIgDAbAAIAbABIAHABQAEADANAhIALAbIAFANQAtBwAEAAQAEAAARgpQAQgnAXhCIAEgLQAHgVAGgGQADgDAHgCIAagBQAZAAAIADQAIADAAAHQAAAIgKAEIgGACQgFADgCAHQgCAIAAAcIACBrQACAvACAHQABAFAIADIAEABIAHAFQADACAAAEQAAAJgLADQgKADgfAAQgcAAgKgDg");
	this.shape_5.setTransform(-44.1,26);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgNBhIgUgDIgGADIgGABIgDAAIgEgDQgGgFgGgPQgFgPAAgOQAAgGADgEQADgEAFAAQAJAAAIAPIAIALQAFAIAKAEQAKAEAKAAQAMAAAHgGQAHgGAAgLQAAgPgegQIgLgFQgdgOgKgMQgLgMAAgSQAAgYARgPQARgQAcAAIAMABIANACIAJgDIAGgBQAJAAAJAPQAIAOAAARQAAAGgDAEQgCAEgGAAQgEAAgEgEQgEgDgGgKQgHgLgIgFQgHgEgLAAQgKAAgGAGQgHAGAAAKQAAAIAHAHQAHAHAWALIACABQA0AZAAAeQAAAagTASQgVARgeAAg");
	this.shape_6.setTransform(104.4,-21.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AhRBxQgWgZAAgoQAAguAZgbQAZgeAoAAIANACQAGACADAEQADAEAAAFQAAAKgMAAIgFgBIgFAAQgVAAgMARQgNAQAAAdQAAAgAOAUQANAUAWgBQASAAALgKQALgLAAgVIAAgzIAAhWQAAgNgCgFQgDgFgHgDIgFgBQgLgDAAgHQAAgFAEgEQAFgDAOgFIAVgGIARgDQAHAAACAFQADADAAAIIAAAKIgCBzIABBOQABARADADIANAEQAKACAAAHQAAAJgbAIIgSAGIgPABQgFAAgCgDQgDgDAAgGIAAgJIAAgEIgBgBIgGAEIgIAGQgLAJgKADQgLAFgLAAQgjAAgWgag");
	this.shape_7.setTransform(86,-25.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AhDBGQgbgcAAgpQAAgpAcgdQAcgcApAAQApAAAaAbQAZAaAAApQAAAqgcAeQgbAcgoAAQgoAAgbgbgAgjg3QgLAPAAAZQAAAkAPAZQARAZAVAAQATAAALgPQALgPAAgaQAAgkgQgYQgQgZgVAAQgTAAgLAPg");
	this.shape_8.setTransform(63.8,-21.4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AhDBGQgbgcAAgpQAAgpAcgdQAcgcApAAQAoAAAaAbQAaAaAAApQAAAqgbAeQgcAcgoAAQgpAAgagbgAgjg3QgLAPAAAZQAAAkAPAZQAQAZAWAAQASAAAMgPQALgPAAgaQAAgkgQgYQgPgZgWAAQgSAAgMAPg");
	this.shape_9.setTransform(42.8,-21.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AheCGQgLgDAAgJQAAgHAKgEQAKgEACgDQADgDABgdIAChIIgChFQgCgcgCgEQgCgCgKgEQgKgFAAgHQAAgIAJgCQAJgDAgAAIByAAIASgCIAKgCIAFABIADADQAEAHADANQAEANAAAJQAAAIgDAFQgEAEgFAAQgHAAgHgNIgGgIQgEgGgIgDQgJgDgMAAIgaAAQgRAAgJACQgKACgDAEQgDAEgCAMIgBAkIAAAPQAAAJACACQABACAFAAIAeAAQAPAAAGgEQAGgEACgMIAAgDQADgUAKAAQAIAAADALQADAKAAAkQAAAigDALQgDAKgIAAQgKAAgDgUIAAgDQgCgMgGgEQgGgFgPAAIgdAAQgFAAgCAEQgCADAAAMIAAAOIABA1QACALADACIAIAEQAMAFAAAHQAAAJgLADQgKADgdAAQgeAAgKgDg");
	this.shape_10.setTransform(21.2,-25.7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("Ag9BGQgagbAAgoQAAgrAbgcQAcgdAqAAQAkABAVAUQAVAVAAAjQAAAMgEADQgDADgOABIhHAAQgHAAgDgDQgDgEAAgEQAAgFADgDQADgDAHAAIAmAAIAKgBQACgBAAgFQAAgSgMgMQgMgNgRAAQgWAAgLAUQgLATAAAcQAAAcAPAVQAPAWAXAAQAOAAAJgDQAKgEAJgGIAHgFQAJgIAFABQAEAAADACQADADAAAEQAAAEgFAHQgFAHgHAFQgRAOgPAGQgPAFgSAAQgnAAgbgbg");
	this.shape_11.setTransform(-10.5,-21.4);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgfCGQgJgDAAgIQAAgGAHgDIAKgGQAEgDABgLIABglIAAgdIAAgiIAAgPQAAgvgCgOQgCgNgDgDIgMgEQgMgDAAgGQAAgFAEgDQADgEAOgEIAZgHIATgDQAFABACADQADAEAAAIIAAAOQgDBDAABDIACBAQABAOACADIALAFQAJAEAAAHQAAAHgKADQgJAEgZAAQgbAAgJgEg");
	this.shape_12.setTransform(-25.9,-25.7);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AhDBGQgbgcAAgpQAAgpAdgdQAbgcApAAQApAAAaAbQAZAaAAApQAAAqgbAeQgcAcgoAAQgpAAgagbgAgjg3QgLAPAAAZQAAAkAQAZQAQAZAVAAQATAAALgPQALgPAAgaQAAgkgPgYQgRgZgVAAQgTAAgLAPg");
	this.shape_13.setTransform(-41.3,-21.4);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AAaCGQgKgDABgHQgBgHAKgEIAHgCQAEgDACgIQACgIAAgUQAAg8gIgOQgIgQgTAAQgJAAgJAHQgJAGgFAJQgEAIgCAOQgCAOABAlQgBATACAHQABAGAFACIAGACQAKAEAAAHQAAAHgJADQgJAEgYAAQgeAAgJgEQgJgDAAgIQAAgGAJgEIAFgCQAGgDACgHQABgIAAgVIAAgfIAAgbIgBhVQgBgVgDgDQgCgDgLgDQgLgEAAgGQAAgFAEgEQAFgDARgGIATgGIARgCQAGAAADAFQACADAAAIIAAAIIgBBKIAAAKIABAFIACABIAEgFIAGgHQAKgJALgFQAKgFALAAQAgAAAQAWQAPAUAAAqIABARIAAAhIAAALQAAAKACADQABAEAFADIAFACQAJAEAAAGQAAAIgJADQgJAEgeAAQgYAAgJgEg");
	this.shape_14.setTransform(-63.2,-25.7);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAaBCIgohoQgMgigHgPQgIgQgHgFIgKgFQgKgDAAgHQAAgIAJgDQAJgDAjAAQAjAAAIADQAJADAAAIQAAAHgOAFIgCABQgEACgCACQgCADAAAEQAAAHAJAZIAfBRIANAfQAEAHADAAQACAAAEgGIAMgbIAEgIQAmhdAAgLQAAgGgCgEQgDgEgGgDIgFgCQgLgEAAgHQAAgIAIgDQAHgDAfAAQAeAAAHADQAIADAAAIQAAAHgLAFIgIAEQgNAIgZBAIgPAmIgkBYIgGARQgMAegIAAQgKAAgbhIgAhNB6IgCgGQgYg0glhfIgRgtIgLgXQgFgHgGgEIgFgCQgMgDAAgIQAAgIAJgDQAJgDAjAAQAkAAAIADQAJADAAAIQAAAHgPAGIgBAAQgFACgCACQgCADAAAEQAAAGAIAXIAgBSIAOAiQADAGAEAAQADAAAEgJIAJgVQAEgNAKAAQAMAAAAANIgDAMIgYA7IgFAOQgMAfgHAAQgHAAgHgQg");
	this.shape_15.setTransform(-93.4,-25.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.wholefoodsmarket, new cjs.Rectangle(-114.7,-50,229.4,100), null);


(lib.trynewflavors = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgNBhIgUgDIgGADIgGABIgDAAIgEgDQgGgFgGgPQgFgPAAgOQAAgGADgEQADgEAFAAQAJAAAIAPIAIALQAFAIAKAEQAKAEAKAAQAMAAAHgGQAHgGAAgLQAAgPgegQIgLgFQgdgOgKgMQgLgMAAgSQAAgYARgPQARgQAcAAIAMABIANACIAJgDIAGgBQAJAAAJAPQAIAOAAARQAAAGgDAEQgCAEgGAAQgEAAgEgEQgEgDgGgKQgHgLgIgFQgHgEgLAAQgKAAgGAGQgHAGAAAKQAAAIAHAHQAHAHAWALIACABQA0AZAAAeQAAAagTASQgVARgeAAg");
	this.shape.setTransform(132.6,4.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("Ag4BdQgJgEAAgHQAAgHAJgDIAFgDQAFgCABgGQADgHAAgOIAAgMIAAgPIAAgLQAAgigCgKQgCgLgDgCIgJgEQgLgDAAgGQgBgFAEgDQADgDAIgEIAagIIAQgDQAKAAACAaIABADIABABQAKgPAKgIQAKgIALAAQANAAAHAIQAIAIAAANQAAANgFAHQgHAIgKAAIgJgCIgIgGIgFgHQgCgEgBgBQgOAAgFASQgEASAAA4QAAARACAHQACAJAEACIAIADQAMADAAAIQAAAGgLAEQgLADgZAAQgcAAgJgDg");
	this.shape_1.setTransform(117.9,4.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AhDBGQgbgbAAgqQAAgpAdgcQAbgdApAAQAoAAAaAbQAaAaAAApQAAArgbAdQgcAcgoAAQgpABgagcgAgjg3QgLAPAAAaQAAAkAQAYQAPAZAWAAQASAAAMgPQALgQAAgZQAAgkgQgYQgPgZgWAAQgSAAgMAPg");
	this.shape_2.setTransform(99.8,4.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgTBOQgMgSgZg9IgLgcQgOgkgIgDIgGgDQgKgFgBgGQAAgIAKgDQAJgCAfAAQAZAAAKACQAIADABAIIgCAGIgDADIgHADQgHADAAAEIAEAPIAPAkIAOAkQAFAIACAAQADAAADgEIAJgRIAUguQAGgTAAgGIgBgHIgEgEIgGgCQgIgDAAgHQAAgHAIgDQAJgCAXAAQATAAAIACQAJADAAAHQAAAIgKADIgHADQgIADgRAlIgEAMIgIARQgrBggLAAQgIABgKgTg");
	this.shape_3.setTransform(79.7,4.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAhBYIgKgKIgIAEQgXAQgXAAQgbAAgRgQQgQgQAAgaQAAgeAVgPQAWgRAnAAQAJAAAEADQAGACAAAHQgBALgNAAQgSAAgLAJQgLAJAAAPQAAAPAKAJQAKAJAQAAQASAAAHgIQAIgIAAgTIAAhHQAAgQgHgJQgIgJgMAAQgJAAgIAEQgHAEgIAIIgEAFQgMAPgMAAQgHAAgFgFQgEgFAAgIQAAgSAVgMQAWgMAjAAQATAAAPAGQAPAFAIALQAGAHACALQACAMAAAbIAAA7QAAALADAFQABAFAEABIAGACQAMADgBAGQAAAJgMAIQgMAHgSAAQgHAAgKgKg");
	this.shape_4.setTransform(60.2,4.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgfCGQgJgDAAgIQAAgGAHgDIAKgFQADgEACgLIABglIAAgdIAAgiIAAgPQAAgvgCgOQgCgOgEgBIgLgFQgMgDAAgHQAAgEAEgDQAEgEANgEIAZgHIATgDQAFABADADQACADAAAJIAAAPQgDBCAABEIACA/QABAOACADIALAFQAJAEAAAHQAAAHgKADQgJAEgZAAQgbgBgJgDg");
	this.shape_5.setTransform(44.4,0);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AheCGQgLgDAAgJQAAgHAKgEQAKgEACgDQADgDABgdIAChIIgChFQgCgcgCgEQgCgCgKgEQgKgFAAgHQAAgIAJgCQAJgDAgAAIByAAIASgCIAKgCIAFABIADADQAEAHADANQAEANAAAJQAAAIgDAFQgEAEgFAAQgHAAgHgNIgGgIQgEgGgIgDQgJgDgMAAIgaAAQgRAAgJACQgKACgDAEQgDAEgCAMIgBAkIAAAPQAAAJACACQABACAFAAIAeAAQAPAAAGgEQAGgEACgMIAAgDQADgUAKAAQAIAAADALQADAKAAAkQAAAigDALQgDAKgIAAQgKAAgDgUIAAgDQgCgMgGgEQgGgFgPAAIgdAAQgFAAgCAEQgCADAAAMIAAAOIABA1QACALADACIAIAEQAMAFAAAHQAAAJgLADQgKADgdAAQgeAAgKgDg");
	this.shape_6.setTransform(28.4,0);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AALAUIgXg6QgKgagJgEIgFgDQgLgFAAgGQAAgIAJgDQAKgCAdAAQAZAAAKACQAJADAAAIIgCAFIgDAEIgGADQgIADAAAEIAEANIAPAmIAQAkQAEAIACAAQADAAAEgEIAIgRIAUguQAHgTAAgGIgCgHIgEgEIgFgCQgJgDAAgHQAAgHAJgDQAIgCAXAAQAUAAAIACQAIADAAAHQAAAIgKADIgHADQgIAEgRAnIgEAJIgIARQgqBggMAAQgNAAghhMgAhuALIgEgMIgNgfQgMgggJgEIgFgDQgLgFAAgGQAAgIAJgDQAKgCAfAAQAZAAAJACQAJADAAAIIgCAGIgDADIgGADQgIADAAAEIAFAPIAOAkIAPAjQAGAJABAAQAGAAAFgLIAHgOIAEgFQACgCAEAAQAFAAADADQACACAAAFQAAAFgFAKQgTAsgJAOQgJANgGAAQgNAAgmhVg");
	this.shape_7.setTransform(-8.5,4.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("Ag9BGQgagbAAgoQAAgrAbgcQAcgdApAAQAlABAVAUQAVAVAAAjQAAAMgDADQgEADgOAAIhHAAQgGAAgDgCQgEgEAAgEQAAgFAEgDQADgDAGAAIAmAAIAJgBQADgBAAgFQAAgSgMgMQgMgNgRAAQgWAAgLAUQgKATAAAcQAAAcAOAVQAPAWAXAAQAOAAAJgDQAKgEAJgGIAGgFQAKgIAGABQAEAAACACQADADAAAEQAAAEgFAHQgFAHgHAFQgRAOgPAGQgPAFgSAAQgnAAgbgbg");
	this.shape_8.setTransform(-34,4.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AARA0IgGgIIgogzIgmgwIgQgSIgBANIAAAZIAAASQAABSADAUQACAVAGAAQAFAAAFAFQAGADAAAGQAAAIgJADQgJAEgWgBQgWABgJgEQgJgDAAgIQAAgHAKgFQAKgEACgCQACgDACgbIABhKIgChGQgBgcgCgDQgCgCgKgFQgKgEAAgHQAAgHAIgDQAJgDAXgBIAVABIAHADIAaAhIAmAwIApAzIAdAjIAUAWIAAgIIAAgOIgBhcQgBgmgCgHIgCgDIgFgEQgKgEgCgCQgDgCAAgFQAAgHAIgDQAHgEAaAAQAXAAAIAEQAHADAAAHQAAAEgCACIgHAFIgEACQgIADgBAEQgDAIAAAlIgBBwIAAAjIAAAXQAAAPgCAEQgBACgGAAQgTAAhDhTg");
	this.shape_9.setTransform(-58.5,0.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AhWB8QgIgIgBgMQAAgJAHgHQAGgHAKAAIAIACIAGAEIAFAHQAFAHADAAQAKAAAJgOQALgNgBgPQAAgQgNgeIgCgEIgehBIgRgkQgDgHgLgFQgGgDgDgCQgCgDAAgEQAAgIAJgDQAKgDAcAAQAbAAAKADQAIADABAHIgBAGIgEADIgHADQgHADAAAEIAEAOIAPAlIAOAjQAGAJACAAQACAAAEgJIAMgdIAPglQADgOAAgEQAAgGgKgGQgLgGAAgEQABgHAIgDQAIgCAWAAQAWAAAIADQAIADAAAHQAAAHgLADIgHACQgLAGgMAgIgGAOIgXA8QgfBNgTAYQgUAXgbAAQgOAAgJgHg");
	this.shape_10.setTransform(-92.7,8.1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("Ag4BdQgJgEAAgHQAAgHAJgDIAFgDQAFgCACgGQABgHAAgOIAAgMIAAgPIAAgLQABgigCgKQgBgLgFgCIgJgEQgKgDgBgGQABgFADgDQADgDAJgEIAZgIIAQgDQAKAAADAaIAAADIABABQAJgPALgIQALgIAKAAQANAAAIAIQAHAIABANQAAANgHAHQgFAIgLAAIgKgCIgIgGIgDgHQgCgEgDgBQgNAAgFASQgEASAAA4QAAARABAHQADAJAFACIAHADQALADAAAIQAAAGgKAEQgKADgZAAQgdAAgJgDg");
	this.shape_11.setTransform(-108.9,4.2);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgnCFQgKgDAAgJQAAgHAKgEQAKgEACgDQACgCABggIABhYIAAgxIgCgdQgBgFgDgCQgDgCgIAAIgIAAQgNAAgHADQgHAEgFAGIgGANIgFANIgGAGQgDACgEAAQgFAAgDgFQgCgFAAgLQAAgZAFgPQAGgPAJgBIACABQAPACAXAAIBtAAQAXAAAPgCIACgBQAJABAGAPQAFAPAAAZQAAALgCAFQgDAFgGAAIgGgCIgFgGIgGgNIgGgNQgFgGgHgEQgIgDgNAAIgHAAQgIAAgDACQgDACgBAFIgCAdIAAAxIABBYQABAgACACQACADAKAEQAKAEAAAHQAAAJgKADQgLADgdABQgcgBgLgDg");
	this.shape_12.setTransform(-128.7,0.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.trynewflavors, new cjs.Rectangle(-142.8,-24.2,285.7,48.5), null);


(lib.thanksgiving = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhFB6QgXgPAAgUQAAgKAEgGQAGgGAKAAQAIAAAEAFQAEAEADAJQAEAOAMAHQAMAIAXAAQAYAAAQgJQARgKAAgOQAAgJgHgFQgFgFgMAAIgWACIgcABQghAAgSgLQgSgLAAgPQAAgKAHgJQAGgIANgIQgLgKgFgMQgGgMABgOQAAgfAWgUQAXgUAkAAIATACIAcAFQAHAAAJgDQAIgEALgIIAHAGIABAGQAAAIgGAIQgFAHgMAGIAGAPIACAPQAAAfgWAUQgYASgjAAIgUgBIgRgEIgHAHIgCAHQAAAJAJAEQAJAEATAAIAbgCIAdgCQAbAAAOALQANAKAAAUQAAAegdAUQgdAUgsAAQgkAAgYgPgAgehcQgKAMAAASQAAATAKAMQAJAMAPAAQAQAAAKgMQAKgMAAgTQAAgTgKgMQgKgMgQAAQgOAAgKANg");
	this.shape.setTransform(104.9,7.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AhbBdQgKgEAAgHQAAgHAJgDIAGgDQAEgCACgGQADgHAAgOIgBgMIAAgPIAAgTQAAgegCgIQgBgJgDgCIgJgEQgMgDAAgGQAAgEAEgEQADgDAIgEIAbgIIATgDQAGAAACACQADAEAAAFIAAANIAAACIABAAIABAAIABAAIAEgFIAEgDQAUgTAXAAQANAAANAGQANAGAIAKQAJAKADAOQAEAPAAAdIAAAZIAAAMIAAALQAAANACAFQACAGAEACIAFADQAJADAAAHQAAAHgJAEQgIACgdAAQgaAAgJgCQgJgDAAgHQAAgIAJgDIAIgDQAEgCACgJQACgHAAgVQgBg6gHgPQgIgQgUAAQgJAAgJAHQgJAFgFAKQgEAIgBAPQgCAOAAAlQAAASACAGQABAGAEACIAHADQAJADAAAIQAAAHgJADQgJADgZAAQgcAAgJgDg");
	this.shape_1.setTransform(83.2,4.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AggCFQgKgDAAgIQAAgGAJgEIAFgCQAFgCACgGQACgHAAgOIAAgNIAAgPIAAgTQAAgegCgIQgBgIgEgCIgJgEQgLgDAAgHQAAgEAEgDQADgDAIgEIAcgJIATgDQAFAAADADQACAEAAAJIAAALIgBAIIgBAvIAAABIgBAuQAAASACAHQABAIAFACIAHADQAJADAAAHQAAAIgJADQgJADgZAAQgbAAgJgEgAgWheQgIgGAAgKQAAgLAJgHQAIgIANAAQALAAAIAHQAIAHAAAKQAAAKgIAIQgJAHgMAAQgMAAgIgHg");
	this.shape_2.setTransform(66.7,0.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgUBOQgKgSgag9IgLgcQgOgkgIgDIgGgDQgLgFABgGQAAgIAJgDQAKgCAeAAQAZAAAJACQAKADgBAIIgBAGIgDADIgGADQgIADAAAEIAEAPIAOAkIAQAkQAEAIACAAQADAAADgEIAIgRIAUguQAHgTAAgGIgBgHIgEgEIgGgCQgIgDAAgHQAAgHAIgDQAJgCAXAAQATAAAJACQAHADAAAHQAAAIgKADIgGADQgJADgPAlIgGAMIgHARQgqBggMAAQgIABgLgTg");
	this.shape_3.setTransform(51.9,4.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AggCFQgKgDAAgIQAAgGAJgEIAFgCQAFgCACgGQACgHAAgOIAAgNIAAgPIAAgTQAAgegCgIQgBgIgEgCIgJgEQgLgDAAgHQAAgEAEgDQADgDAIgEIAcgJIATgDQAFAAADADQACAEAAAJIAAALIgBAIIgBAvIAAABIgBAuQAAASACAHQABAIAFACIAHADQAJADAAAHQAAAIgJADQgJADgZAAQgbAAgJgEgAgWheQgIgGAAgKQAAgLAJgHQAIgIANAAQALAAAIAHQAIAHAAAKQAAAKgIAIQgJAHgMAAQgMAAgIgHg");
	this.shape_4.setTransform(36.7,0.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AhEB6QgYgPAAgUQAAgKAEgGQAGgGAKAAQAIAAAEAFQAEAEADAJQAEAOAMAHQAMAIAXAAQAYAAARgJQAQgKAAgOQAAgJgGgFQgHgFgLAAIgWACIgcABQghAAgSgLQgSgLAAgPQAAgKAGgJQAHgIANgIQgKgKgGgMQgFgMAAgOQAAgfAWgUQAXgUAkAAIASACIAdAFQAHAAAJgDQAIgEALgIIAHAGIABAGQAAAIgGAIQgGAHgKAGIAFAPIACAPQAAAfgWAUQgYASgjAAIgUgBIgSgEIgGAHIgCAHQABAJAIAEQAJAEATAAIAbgCIAegCQAaAAANALQAPAKAAAUQAAAegeAUQgdAUgtAAQgjAAgXgPgAgehcQgKAMAAASQAAATAKAMQAJAMAQAAQAOAAALgMQAKgMAAgTQAAgTgKgMQgKgMgPAAQgPAAgKANg");
	this.shape_5.setTransform(22.3,7.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgNBhIgUgDIgGADIgGABIgDAAIgEgDQgGgFgGgPQgFgPAAgOQAAgGADgEQADgEAFAAQAJAAAIAPIAIALQAFAIAKAEQAKAEAKAAQAMAAAHgGQAHgGAAgLQAAgPgegQIgLgFQgdgOgKgMQgLgMAAgSQAAgYARgPQARgQAcAAIAMABIANACIAJgDIAGgBQAJAAAJAPQAIAOAAARQAAAGgDAEQgCAEgGAAQgEAAgEgEQgEgDgGgKQgHgLgIgFQgHgEgLAAQgKAAgGAGQgHAGAAAKQAAAIAHAHQAHAHAWALIACABQA0AZAAAeQAAAagTASQgVARgeAAg");
	this.shape_6.setTransform(3.5,4.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AA9CJIgIgBQgIgEgSgWIgIgKIgDgFQgtg6gEAAQAAAAgBAAQAAAAAAAAQgBAAAAABQAAAAAAABIgBAIIAAAIIABAnQABALADADIAKAFQAJAEAAAHQAAAHgJADQgKAEgYAAQgdgBgJgDQgJgDAAgIQAAgHAJgDIAFgCQAFgDACgIQACgKAAgWIAAgXIAAgdIAAgWIgBhGQgBgRgDgDQgCgCgJgDIgGgCIgHgDIgCgGQAAgEAEgDQAEgEANgEIAZgHIAUgDQAFABADADQACADAAAJIgBAkIgBAxIAAAuIABAKQAAAAAAAAQAAABABAAQAAAAAAAAQABABAAAAIAIgFIAOgLIASgSQAEgFAAgDQAAgCgHgDQgGgEAAgFQAAgJAJgDQAKgDAbAAQARAAAJADQAIADAAAHQAAAJgOAEQgOADgFAEQgHAEgQAPIgDACIgGAIIgCADQAAAEAQAVIACADIAgAnQAOAPAHAGQAFADAMAEQAMAEAAAHQAAAIgJAEQgJADgUABg");
	this.shape_7.setTransform(-14.2,0);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AhbBdQgJgEAAgHQAAgHAJgDIAEgDQAGgCABgGQACgHAAgOIAAgMIAAgPIAAgTQAAgegCgIQgBgJgEgCIgJgEQgLgDAAgGQAAgEAEgEQADgDAJgEIAbgIIASgDQAGAAACACQADAEgBAFIAAANIABACIABAAIABAAIABAAIAEgFIAEgDQAUgTAXAAQAOAAAMAGQAMAGAJAKQAJAKAEAOQADAPAAAdIAAAZIAAAMIgBALQAAANACAFQADAGAEACIAFADQAJADAAAHQAAAHgIAEQgJACgdAAQgaAAgJgCQgJgDAAgHQAAgIAKgDIAHgDQADgCACgJQACgHAAgVQABg6gIgPQgIgQgTAAQgKAAgJAHQgJAFgFAKQgEAIgCAPQgBAOAAAlQAAASABAGQACAGAEACIAHADQAKADAAAIQAAAHgKADQgJADgYAAQgdAAgJgDg");
	this.shape_8.setTransform(-36.5,4.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AAhBYIgJgKIgJAEQgXAQgWAAQgcAAgQgQQgRgQgBgaQAAgeAWgPQAWgRAnAAQAJAAAFADQAEACAAAHQAAALgMAAQgTAAgLAJQgLAJAAAPQAAAPAJAJQALAJAQAAQARAAAIgIQAIgIAAgTIAAhHQAAgQgIgJQgGgJgNAAQgJAAgIAEQgIAEgHAIIgEAFQgLAPgNAAQgHAAgFgFQgFgFAAgIQAAgSAXgMQAVgMAiAAQAUAAAPAGQAPAFAIALQAGAHACALQACAMABAbIAAA7QAAALABAFQACAFAEABIAFACQANADAAAGQAAAJgNAIQgNAHgQAAQgJAAgJgKg");
	this.shape_9.setTransform(-57.3,4.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAaCGQgKgDABgHQgBgHAKgEIAHgCQAEgDACgIQACgIAAgTQAAg9gIgOQgIgPgTgBQgJAAgJAHQgJAGgFAJQgEAIgCAOQgCAOABAlQgBATACAHQABAFAFADIAGACQAKAEAAAHQAAAHgJADQgJAEgYAAQgegBgJgDQgJgDAAgIQAAgGAJgEIAFgCQAGgDACgHQABgJAAgTIAAggIAAgbIgBhVQgBgVgDgDQgCgDgLgDQgLgEAAgGQAAgFAEgEQAFgDARgHIATgFIARgCQAGAAADAFQACADAAAIIAAAIIgBBKIAAAKIABAFIACABIAEgFIAGgHQAKgJALgFQAKgFALAAQAgAAAQAWQAPAUAAAqIABARIAAAhIAAALQAAAKACADQABAEAFADIAFACQAJADAAAHQAAAIgJADQgJADgeABQgYAAgJgEg");
	this.shape_10.setTransform(-79,0);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgnCFQgKgDAAgJQAAgHAKgEQAKgEACgDQACgCABggIABhYIAAgxIgCgdQgBgFgDgCQgDgCgIAAIgIAAQgNAAgHADQgHAEgFAGIgGANIgFANIgGAGQgDACgEAAQgFAAgDgFQgCgFAAgLQAAgZAFgPQAGgPAJgBIACABQAPACAXAAIBtAAQAXAAAPgCIACgBQAJABAGAPQAFAPAAAZQAAALgCAFQgDAFgGAAIgGgCIgFgGIgGgNIgGgNQgFgGgHgEQgIgDgNAAIgHAAQgIAAgDACQgDACgBAFIgCAdIAAAxIABBYQABAgACACQACADAKAEQAKAEAAAHQAAAJgKADQgLADgdABQgcgBgLgDg");
	this.shape_11.setTransform(-102,0.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.thanksgiving, new cjs.Rectangle(-116.1,-24.2,232.3,48.5), null);


(lib.savorysides = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgNBhIgUgDIgGADIgGABIgDAAIgEgDQgGgFgGgPQgFgPAAgOQAAgGADgEQADgEAFAAQAJAAAIAPIAIALQAFAIAKAEQAKAEAKAAQAMAAAHgGQAHgGAAgLQAAgPgegQIgLgFQgdgOgKgMQgLgMAAgSQAAgYARgPQARgQAcAAIAMABIANACIAJgDIAGgBQAJAAAJAPQAIAOAAARQAAAGgDAEQgCAEgGAAQgEAAgEgEQgEgDgGgKQgHgLgIgFQgHgEgLAAQgKAAgGAGQgHAGAAAKQAAAIAHAHQAHAHAWALIACABQA0AZAAAeQAAAagTASQgVARgeAAg");
	this.shape.setTransform(99.7,4.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("Ag8BGQgbgbAAgoQAAgrAcgcQAbgdAqAAQAjABAWAUQAVAVAAAjQAAAMgDADQgEADgOAAIhHAAQgGAAgDgCQgEgEAAgEQAAgFAEgDQADgDAGAAIAmAAIAJgBQADgBAAgFQAAgSgMgMQgMgNgRAAQgWAAgLAUQgLATAAAcQAAAcAPAVQAPAWAXAAQAOAAAKgDQAJgEAJgGIAGgFQAKgIAFABQAEAAADACQADADAAAEQAAAEgFAHQgEAHgJAFQgQAOgPAGQgPAFgSAAQgmAAgbgbg");
	this.shape_1.setTransform(81.9,4.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AhRBxQgWgZAAgoQAAguAZgbQAZgdAogBIANACQAGACADAEQADAEAAAFQAAAKgMAAIgFgBIgFAAQgVAAgMARQgNAQAAAdQAAAgAOAUQANATAWAAQASAAALgKQALgLAAgVIAAgzIAAhWQAAgMgCgGQgDgFgHgDIgFgBQgLgDAAgHQAAgFAEgEQAFgDAOgFIAVgGIARgDQAHAAACAFQADADAAAIIAAAJIgCB0IABBOQABARADADIANAEQAKACAAAHQAAAJgbAIIgSAGIgPABQgFAAgCgDQgDgCAAgHIAAgJIAAgEIgBgBIgGAEIgIAGQgLAIgKAFQgLAEgLgBQgjABgWgag");
	this.shape_2.setTransform(61.6,0.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AggCFQgKgDAAgIQAAgGAJgEIAFgCQAFgCACgGQACgHAAgOIAAgNIAAgPIAAgTQAAgegCgIQgBgIgEgCIgJgEQgLgDAAgHQAAgEAEgDQADgDAIgEIAcgJIATgDQAFAAADADQACAEAAAJIAAALIgBAIIgBAvIAAABIgBAuQAAASACAHQABAIAFACIAHADQAJADAAAHQAAAIgJADQgJADgZAAQgbAAgJgEgAgWheQgIgGAAgKQAAgLAJgHQAIgIANAAQALAAAIAHQAIAHAAAKQAAAKgIAIQgJAHgMAAQgMAAgIgHg");
	this.shape_3.setTransform(44.4,0.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgtCHQgVgFgNgHQgIgFgFgQQgFgQAAgVQAAgIAEgFQADgEAGAAQAJAAAJAQIAFAIQALAVAPAKQAOAJATAAQAUAAAOgMQAOgMAAgSQAAgag3gYIgGgDQgtgTgPgRQgPgQAAgbQAAghAZgWQAZgWAnAAIAWACIAZAGIAIgFIAGgBQAFAAAEADQADACAEAIQAHALADAMQAEAMAAAKQAAAGgDAEQgDADgFAAQgKAAgKgNIgCgEQgLgOgMgGQgNgHgPAAQgVAAgMAKQgMAJAAARQAAAPAKALQAKAKAoARIAIADQAhAOAPANQAKAJAGANQAFANAAAPQAAAmgbAVQgaAWgvAAQgXAAgUgFg");
	this.shape_4.setTransform(28.3,0.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AhWB8QgJgIAAgMQABgJAGgHQAHgHAJAAIAIACIAGAEIAFAHQAFAHADAAQAKAAAKgOQAKgNAAgPQAAgQgOgeIgCgEIgdhBIgSgkQgDgHgLgFQgHgDgCgCQgCgDAAgEQAAgIAJgDQALgDAbAAQAbAAAJADQAJADAAAHIgBAGIgDADIgHADQgHADAAAEIAEAOIAPAlIAOAjQAFAJADAAQACAAAEgJIAMgdIAPglQADgOAAgEQAAgGgKgGQgKgGAAgEQAAgHAIgDQAJgCAVAAQAWAAAIADQAIADAAAHQAAAHgLADIgHACQgLAGgMAgIgGAOIgXA8QgfBNgTAYQgUAXgbAAQgNAAgKgHg");
	this.shape_5.setTransform(-2,8.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("Ag4BdQgJgEAAgHQAAgHAJgDIAFgDQAFgCACgGQACgHAAgOIAAgMIAAgPIAAgLQgBgigBgKQgCgLgEgCIgJgEQgLgDABgGQAAgFADgDQADgDAJgEIAZgIIAQgDQAJAAAEAaIAAADIABABQAKgPAKgIQAKgIALAAQANAAAIAIQAHAIABANQgBANgFAHQgHAIgKAAIgKgCIgIgGIgDgHQgCgEgDgBQgMAAgGASQgEASAAA4QAAARACAHQABAJAGACIAHADQAMADAAAIQAAAGgLAEQgLADgYAAQgdAAgJgDg");
	this.shape_6.setTransform(-18.2,4.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AhDBGQgbgbAAgqQAAgpAcgcQAcgdApAAQAoAAAaAbQAaAaAAApQAAArgcAdQgbAcgoAAQgoABgbgcgAgjg3QgLAPAAAaQAAAkAPAYQAQAZAWAAQASAAAMgPQALgQAAgZQAAgkgQgYQgPgZgWAAQgSAAgMAPg");
	this.shape_7.setTransform(-36.3,4.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgUBOQgLgSgZg9IgLgcQgOgkgIgDIgFgDQgMgFAAgGQAAgIAKgDQAKgCAeAAQAZAAAKACQAIADABAIIgCAGIgDADIgGADQgIADAAAEIAEAPIAPAkIAPAkQAEAIACAAQACAAAEgEIAJgRIATguQAHgTAAgGIgBgHIgFgEIgEgCQgJgDAAgHQAAgHAJgDQAHgCAYAAQAUAAAHACQAJADgBAHQABAIgLADIgGADQgJADgPAlIgGAMIgHARQgrBggLAAQgIABgLgTg");
	this.shape_8.setTransform(-56.4,4.6);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AAhBYIgJgKIgJAEQgXAQgWAAQgcAAgQgQQgSgQABgaQgBgeAWgPQAWgRAnAAQAJAAAFADQAEACAAAHQABALgNAAQgTAAgLAJQgLAJAAAPQAAAPAJAJQAKAJARAAQASAAAHgIQAIgIAAgTIAAhHQAAgQgIgJQgHgJgMAAQgJAAgIAEQgIAEgHAIIgEAFQgMAPgMAAQgHAAgFgFQgEgFgBgIQAAgSAXgMQAVgMAjAAQATAAAPAGQAPAFAIALQAGAHACALQADAMAAAbIAAA7QAAALACAFQABAFAEABIAFACQAMADAAAGQAAAJgMAIQgMAHgRAAQgJAAgJgKg");
	this.shape_9.setTransform(-76,4.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgtCHQgVgFgNgHQgIgFgFgQQgFgQAAgVQAAgIAEgFQADgEAGAAQAJAAAJAQIAFAIQALAVAPAKQAOAJATAAQAUAAAOgMQAOgMAAgSQAAgag3gYIgGgDQgtgTgPgRQgPgQAAgbQAAghAZgWQAZgWAnAAIAWACIAZAGIAIgFIAGgBQAFAAAEADQADACAEAIQAHALADAMQAEAMAAAKQAAAGgDAEQgDADgFAAQgKAAgKgNIgCgEQgLgOgMgGQgNgHgPAAQgVAAgMAKQgMAJAAARQAAAPAKALQAKAKAoARIAIADQAhAOAPANQAKAJAGANQAFANAAAPQAAAmgbAVQgaAWgvAAQgXAAgUgFg");
	this.shape_10.setTransform(-97.2,0.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.savorysides, new cjs.Rectangle(-110,-24.2,220,48.5), null);


(lib.mainbutton = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006F46").s().p("EgQFAzRMAAAhmhMAgLAAAMAAABmhg");
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.halfpageturkey_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.halfpageturkey();
	this.instance.parent = this;
	this.instance.setTransform(-124,-135.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.halfpageturkey_1, new cjs.Rectangle(-124,-135.5,248,271), null);


(lib.halfpagetastingeventnearyou = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgSA3QgKgDgGgHQgHgGgEgJIgDgJIgBgLIAAgeIAAgfQAAgBAAAAQAAgBABAAQAAgBAAAAQAAAAABgBIADgBIAFgBIADAAIAFABQABABAAAAQABABAAAAQAAAAABABQAAABAAAAIAAA6QAAAGACAGQACAGADAFQAEAFAGACQAFADAGAAQAHAAAGgDQAFgCAEgFQAEgEACgGQABgHAAgGIAAg5QAAgEADgBIAFgBIAEgBIAEABIAEACQAAAAAAAAQABABAAAAQAAABAAAAQAAABAAABIAAA9IgBALIgDAJQgEAJgHAGQgGAHgJADQgJAEgLAAQgJAAgJgEg");
	this.shape.setTransform(103.8,-0.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgLA5IgMgDIgKgFIgJgHQgIgIgFgLIgEgLIgBgMIABgLIAEgLQAFgLAIgIIAJgHIAKgGIAMgDIALgBIAMABIAMADQALAFAIAIQAIAIAFALQAFALAAALIgCAMIgDALQgFALgIAIQgIAIgLAEIgMADQgGACgGAAQgFAAgGgCgAgOgjQgHADgFAFQgGAGgDAGQgDAIAAAHQAAAIADAIQADAGAGAFQAFAGAHADQAHADAHAAQAHAAAHgDQAHgDAGgGQAFgFADgGQAEgIAAgIQAAgHgEgIQgDgGgFgGQgGgFgHgDQgHgDgHAAQgHAAgHADg");
	this.shape_1.setTransform(90.9,-0.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgEA7IgDgBIgBgBIgBgCIAAgoIgBgHIgEgGIgggxIAAgBQAAgBAAAAQAAgBAAAAQABgBAAAAQAAAAABgBIADgDIAEgCIAEAAIADAAIADADIAWAkIADACIACABIACgBIADgCIAXgkIACgDIAEgBIAEABIAEABIAEADIABADIAAACIgBABIggAyIgDAGIgBADIAAACIAAAoQgCAEgDABIgGAAg");
	this.shape_2.setTransform(79.1,-0.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAcA6IgCgCIgDgBIgBgBIgUgdIgCgFIgFgBIgOAAQgBAAAAABQgBAAAAAAQgBAAAAAAQgBABgBAAQAAAAAAABQAAAAgBABQAAAAAAABQAAAAAAABIAAAcQAAABAAAAQAAAAAAABQgBAAAAAAQAAABAAAAIgFABIgEABIgEAAQgDAAgCgCQgCgBAAgEIABhnQAAAAAAgBQAAAAAAgBQAAAAAAgBQABAAAAAAIADgBIAwAAQAIgBAHADQAIADAGAFQAFAFADAHQADAHAAAJQAAAJgDAHQgFAEgDAEIgIAGQgEACAAADIAAACIAEAHIAHAJIAGAJIADAGQAAAAgBAAQAAABAAAAQAAABAAAAQgBABAAAAIgEACIgDACIgFABgAgXgkQAAABgBAAQAAABgBAAQAAABAAAAQAAABAAABIAAAZQAAABAAABQAAABAAAAQABABAAAAQABABAAAAQADABADAAIAWAAIAIgBQAEgBADgCQADgCACgEQACgDAAgFQgBgKgGgEQgDgCgEgCQgDgBgFAAIgWAAQgDAAgDABg");
	this.shape_3.setTransform(63.8,-0.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAsA5IgCAAIgHAAQgDgBgBgDIgGgPIgCgDIgEgBIglAAIgBABIgCABIgCABIgBABIgGAPIgCACIgDABIgDABIgDAAIgEAAIgDAAIgDgCQAAAAgBAAQAAAAAAgBQAAAAAAAAQgBAAAAgBIAvhqQAAAAABgBQAAAAAAAAQABgBAAAAQAAAAABAAIADgBIAFAAQAAAAABABQABAAAAAAQABABAAAAQAAABAAAAIAtBqIAAABQAAAAAAAAQAAABAAAAQAAAAAAABQgBAAAAAAIgDABgAgBgRIgBACIgBADIgCAFIgDAHIgDAFIgBAFIgBACIABADIACABIAWAAIACgBIABgCIgCgFIgEgJIgDgJIgDgGIgDgBg");
	this.shape_4.setTransform(52,-0.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgmA4IgDgBQgBAAAAAAQgBgBAAAAQAAAAAAgBQAAAAAAAAIAAhpQAAAAAAAAQAAgBAAAAQAAAAABgBQAAAAAAAAIAEgBIBOAAIADABIABAEIABAEIAAADIgBAFIgEACIg6AAIgDACIgCAEIAAAPQAAABABAAQAAABAAAAQAAABAAAAQABAAAAABQAAAAABAAQAAAAABABQAAAAABAAQAAAAABAAIAlAAQAAAAABAAQAAAAABAAQAAABAAAAQAAAAAAAAIACAEIAAAFIAAACQAAAFgEABIgkAAQgBAAAAABQgBAAgBAAQAAAAgBABQAAAAgBAAQAAABAAAAQgBABAAABQAAAAAAABQgBAAAAABIAAARQAAAAABABQAAAAAAABQAAAAAAABQABAAAAAAQAAABABAAQAAAAABABQAAAAABAAQAAAAABAAIA5AAQAEACAAAFIAAADIAAAFIgCADQAAAAAAABQAAAAgBAAQAAAAAAAAQgBAAAAAAg");
	this.shape_5.setTransform(41.6,-0.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAhA7QgCgBgCgDIgug/QAAAAgBgBQAAAAAAAAQgBAAAAAAQgBAAAAAAIgDABQgBAAAAABQAAAAAAAAQgBABAAAAQAAABAAAAIAAA6QgBACgDABIgFABIgHAAQgDgBgCgDIAAhrQAAAAAAgBQAAAAABAAQAAgBAAAAQAAAAABAAIADgCIAEgBIADAAQAFAAADAEIAuA9IADABIACAAIABgCIAAg6QAAAAABgBQAAAAAAgBQAAAAABAAQAAAAABAAIADgCIAEAAIAEAAQAFAAACAEIAABsQAAABgBAAQAAABAAAAQgBABAAAAQgBAAAAABQgBAAAAAAQgBAAAAABQgBAAgBAAQAAAAgBAAg");
	this.shape_6.setTransform(29.5,-0.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgBA5IgGgBQgCgBAAgDIAAhTQAAgBAAgBQAAAAgBgBQAAAAAAgBQAAAAgBgBQgBgBgEAAIgJAAIgJAAIgEAAQgDAAgCgCIgBgGIAAgDIABgEIABgDIAEgBIBNAAQAEAAABACIABAGIAAACIgBAFIgCADQAAAAAAABQgBAAAAAAQAAAAgBAAQAAAAgBAAIgWAAIgFABQAAABgBAAQAAABAAAAQAAABgBABQAAAAAAABIAABSIgBAEIgDABIgEABg");
	this.shape_7.setTransform(14.1,-0.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAhA7QgCgBgCgDIgug/QAAAAgBgBQAAAAAAAAQgBAAAAAAQgBAAAAAAIgDABQgBAAAAABQAAAAAAAAQgBABAAAAQAAABAAAAIAAA6QgBACgDABIgFABIgHAAQgDgBgCgDIAAhrQAAAAAAgBQAAAAABAAQAAgBAAAAQAAAAABAAIADgCIAEgBIADAAQAFAAADAEIAuA9IADABIACAAIABgCIAAg6QAAAAABgBQAAAAAAgBQAAAAABAAQAAAAABAAIADgCIAEAAIAEAAQAFAAACAEIAABsQgBABAAAAQAAABgBAAQAAABAAAAQgBAAAAABQgBAAAAAAQgBAAAAABQgBAAgBAAQAAAAgBAAg");
	this.shape_8.setTransform(3.4,-0.4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AglA4IgEgBQgBAAAAAAQgBgBAAAAQAAAAAAgBQgBAAAAAAIAAhpQAAAAABAAQAAgBAAAAQAAAAABgBQAAAAAAAAIAEgBIBPAAIACABIABAEIAAAEIAAADIgBAFIgCACIg7AAIgDACIgBAEIAAAPQAAABAAAAQAAABAAAAQAAABAAAAQABAAAAABQAAAAABAAQAAAAABABQAAAAABAAQAAAAABAAIAlAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAABAAIABAEIAAAFIAAACQAAAFgEABIglAAQAAAAgBABQAAAAgBAAQAAAAAAABQgBAAAAAAQgBABAAAAQgBABAAABQAAAAAAABQAAAAAAABIAAARQAAAAAAABQAAAAAAABQAAAAAAABQABAAAAAAQAAABABAAQAAAAABABQAAAAABAAQAAAAABAAIA6AAQADACAAAFIAAADIgBAFIAAADQgBAAAAABQAAAAgBAAQAAAAAAAAQgBAAAAAAg");
	this.shape_9.setTransform(-7.5,-0.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgBA4IgEgIIgFgNIgIgQIgIgSIgIgRIgGgPIgEgMIgCgFIABgDIAEgDIAEgCIAEAAQABAAAAAAQABAAAAAAQABABAAAAQABAAABAAIACAFIAYA4IABABIABABQAAAAABAAQAAAAABgBQAAAAAAAAQABgBAAgBIAXg4IADgEQABAAAAgBQABAAAAAAQABAAAAAAQABgBABAAIADABIAFABIADADQABAAAAAAQAAABABAAQAAABAAAAQAAAAAAABIgCAFIgFALIgGAQIgIARIgIATIgIAQIgFAOIgDAGIgBACIgBABQAAAAAAgBQgBAAAAAAQAAAAAAgBQAAAAAAAAg");
	this.shape_10.setTransform(-18.5,-0.4);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgmA4IgDgBQgBAAAAAAQgBgBAAAAQAAAAAAgBQgBAAAAAAIAAhpQAAAAABAAQAAgBAAAAQAAAAABgBQAAAAABAAIADgBIBPAAIACABIABAEIAAAEIAAADIgBAFIgCACIg7AAIgDACIgBAEIAAAPQAAABAAAAQAAABAAAAQAAABAAAAQABAAAAABQAAAAABAAQAAAAABABQAAAAABAAQAAAAABAAIAlAAQAAAAABAAQAAAAABAAQAAABAAAAQAAAAABAAIABAEIAAAFIAAACQAAAFgEABIglAAQAAAAgBABQAAAAgBAAQAAAAgBABQAAAAgBAAQAAABAAAAQgBABAAABQAAAAAAABQAAAAAAABIAAARQAAAAAAABQAAAAAAABQAAAAAAABQABAAAAAAQAAABABAAQAAAAABABQAAAAABAAQAAAAABAAIA6AAQADACAAAFIAAADIgBAFIgBADQAAAAAAABQAAAAgBAAQAAAAAAAAQgBAAAAAAg");
	this.shape_11.setTransform(-28.4,-0.4);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgIA6QgGgBgGgDQgFgCgFgDIgJgHIgIgIIgFgKQgFgMAAgMQAAgFABgGQABgGADgGQAFgKAIgIIAJgHIAKgGIAMgDIALgBIANACQAGABAGACQAMAGAJAKIAAACIgBADIgEAFIgEADIgEABQgCAAgDgCIgGgFIgJgGQgFgCgIAAQgHAAgHADQgHADgGAFQgFAGgDAHQgDAHAAAHQAAAIADAHQADAHAFAFQAGAGAHADQAHADAHAAIAIgBIAIgBIAGgEQAEgCACgEIAAgCQAAgBAAAAQAAgBAAAAQAAgBgBAAQAAAAAAgBIgEgBIgUAAQgBAAAAAAQgBAAAAAAQAAAAgBAAQAAgBAAAAIgCgDIAAgFIAAgDIABgFIADgCIAwAAIABABIACABQACAFAAAGIAAAEIgBAFQgDAJgGAGQgGAHgGAFQgIAEgIACQgIADgJAAIgLgBg");
	this.shape_12.setTransform(-46.2,-0.4);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AAhA7QgCgBgCgDIgug/QAAAAgBgBQAAAAAAAAQgBAAAAAAQgBAAAAAAIgDABQgBAAAAABQAAAAAAAAQgBABAAAAQAAABAAAAIAAA6QgBACgDABIgFABIgHAAQgDgBgCgDIAAhrQAAAAAAgBQAAAAABAAQAAgBAAAAQAAAAABAAIADgCIAEgBIADAAQAFAAADAEIAuA9IADABIACAAIABgCIAAg6QAAAAABgBQAAAAAAgBQAAAAABAAQAAAAABAAIADgCIAEAAIAEAAQAFAAACAEIAABsQAAABgBAAQAAABgBAAQAAABAAAAQgBAAAAABQgBAAAAAAQgBAAAAABQgBAAgBAAQAAAAgBAAg");
	this.shape_13.setTransform(-58.6,-0.4);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgDA7QgEAAgCgEIAAhtIACgCIAFgBIACAAIAEAAQAFAAABADIAABsIgCADIgEABIgEABg");
	this.shape_14.setTransform(-67.1,-0.4);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgBA5IgGgBQgCgBAAgDIAAhTQAAgBAAgBQAAAAgBgBQAAAAAAgBQAAAAgBgBQgBgBgEAAIgJAAIgJAAIgEAAQgDAAgCgCIgBgGIAAgDIABgEIABgDIAEgBIBNAAQAEAAABACIABAGIAAACIgBAFIgCADQAAAAAAABQgBAAAAAAQAAAAgBAAQAAAAgBAAIgWAAIgFABQAAABgBAAQAAABAAAAQgBABAAABQAAAAAAABIAABSIgBAEIgDABIgEABg");
	this.shape_15.setTransform(-74.3,-0.3);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgZA2QgMgEgJgJIgBgCIAAgCIABgEIADgEIAFgDIADgBQADAAADACIAHAFIAKAFQAFACAHAAIAIgBQAFAAAEgCQAEgCADgDQADgEgBgFQAAgEgCgDQgDgDgFgBIgMgDIgNgBIgNgDIgMgEQgFgEgDgGQgDgFAAgJQAAgJAEgGQAFgHAHgEQAGgEAIgCQAJgCAGAAIALABIAMACIALAFQAFADAEADIAAACIABACIgBAEIgEAEIgFACIgDABIgEAAQgGgFgGgDQgIgDgHAAIgHAAIgIADIgGAFQgDADAAAEQAAAGAGADQAFADAJABIAQACQAKACAHADQAJADAFAFQAGAGAAAMQAAAKgFAHQgFAHgHAFQgHAEgJADQgJACgHAAQgMAAgNgFg");
	this.shape_16.setTransform(-84.4,-0.4);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AAsA5IgCAAIgHAAQgCgBgCgDIgGgPIgCgDIgEgBIglAAIgBABIgCABIgCABIgBABIgGAPIgCACIgDABIgDABIgEAAIgDAAIgDAAIgDgCQAAAAgBAAQAAAAAAgBQAAAAAAAAQgBAAAAgBIAvhqQAAAAABgBQAAAAAAAAQABgBAAAAQAAAAABAAIADgBIAFAAQAAAAABABQABAAAAAAQABABAAAAQAAABAAAAIAtBqIAAABQAAAAAAAAQAAABAAAAQAAAAAAABQgBAAAAAAIgEABgAAAgRIgBACIgCADIgCAFIgDAHIgCAFIgCAFIgCACIACADIACABIAVAAIADgBIABgCIgCgFIgEgJIgDgJIgDgGIgDgBg");
	this.shape_17.setTransform(-95.3,-0.4);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgBA5IgGgBQgCgBAAgDIAAhTQAAgBAAgBQAAAAgBgBQAAAAAAgBQAAAAgBgBQgBgBgEAAIgJAAIgJAAIgEAAQgDAAgCgCIgBgGIAAgDIABgEIABgDIAEgBIBNAAQAEAAABACIABAGIAAACIgBAFIgCADQAAAAAAABQgBAAAAAAQAAAAgBAAQAAAAgBAAIgWAAIgFABQAAABgBAAQAAABAAAAQAAABgBABQAAAAAAABIAABSIgBAEIgDABIgEABg");
	this.shape_18.setTransform(-105.5,-0.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.halfpagetastingeventnearyou, new cjs.Rectangle(-112.2,-10.2,224.5,20.6), null);


(lib.halfpagetable_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.halfpagetable();
	this.instance.parent = this;
	this.instance.setTransform(-150,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.halfpagetable_1, new cjs.Rectangle(-150,-300,300,600), null);


(lib.halfpagepotatoes_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.halfpagepotatoes();
	this.instance.parent = this;
	this.instance.setTransform(-44,-114);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.halfpagepotatoes_1, new cjs.Rectangle(-44,-114,88,228), null);


(lib.halfpageorange_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.halfpageorange();
	this.instance.parent = this;
	this.instance.setTransform(-50,-68.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.halfpageorange_1, new cjs.Rectangle(-50,-68.5,100,137), null);


(lib.halfpagegreens_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.halfpagegreens();
	this.instance.parent = this;
	this.instance.setTransform(-70.5,-91.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.halfpagegreens_1, new cjs.Rectangle(-70.5,-91.5,141,183), null);


(lib.halfpagedeliciousdesserts = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgNBhIgUgDIgGADIgGABIgDAAIgEgDQgGgFgGgPQgFgPAAgOQAAgGADgEQADgEAFAAQAJAAAIAPIAIALQAFAIAKAEQAKAEAKAAQAMAAAHgGQAHgGAAgLQAAgPgegQIgLgFQgdgOgKgMQgLgMAAgSQAAgYARgPQARgQAcAAIAMABIANACIAJgDIAGgBQAJAAAJAPQAIAOAAARQAAAGgDAEQgCAEgGAAQgEAAgEgEQgEgDgGgKQgHgLgIgFQgHgEgLAAQgKAAgGAGQgHAGAAAKQAAAIAHAHQAHAHAWALIACABQA0AZAAAeQAAAagTASQgVARgeAAg");
	this.shape.setTransform(63.9,30);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgJBxQgJgEgIgFQgGgHgDgKQgCgKAAgcIAAhkIgRAAIgGgBIgBgFIAAgFQgBgGAUgQIAHgHIAIgHQATgQAIAAIAEACQABAAAAAAQABABAAAAQAAABAAAAQABABAAAAIAAAkIApAAQAFAAACABQACACgBAFIAAAFQAAAFgCACQgBACgFAAIgmAAIgDACIgBAEIAABdQAAAXAEAHQAEAFALABQAGAAAJgEIANgCQAEAAADACQADACAAAEQgBAKgQAKQgPAJgVAAQgKAAgJgCg");
	this.shape_1.setTransform(49.5,28.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("Ag4BcQgJgDAAgHQAAgHAJgDIAFgDQAFgCABgGQADgGAAgPIAAgMIAAgQIAAgKQAAgigCgKQgCgLgDgCIgJgEQgLgDAAgHQgBgEAEgDQADgDAIgEIAagHIAQgEQAKAAACAZIABAEIABABQAKgPAKgIQAKgIALAAQANAAAHAIQAIAIAAANQAAANgFAIQgHAHgKAAIgJgCIgIgFIgFgIQgCgEgBgBQgOAAgEASQgFASAAA4QAAARACAHQACAJAEACIAIADQAMADAAAIQAAAGgLADQgLAEgZAAQgcAAgJgEg");
	this.shape_2.setTransform(36,29.9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("Ag8BGQgbgbAAgoQAAgrAcgcQAbgcAqAAQAjAAAWAUQAVAVAAAjQAAALgDAEQgEADgOAAIhHAAQgHAAgCgCQgEgDAAgFQAAgFAEgDQACgDAHAAIAmAAIAJgBQADgBAAgFQAAgSgMgMQgMgNgRAAQgWAAgLAUQgLATAAAcQAAAcAPAVQAPAWAXAAQAOAAAKgDQAJgDAJgHIAHgFQAJgHAFAAQAFgBACADQADADAAAEQAAAEgFAHQgEAGgJAGQgQAOgPAGQgPAGgSgBQgmAAgbgbg");
	this.shape_3.setTransform(18.6,30.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgNBhIgUgDIgGADIgGABIgDAAIgEgDQgGgFgGgPQgFgPAAgOQAAgGADgEQADgEAFAAQAJAAAIAPIAIALQAFAIAKAEQAKAEAKAAQAMAAAHgGQAHgGAAgLQAAgPgegQIgLgFQgdgOgKgMQgLgMAAgSQAAgYARgPQARgQAcAAIAMABIANACIAJgDIAGgBQAJAAAJAPQAIAOAAARQAAAGgDAEQgCAEgGAAQgEAAgEgEQgEgDgGgKQgHgLgIgFQgHgEgLAAQgKAAgGAGQgHAGAAAKQAAAIAHAHQAHAHAWALIACABQA0AZAAAeQAAAagTASQgVARgeAAg");
	this.shape_4.setTransform(0.5,30);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgNBhIgUgDIgGADIgGABIgDAAIgEgDQgGgFgGgPQgFgPAAgOQAAgGADgEQADgEAFAAQAJAAAIAPIAIALQAFAIAKAEQAKAEAKAAQAMAAAHgGQAHgGAAgLQAAgPgegQIgLgFQgdgOgKgMQgLgMAAgSQAAgYARgPQARgQAcAAIAMABIANACIAJgDIAGgBQAJAAAJAPQAIAOAAARQAAAGgDAEQgCAEgGAAQgEAAgEgEQgEgDgGgKQgHgLgIgFQgHgEgLAAQgKAAgGAGQgHAGAAAKQAAAIAHAHQAHAHAWALIACABQA0AZAAAeQAAAagTASQgVARgeAAg");
	this.shape_5.setTransform(-15.7,30);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("Ag9BGQgagbAAgoQAAgrAcgcQAbgcApAAQAlAAAVAUQAVAVAAAjQAAALgDAEQgEADgOAAIhHAAQgGAAgDgCQgEgDAAgFQAAgFAEgDQADgDAGAAIAmAAIAJgBQADgBAAgFQAAgSgMgMQgMgNgRAAQgWAAgLAUQgKATAAAcQAAAcAOAVQAPAWAXAAQAOAAAJgDQAKgDAJgHIAGgFQAKgHAGAAQADgBADADQADADAAAEQAAAEgFAHQgEAGgJAGQgQAOgPAGQgPAGgSgBQgnAAgbgbg");
	this.shape_6.setTransform(-33.5,30.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgoCHIgXgBIgQABIgQAAQgWAAgIgDQgHgDAAgIQAAgHAKgEQAKgEACgDQADgDABgdIAChIIgChFQgCgcgCgEQgCgCgKgEQgKgFAAgHQAAgIAIgDQAIgDAXAAIAQABIATAAIAYgBIAWAAQBFAAAmAkQAmAkAABBQAABBgnAiQgnAhhKAAgAgohqQgJADgCAGQgDAHgBAWIgBA5IABBHQACAdACAGQACAFAMAFQANAEARAAQAqAAAVgaQAWgaAAg1QAAg2gZgdQgYgeguAAQgPAAgIADg");
	this.shape_7.setTransform(-57.9,25.9);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgNBhIgUgDIgGADIgGABIgDAAIgEgDQgGgFgGgPQgFgPAAgOQAAgGADgEQADgEAFAAQAJAAAIAPIAIALQAFAIAKAEQAKAEAKAAQAMAAAHgGQAHgGAAgLQAAgPgegQIgLgFQgdgOgKgMQgLgMAAgSQAAgYARgPQARgQAcAAIAMABIANACIAJgDIAGgBQAJAAAJAPQAIAOAAARQAAAGgDAEQgCAEgGAAQgEAAgEgEQgEgDgGgKQgHgLgIgFQgHgEgLAAQgKAAgGAGQgHAGAAAKQAAAIAHAHQAHAHAWALIACABQA0AZAAAeQAAAagTASQgVARgeAAg");
	this.shape_8.setTransform(71.2,-21.5);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AAoBfQgCgDAAgGIAAgNIAAgBIgBAAQgDAAgEAEIgCADQgJAJgLAFQgLAEgNAAQgPAAgMgFQgNgFgHgKQgKgLgDgPQgEgPAAgnIABgNIAAgOIAAgDQAAgQgCgEQgDgEgGgDIgIgCQgLgDABgHQAAgEADgDQAEgEANgEIAagHIAUgDQAFAAACAEQACAEAAAIIAAAIIgCBFQAAAmAIAOQAHAPAUAAQAUAAAJgTQAKgTgBgtIAAgOQAAgPgBgEQgCgFgHgCIgIgCQgKgDAAgHQAAgEAEgDQADgDANgFIAagHIATgDQAGAAACAEQADADgBAJIAAALIgCBMIAAAfIABANQACAIAJADIAAAAIAEABQALAEAAAGQgBAEgDAEQgDADgJADIgaAJQgNADgHAAQgFAAgDgDg");
	this.shape_9.setTransform(52,-21.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AhDBGQgbgcAAgpQAAgpAcgdQAcgcApAAQApAAAaAbQAZAaAAApQAAAqgcAeQgbAcgoAAQgoAAgbgbgAgjg3QgLAPAAAZQAAAkAPAZQARAZAVAAQATAAALgPQALgPAAgaQAAgkgQgYQgQgZgVAAQgTAAgLAPg");
	this.shape_10.setTransform(30.5,-21.4);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AggCFQgKgDAAgIQAAgGAJgEIAFgCQAFgCACgGQACgHAAgOIAAgNIAAgPIAAgTQAAgegCgIQgBgIgEgCIgJgEQgLgDAAgHQAAgEAEgDQADgDAIgEIAcgJIATgDQAFAAADADQACAEAAAJIAAALIgBAIIgBAvIAAABIgBAuQAAASACAHQABAIAFACIAHADQAJADAAAHQAAAIgJADQgJADgZAAQgbAAgJgEgAgWheQgIgGAAgKQAAgLAJgHQAIgIANAAQALAAAIAHQAIAHAAAKQAAAKgIAIQgJAHgMAAQgMAAgIgHg");
	this.shape_11.setTransform(14.6,-25.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("Ag7BGQgagbAAgoQAAgqAcgdQAcgdApAAQAfAAAVAQQAWARAAAVQAAAJgGAGQgGAFgJAAQgKAAgGgFQgFgEgHgPQgGgOgHgFQgHgFgMgBQgUABgMAQQgNAQAAAdQAAAgASAVQARAVAaAAQAJAAAJgDQAIgCAHgFIAHgFQAKgIAGAAQAEAAACACQACACAAAFQAAAEgEAHQgEAGgGAFQgOAOgQAFQgQAHgTgBQgmAAgbgbg");
	this.shape_12.setTransform(-0.1,-21.4);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AggCFQgKgDAAgIQAAgGAJgEIAFgCQAFgCACgGQACgHAAgOIAAgNIAAgPIAAgTQAAgegCgIQgBgIgEgCIgJgEQgLgDAAgHQAAgEAEgDQADgDAIgEIAcgJIATgDQAFAAADADQACAEAAAJIAAALIgBAIIgBAvIAAABIgBAuQAAASACAHQABAIAFACIAHADQAJADAAAHQAAAIgJADQgJADgZAAQgbAAgJgEgAgWheQgIgGAAgKQAAgLAJgHQAIgIANAAQALAAAIAHQAIAHAAAKQAAAKgIAIQgJAHgMAAQgMAAgIgHg");
	this.shape_13.setTransform(-15.2,-25.7);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgfCGQgJgDAAgIQAAgGAHgDIAKgGQADgDACgLIABglIAAgdIAAgiIAAgPQAAgvgCgOQgBgNgFgDIgLgEQgMgDAAgGQAAgFAEgDQAEgEANgEIAZgHIASgDQAGABADADQABAEAAAIIAAAOQgCBDAABDIABBAQABAOADADIALAFQAJAEAAAHQAAAHgJADQgKAEgYAAQgcAAgJgEg");
	this.shape_14.setTransform(-25.9,-25.7);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("Ag8BGQgbgbAAgoQAAgrAbgcQAcgdAqAAQAjABAWAUQAVAVAAAjQAAAMgEADQgDADgOABIhHAAQgHAAgDgDQgDgEAAgEQAAgFADgDQADgDAHAAIAmAAIAKgBQACgBAAgFQAAgSgMgMQgMgNgRAAQgWAAgLAUQgLATAAAcQAAAcAPAVQAPAWAXAAQAOAAAKgDQAJgEAJgGIAHgFQAJgIAFABQAEAAADACQADADAAAEQAAAEgFAHQgEAHgJAFQgQAOgPAGQgPAFgSAAQgmAAgbgbg");
	this.shape_15.setTransform(-40.7,-21.4);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgoCHIgXgBIgQABIgQAAQgWAAgIgDQgHgDAAgIQAAgHAKgEQAKgEACgDQADgDABgdIAChIIgChFQgCgcgCgEQgCgCgKgEQgKgFAAgHQAAgIAIgDQAIgDAXAAIAQABIATAAIAYgBIAWAAQBFAAAmAkQAmAkAABBQAABBgnAiQgnAhhKAAgAgohqQgJADgCAGQgDAHgBAWIgBA5IABBHQACAdACAGQACAFAMAFQANAEARAAQAqAAAVgaQAWgaAAg1QAAg2gZgdQgYgeguAAQgPAAgIADg");
	this.shape_16.setTransform(-65.2,-25.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.halfpagedeliciousdesserts, new cjs.Rectangle(-81.4,-50,162.9,100), null);


(lib.halfpagecranberries_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.halfpagecranberries();
	this.instance.parent = this;
	this.instance.setTransform(-57.5,-36);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.halfpagecranberries_1, new cjs.Rectangle(-57.5,-36,115,72), null);


(lib.foryourfeast = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgJBxQgJgDgIgGQgGgHgDgKQgCgKAAgcIAAhkIgRAAIgGgBIgCgFIAAgFQAAgFAUgRIAHgHIAIgHQATgRAIAAIAFADQAAAAAAAAQABABAAAAQAAABAAAAQABABAAAAIAAAkIApAAQAFAAACABQABADAAAEIAAAFQAAAFgCACQgBACgFAAIgmAAIgDACIgBAEIAABdQAAAXAEAHQAEAFALABQAGgBAJgDIANgCQAEgBADADQACADAAADQAAAKgQAKQgPAJgVAAQgKAAgJgCg");
	this.shape.setTransform(113.5,2.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgNBhIgUgDIgGADIgGABIgDAAIgEgDQgGgFgGgPQgFgPAAgOQAAgGADgEQADgEAFAAQAJAAAIAPIAIALQAFAIAKAEQAKAEAKAAQAMAAAHgGQAHgGAAgLQAAgPgegQIgLgFQgdgOgKgMQgLgMAAgSQAAgYARgPQARgQAcAAIAMABIANACIAJgDIAGgBQAJAAAJAPQAIAOAAARQAAAGgDAEQgCAEgGAAQgEAAgEgEQgEgDgGgKQgHgLgIgFQgHgEgLAAQgKAAgGAGQgHAGAAAKQAAAIAHAHQAHAHAWALIACABQA0AZAAAeQAAAagTASQgVARgeAAg");
	this.shape_1.setTransform(98.5,4.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAhBYIgJgKIgJAEQgXAQgWAAQgcAAgQgQQgRgQgBgaQAAgeAWgPQAWgRAnAAQAJAAAFADQAEACAAAHQAAALgMAAQgTAAgLAJQgLAJAAAPQAAAPAJAJQALAJAQAAQARAAAIgIQAIgIAAgTIAAhHQAAgQgIgJQgGgJgNAAQgJAAgIAEQgIAEgHAIIgEAFQgLAPgNAAQgHAAgFgFQgFgFAAgIQAAgSAXgMQAVgMAiAAQAUAAAPAGQAPAFAIALQAGAHACALQACAMABAbIAAA7QAAALACAFQABAFAEABIAFACQANADAAAGQAAAJgNAIQgNAHgQAAQgJAAgJgKg");
	this.shape_2.setTransform(80.8,4.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("Ag9BGQgagbAAgoQAAgrAbgcQAcgdApAAQAlABAVAUQAVAVAAAjQAAAMgEADQgDADgOAAIhHAAQgGAAgEgCQgDgEAAgEQAAgFADgDQAEgDAGAAIAmAAIAKgBQACgBAAgFQAAgSgMgMQgMgNgRAAQgWAAgLAUQgLATABAcQAAAcAOAVQAPAWAXAAQAOAAAJgDQAKgEAJgGIAHgFQAJgIAGABQAEAAACACQADADAAAEQAAAEgFAHQgFAHgHAFQgRAOgPAGQgPAFgSAAQgnAAgbgbg");
	this.shape_3.setTransform(60.7,4.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AheCGQgLgDAAgJQAAgHAKgEQAKgEACgDQADgDABgdIAChIIgChFQgCgcgCgEQgCgCgKgEQgKgFAAgHQAAgIAJgCQAJgDAgAAIByAAIASgCIAKgCIAFABIADADQAEAHADANQAEANAAAJQAAAIgDAFQgEAEgFAAQgHAAgHgNIgGgIQgEgGgIgDQgJgDgMAAIgaAAQgRAAgJACQgKACgDAEQgDAEgCAMIgBAkIAAAPQAAAJACACQABACAFAAIAeAAQAPAAAGgEQAGgEACgMIAAgDQADgUAKAAQAIAAADALQADAKAAAkQAAAigDALQgDAKgIAAQgKAAgDgUIAAgDQgCgMgGgEQgGgFgPAAIgdAAQgFAAgCAEQgCADAAAMIAAAOIABA1QACALADACIAIAEQAMAFAAAHQAAAJgLADQgKADgdAAQgeAAgKgDg");
	this.shape_4.setTransform(39.8,0);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("Ag4BdQgJgEAAgHQAAgHAJgDIAFgDQAFgCACgGQABgHAAgOIAAgMIAAgPIAAgLQABgigCgKQgBgLgFgCIgJgEQgKgDgBgGQABgFADgDQADgDAJgEIAZgIIAQgDQAKAAADAaIAAADIABABQAJgPALgIQALgIAKAAQANAAAIAIQAHAIABANQAAANgHAHQgFAIgLAAIgKgCIgIgGIgDgHQgCgEgDgBQgNAAgFASQgEASAAA4QAAARABAHQADAJAFACIAHADQALADAAAIQABAGgLAEQgKADgZAAQgdAAgJgDg");
	this.shape_5.setTransform(11.2,4.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAoBfQgCgDAAgGIAAgNIAAgBIgBAAQgCAAgFAEIgCADQgJAJgMAFQgKAEgNAAQgPAAgMgFQgMgFgJgKQgIgLgEgPQgEgPAAgnIABgNIAAgOIAAgDQgBgQgCgEQgCgEgHgDIgHgCQgLgDAAgHQAAgEAEgDQAEgEANgEIAZgHIAVgDQAEAAACAEQADAEAAAIIAAAIIgDBFQABAmAHAOQAJAPASAAQAVAAAKgTQAIgTABgtIAAgOQAAgPgCgEQgDgFgGgCIgHgCQgLgDAAgHQAAgEAEgDQAEgDANgFIAZgHIATgDQAGAAACAEQACADAAAJIAAALIgCBMIAAAfIABANQABAIAKADIAAAAIAEABQALAEAAAGQAAAEgEAEQgDADgJADIgaAJQgNADgGAAQgGAAgDgDg");
	this.shape_6.setTransform(-7.6,4.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AhDBGQgbgbAAgqQAAgpAcgcQAcgdApAAQAoAAAaAbQAaAaAAApQAAArgcAdQgbAcgoAAQgoABgbgcgAgjg3QgLAPAAAaQAAAkAPAYQAQAZAWAAQASAAAMgPQALgQAAgZQAAgkgQgYQgPgZgWAAQgSAAgMAPg");
	this.shape_7.setTransform(-29.1,4.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgmCEQgLgDAAgJQAAgHAMgFIAIgEQAGgFABhMIAAgRIgWgkIgkg4QgLgPgGgEIgJgEQgNgEAAgIQAAgHAJgDQAJgDAlAAQAkAAAIADQAJADAAAHQAAAIgOAFIgBAAIgGAEIgCAGQAAAEAIANIAlA6IAggwQALgRAAgGQAAgFgDgDQgDgDgJgDQgHgDgCgDQgCgCAAgFQAAgHAHgDQAIgDAfAAQAeAAAIADQAIADAAAHQAAAIgLAEIgOAHQgIAHgSAbQgSAbgbAuIAAAhQABA+AFAEIAJAEQALAFAAAHQAAAJgKADQgKADgeAAQgcAAgKgDg");
	this.shape_8.setTransform(-51.7,0.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("Ag4BdQgJgEAAgHQAAgHAJgDIAFgDQAFgCABgGQACgHAAgOIAAgMIAAgPIAAgLQAAgigBgKQgBgLgEgCIgJgEQgMgDAAgGQAAgFAEgDQADgDAIgEIAagIIARgDQAIAAADAaIABADIABABQAKgPAKgIQALgIAKAAQANAAAHAIQAJAIgBANQABANgHAHQgFAIgLAAIgJgCIgIgGIgFgHQgCgEgBgBQgOAAgEASQgFASAAA4QAAARABAHQADAJAEACIAIADQALADAAAIQAAAGgKAEQgLADgZAAQgcAAgJgDg");
	this.shape_9.setTransform(-80.7,4.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AhDBGQgbgbAAgqQAAgpAdgcQAbgdApAAQAoAAAbAbQAZAaAAApQAAArgbAdQgcAcgoAAQgoABgbgcgAgjg3QgLAPAAAaQAAAkAQAYQAQAZAVAAQATAAALgPQALgQAAgZQAAgkgPgYQgQgZgWAAQgSAAgMAPg");
	this.shape_10.setTransform(-98.8,4.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("Ag0CGQgJgDAAgHQAAgGAJgDIAEgCQAFgDACgGQACgGAAgQIAAgSIAAhaIgWAAQgEAAgBgBQgCgCAAgGIAAgEQAAgFACgCQACgCAEAAIAUAAIgCgPIgBgNQAAgcARgQQARgQAeAAQAWAAANAKQANAJAAAPQAAAJgFAEQgEAFgKAAQgGAAgEgDQgFgCgDgFIgEgHQgHgOgKAAQgHAAgEAFQgEAFAAAHIAEAVQADAQABANIAbAAQAFAAABACQACACAAAFIAAAEQAAAFgCACQgCACgEAAIgbAAIAABgQAAAYACAHQABAIAEABIAHADQALAEAAAHQAAAIgJACQgJADgbAAQgbAAgJgDg");
	this.shape_11.setTransform(-113,0);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.foryourfeast, new cjs.Rectangle(-122,-24.2,244.1,48.5), null);


(lib.Path = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AqAXuQkoh9jkjkQjkjkh9koQiCkyAAlPQAAlOCCkyQB9koDkjkQDkjkEoh9QEyiCFOAAQFPAAEyCCQEoB9DkDkQDkDkB9EoQCCEygBFOQABFPiCEyQh9EojkDkQjkDkkoB9QkyCClPAAQlOAAkyiCg");
	this.shape.setTransform(164.8,164.8);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Path, new cjs.Rectangle(0,0,329.5,329.6), null);


(lib.findanevent = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgGAwIAAhTIgeAAIAAgMIBJAAIAAAMIgeAAIAABTg");
	this.shape.setTransform(46.9,0.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAXAwIgxhNIAABNIgOAAIAAhfIASAAIAxBMIAAhMIANAAIAABfg");
	this.shape_1.setTransform(37.9,0.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgfAwIAAhfIA9AAIAAAMIgvAAIAAAdIAsAAIAAAKIgsAAIAAAgIAxAAIAAAMg");
	this.shape_2.setTransform(28.9,0.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgFAwIgmhfIAPAAIAcBNIABAAIAchNIAPAAIgmBfg");
	this.shape_3.setTransform(20.3,0.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgfAwIAAhfIA9AAIAAAMIgvAAIAAAdIAsAAIAAAKIgsAAIAAAgIAxAAIAAAMg");
	this.shape_4.setTransform(12.2,0.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAXAwIgxhNIAABNIgOAAIAAhfIASAAIAxBMIAAhMIANAAIAABfg");
	this.shape_5.setTransform(-0.7,0.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAgAwIgJgYIgtAAIgJAYIgPAAIAphfIAMAAIAoBfgAARAMIgRgrIgRArIAiAAg");
	this.shape_6.setTransform(-10.6,0.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgpAwIAAhfIAhAAQAIAAAJADQAJADAIAFQAHAGAFAJIADAKIABALIgBALIgDAKIgGAIIgGAHQgIAGgJADQgLADgGAAgAgcAkIARAAQAJAAAGgCQAHgDAGgEQAFgFADgHIACgHIABgIIgBgHIgCgIQgDgGgFgFQgGgEgHgDQgGgCgJAAIgRAAg");
	this.shape_7.setTransform(-23.7,0.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAYAwIgyhNIAABNIgOAAIAAhfIASAAIAxBMIAAhMIANAAIAABfg");
	this.shape_8.setTransform(-34.2,0.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgGAwIAAhfIANAAIAABfg");
	this.shape_9.setTransform(-41.3,0.1);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgdAwIAAhfIA7AAIAAAMIgtAAIAAAeIAqAAIAAAKIgqAAIAAArg");
	this.shape_10.setTransform(-46.6,0.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.findanevent, new cjs.Rectangle(-54.5,-10.3,109,20.6), null);


(lib.datefive = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgWA3QgKgEgIgHIgBgDIABgEIADgEIAEgDIAEgBIAFACIAFADIAHAEQAFABAFAAQAEAAAFgCQAEgBAEgDQACgDADgFQACgEAAgFQgBgFgBgEIgFgGIgHgEQgEgCgEAAQgFAAgFACIgFADIgGADIgFABIgGAAQgDgBgBgDIAFgyQAAgCACgDIAGgCIAbAAIAbABQAEAAABADIACAGQAAADgCADQgBACgDABIgkAAQgGAAgCAEQgCADABAFQAAABAAAAQAAABAAAAQAAABAAAAQABAAAAABQAAAAABAAQAAABABAAQAAAAABAAQAAAAAAAAIAHgBIAGAAQAIAAAIADQAHADAFAFQAFAFADAGQACAHAAAJQAAAJgDAIQgEAIgFAGQgHAFgIADQgIADgJAAQgLAAgJgDg");
	this.shape.setTransform(34.6,-0.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgOAJIgCgBIgCgCIgBgEIAAgCIAAgCIABgDIACgCIACgBIAcAAIADABIACACIAAADIABACIgBAEQgBADgCACIgDAAg");
	this.shape_1.setTransform(22.4,-0.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAJA6QAAAAAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBIAAgSQAAgBgBAAQAAgBAAAAQAAgBAAAAQgBgBAAAAQAAgBgBAAQAAgBgBAAQAAAAgBAAQgBgBgBAAIgkAAIgFgBQAAAAAAAAQgBgBAAAAQAAgBAAAAQgBgBAAAAIABgFIAihLIADgEIAFgBIACABIAEACIADACIAAADIgBAFIgFAKIgEAMIgGANIgEALIgDAEIAAACIAAACIABACQAAABABAAQAAAAAAABQABAAAAAAQABAAABAAIADAAIAGgBIAEgBQABAAAAgBQABAAAAgBQAAAAAAgBQABgBAAAAIAAgRIABgEIADgBIAEgBIADAAIACAAIADABIADACIAAADIAAARIABADQAAABABAAQAAABABAAQAAAAABAAQAAAAABAAIAIAAQAEADAAADIABAGQgBAFgBABIgEABIgFAAQgDAAgCADIgBACIgBACIABAMQAAAEgBACQAAABAAABQgBAAAAAAQgBABAAAAQgBAAgBAAIgIACg");
	this.shape_2.setTransform(10.3,-0.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgGAHQgEgDAAgEQAAgEAEgDQADgDADAAQAFAAADADQADADAAAEQAAAEgDADQgDAEgFAAQgDAAgDgEg");
	this.shape_3.setTransform(-1.7,4.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgBA4IgEgIIgFgNIgIgQIgIgSIgIgRIgGgPIgEgMIgCgFIABgDIAEgDIAEgCIAEAAQABAAAAAAQABAAAAAAQABABAAAAQABAAABAAIACAFIAYA4IABABIABABQAAAAABAAQAAAAABgBQAAAAAAAAQABgBAAgBIAXg4IADgEQABAAAAgBQABAAAAAAQABAAAAAAQABgBABAAIADABIAFABIADADQABAAAAAAQAAABABAAQAAABAAAAQAAAAAAABIgCAFIgFALIgGAQIgIARIgIATIgIAQIgFAOIgDAGIgBACIgBABQAAAAAAgBQgBAAAAAAQAAAAAAgBQAAAAAAAAg");
	this.shape_4.setTransform(-9,-0.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgLA5IgMgDIgKgFIgJgHQgIgIgFgLIgEgLIgBgMIABgLIAEgLQAFgLAIgIIAJgHIAKgGIAMgDIALgBIAMABIAMADQALAFAIAIQAIAIAFALQAFALAAALIgCAMIgDALQgFALgIAIQgIAIgLAEIgMADQgGACgGAAQgFAAgGgCgAgOgjQgHADgFAFQgGAGgDAGQgDAIAAAHQAAAIADAIQADAGAGAFQAFAGAHADQAHADAHAAQAHAAAHgDQAHgDAGgGQAFgFADgGQAEgIAAgIQAAgHgEgIQgDgGgFgGQgGgFgHgDQgHgDgHAAQgHAAgHADg");
	this.shape_5.setTransform(-20.7,-0.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAhA7QgCgBgCgDIgug/QAAAAgBgBQAAAAAAAAQgBAAAAAAQgBAAAAAAIgDABQgBAAAAABQAAAAAAAAQgBABAAAAQAAABAAAAIAAA6QgBACgDABIgFABIgHAAQgDgBgCgDIAAhrQAAAAAAgBQAAAAABAAQAAgBAAAAQAAAAABAAIADgCIAEgBIADAAQAFAAADAEIAuA9IADABIACAAIABgCIAAg6QAAAAABgBQAAAAAAgBQAAAAABAAQAAAAABAAIADgCIAEAAIAEAAQAFAAACAEIAABsQAAABgBAAQAAABgBAAQAAABAAAAQgBAAAAABQgBAAAAAAQgBAAAAABQgBAAgBAAQAAAAgBAAg");
	this.shape_6.setTransform(-33.4,-0.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.datefive, new cjs.Rectangle(-41.4,-10.2,82.9,20.6), null);


(lib.ctarectangle = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D63900").s().p("AqdCrIAAlVIU7AAIAAFVg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.ctarectangle, new cjs.Rectangle(-67,-17.1,134.1,34.3), null);


(lib.blackwideskyscraper = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("EgRBA2FMAAAhsJMAiDAAAMAAABsJg");
	this.shape.setTransform(0,0,0.753,0.867);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.blackwideskyscraper, new cjs.Rectangle(-82.1,-300,164.3,600.1), null);


(lib.blackrectangleinbox = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("EgXHgukMAuPAAAMAAABdJMguPAAAg");
	this.shape.setTransform(0,0,1.01,1.005);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-150.5,-300.5,301,601);


(lib.atasteof = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ag0CGQgJgDAAgHQAAgGAJgDIAEgCQAFgDACgGQACgGAAgQIAAgSIAAhaIgWAAQgEAAgBgBQgCgCAAgGIAAgEQAAgFACgCQACgCAEAAIAUAAIgCgPIgBgNQAAgcARgQQARgQAeAAQAWAAANAKQANAJAAAPQAAAJgFAEQgEAFgKAAQgGAAgEgDQgFgCgDgFIgEgHQgHgOgKAAQgHAAgEAFQgEAFAAAHIAEAVQADAQABANIAbAAQAFAAABACQACACAAAFIAAAEQAAAFgCACQgCACgEAAIgbAAIAABgQAAAYACAHQABAIAEABIAHADQALAEAAAHQAAAIgJACQgJADgbAAQgbAAgJgDg");
	this.shape.setTransform(82.8,0);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AhDBGQgbgbAAgqQAAgpAcgcQAcgdApAAQAoAAAaAbQAaAaAAApQAAArgcAdQgbAcgoAAQgoABgbgcgAgjg3QgLAPAAAaQAAAkAPAYQAQAZAWAAQASAAAMgPQALgQAAgZQAAgkgQgYQgPgZgWAAQgSAAgMAPg");
	this.shape_1.setTransform(65.4,4.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("Ag8BGQgbgbAAgoQAAgrAcgcQAbgdAqAAQAjABAWAUQAVAVAAAjQAAAMgDADQgEADgOAAIhHAAQgGAAgDgCQgEgEAAgEQAAgFAEgDQADgDAGAAIAmAAIAJgBQADgBAAgFQAAgSgMgMQgMgNgRAAQgWAAgLAUQgLATAAAcQAAAcAPAVQAPAWAXAAQAOAAAKgDQAJgEAJgGIAGgFQAKgIAFABQAEAAADACQADADAAAEQAAAEgFAHQgEAHgJAFQgQAOgPAGQgPAFgSAAQgmAAgbgbg");
	this.shape_2.setTransform(34.7,4.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgKBxQgJgDgHgGQgGgHgDgKQgDgKAAgcIAAhkIgRAAIgFgBIgCgFIAAgFQABgFATgRIAHgHIAIgHQAUgRAGAAIAGADQAAAAAAAAQABABAAAAQAAABAAAAQAAABAAAAIAAAkIArAAQAEAAACABQACADAAAEIAAAFQgBAFgCACQgCACgDAAIgnAAIgDACIgBAEIAABdQAAAXAEAHQAEAFALABQAGgBAJgDIANgCQAEgBADADQACADAAADQABAKgRAKQgPAJgVAAQgKAAgKgCg");
	this.shape_3.setTransform(18.3,2.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgNBhIgUgDIgGADIgGABIgDAAIgEgDQgGgFgGgPQgFgPAAgOQAAgGADgEQADgEAFAAQAJAAAIAPIAIALQAFAIAKAEQAKAEAKAAQAMAAAHgGQAHgGAAgLQAAgPgegQIgLgFQgdgOgKgMQgLgMAAgSQAAgYARgPQARgQAcAAIAMABIANACIAJgDIAGgBQAJAAAJAPQAIAOAAARQAAAGgDAEQgCAEgGAAQgEAAgEgEQgEgDgGgKQgHgLgIgFQgHgEgLAAQgKAAgGAGQgHAGAAAKQAAAIAHAHQAHAHAWALIACABQA0AZAAAeQAAAagTASQgVARgeAAg");
	this.shape_4.setTransform(3.3,4.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAhBYIgKgKIgIAEQgWAQgYAAQgbAAgRgQQgQgQgBgaQABgeAVgPQAWgRAnAAQAJAAAEADQAFACABAHQAAALgOAAQgRAAgMAJQgLAJAAAPQAAAPAKAJQAJAJARAAQARAAAIgIQAIgIAAgTIAAhHQAAgQgIgJQgGgJgNAAQgJAAgIAEQgHAEgIAIIgEAFQgLAPgNAAQgIAAgEgFQgFgFABgIQgBgSAWgMQAWgMAiAAQAUAAAPAGQAPAFAIALQAGAHACALQACAMAAAbIAAA7QAAALACAFQACAFAEABIAFACQAMADABAGQAAAJgNAIQgNAHgRAAQgHAAgKgKg");
	this.shape_5.setTransform(-14.4,4.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgnCFQgKgDAAgJQAAgHAKgEQAKgEACgDQACgCABggIABhYIAAgxIgCgdQgBgFgDgCQgDgCgIAAIgIAAQgNAAgHADQgHAEgFAGIgGANIgFANIgGAGQgDACgEAAQgFAAgDgFQgCgFAAgLQAAgZAFgPQAGgPAJgBIACABQAPACAXAAIBtAAQAXAAAPgCIACgBQAJABAGAPQAFAPAAAZQAAALgCAFQgDAFgGAAIgGgCIgFgGIgGgNIgGgNQgFgGgHgEQgIgDgNAAIgHAAQgIAAgDACQgDACgBAFIgCAdIAAAxIABBYQABAgACACQACADAKAEQAKAEAAAHQAAAJgKADQgLADgdABQgcgBgLgDg");
	this.shape_6.setTransform(-36.8,0.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AApCGQgMgDAAgJQAAgHAOgEIADgBQAFgCACgDQACgDAAgEIgDgPIgHgVIgDgFIgCgBIgPgCIgcgBIgQAAQgQAAAAgNQAAgPAQAAIAJAAIATAAIAUABIgUgyIgSgsIgEAAIgUAuIgSAwIgTAxQgDAKAAAHQgBAGADAEQACAEAGACIAHADQALADAAAIQAAAJgKADQgJADgcABQgdgBgJgDQgKgDABgJQAAgHALgEIAHgEQAOgJAMgfIAEgMIAbhDIAHgQQAbhDAGgcQADgIADgDQAEgCALgBQAFAAAFAEQADACAFAHIAcA+IAlBXIAIAXQAWA2ANAHIAGACQAMAEAAAHQgBAJgKADQgMADghABQghgBgLgDg");
	this.shape_7.setTransform(-72.7,0);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.atasteof, new cjs.Rectangle(-88.5,-24.2,177.1,48.5), null);


(lib.whitelogo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AqoZNQk7iFjyjyQjyjziFk6QiJlFAAljQAAlkCJlFQCFk6DyjzQDzjyE6iFQFFiJFjAAQFkAAFFCJQE6CFDyDyQDyDzCGE6QCJFFAAFkQAAFjiJFFQiGE6jyDzQjyDyk6CFQlFCJlkAAQljAAlFiJgALTMVIgBANQgBAOALAAIAxAAQAMAAABALIAACUQAAAHAEADQAFABAJAAQAKAAAEgBQAFgDAAgHIAAiUQgBgLAMAAIAyAAQALABAAgTQAAgRgMAAIifAAQgIAAgBAIgADSOMIBBBGQAHAJATgBQAOAAAEgEQAGgFgIgJIhOhVQgJgKAJgIIBAg7QAKgJgMgLQgMgMgNALIhKBDQgFAFgEABQgFADgLgBQgJABAAgNIAAg3QAAgMgSgBQgKAAgEACQgGADAAAIIAAC1QABAMAQAAQAVABAAgMIAAg8QAAgGAEgFQADgFAFAAQATABALAIgAhwOXQALAAAGAJIAfAxQAHAKARgBQAOAAAEgEQAFgEgFgIIgjgxQgDgGAHgHQAPgKAIgJQAPgQAAgXQAAgggVgTQgUgTggAAIhrAAQgKABABAHIAAC7QAAALAMAAIAPAAQAKgCAAgGIAAgxQgBgEAEgDQAEgDADAAgAmQOxQAHAAADAGIAOAbQADAJAPgBQAHAAAHgBQAJgEgDgGIhYi7QgEgJgMAAQgKAAgFAKIhZC5QgGAMAXAAQASAAACgIIAMgWQAFgLAJAAgArGNkIANBsQABAFAFADQAFADAFgBQAXAAgBgKIgVi2QgCgIgEgDQgDgCgGgBQgLABgEAHIg8BRQgHAIgDAAQgFgBgFgHIg5hPQgEgJgKAAQgLAAgEAFQgEADgBAJIgVCyQAAAFAGADQAFADAFgBQAUAAABgKIAPhqQAAgGAGgBQAEABACADIAtA8QAEAGAHAAQAGAAAEgFIAwg/QADgDAEgBQAFABACAGgAGyMbIAACvQAAAPAMAAICdAAQAKgBAAgQQAAgTgKAAIh6AAQgKAAAAgKIAAgfQAAgKALAAIBGAAQALAAgBgSQAAgSgKAAIhHAAQgKAAAAgJIAAgcQABgIAIgBIB6AAQAHABADgGQACgEAAgJQAAgJgCgDQgDgFgGAAIidAAQgMAAAAAOgAT4IxQgMAMAAATQAAASAMANQAOANARAAQATAAANgNQANgNAAgSQAAgTgNgMQgNgOgTAAQgRAAgOAOgAP5JKQAlAMA0AAQBUAAAzgsQAzgtgBhKQAAgggMgfQgMgegWgXQgUgVgXgSQgWgRgzgjIgqgeQgbgWgMgSQgJgLAAgXQAAgaARgPQASgQAdAAQAtAAAjAbQAOALAGAHQAHAHAOAVQAKAPAMAAQAKgBAIgFQAHgGAAgJQgBgIgBgEIgUhbQgGgZgSAAQgFABgDABIgKAGQgLAHgIAAIgMgBIgVgGQgkgIgmAAQhGAAgrAmQgrAmAAA9QAAA0AgAlQATAXASAOIBOA4QA/ArAbAdQAbAfABAhQgBAigZAVQgaAUgqAAQgkAAghgSQgigRgWgfIgMgRQgJgMgMAAQgMAAgHAHQgIAJAAALQAAAJACAIIAVBVQAFAPAFAGQAGAHALAAQAJAAALgIQAJgJAJAAIASAFgAjRF+QAHAAACALIABACQAYBeBGA2QBGA2BlABQCCgBBMhQQBMhRAAiIQAAiFhMhQQhMhQiAAAQhmAAhHA3QhGA2gYBfIgBABQgBAKgIABQgHABgCgMQgWhfhHg3QhIg3hpAAQh/AAhMBQQhLBRgBCIQAACFBNBRQBLBQB+AAQBogBBIg2QBGg2AYhfIABgCQACgKAGAAIABAAgAFmIeQgFAHAAAKQAAANAKAFQAGADAVADQBdANBrABQBGgBAwgOQAxgNAlgeQAugmAag9QAZg+AAhNQAAhFgUg4QgUg4glglQgngog0gSQg2gShPAAQhrAAhdANQgVADgGADQgKAGAAAMQAAALAFAGQAHAIAIgBIARAAQAKABAFAKQACALABAXIAAF5QgBAYgCAKQgFALgKAAIgRAAQgIAAgHAHgAyyIgQgGAGgBALQAAAOAJAFQAIAFAXAAICcAAQAXAAAKgFQAIgFABgOQgBgLgFgGQgHgIgKAAIgTAAQgMABgGgLQgCgHAAgbIAAiKQAAgZAIgGQAEgDAeAAIBGAAQAbAAAHADQAIAEACAMIAAAGQAEAWATAAQAOAAAFgJQAFgIAAgWIAAhIQAAgWgFgJQgFgJgOAAQgTAAgEAWIAAAEQgCANgIADQgHAEgbAAIhGAAQgdAAgFgDQgIgGAAgZIAAhkQgBgjAJgIQAIgJAjAAIBtAAQAgAAAMAEQAQAFAFAQQAFANAEAFQAHANAOAAQANAAAFgIQAEgJgDgRIgMg6QgFgWgaABIlvAAQgWgBgJAGQgIAFgBAOQABAKAGAHQAHAHAJAAIARAAQAEAAAEADQAEAEABAFQAEALAAAXIAAF7QAAAYgDAKQgEALgKgBIgRAAQgJAAgHAIgACnrWQADAJgKADQgoAOgmATQgmATgYATQg6AngfBDQghBDAABZQAACLBPBUQBOBUCEAAQCHAABQhUQBQhVgBiOQABikhphOQg7gsg3AGQgiAEgFATQgEAUAaAKQA2AUAZA7QAXA4AABfQAABwgqBCQgrBChJAAQhMAAgphAQgrhBAAhxQAAhRAQgyQATg/AvgvQAegdBGgjQA+geAigsQAUgZAAgVQABgTgPgFQgMgDgNAMIgYAXQgvAfg4gTQgugOglgpQgbgfgogIQgcgGggAHQgKADgDgHQgEgHALgIQAcgVAqACQAvABAfAdQAeAbAgAPQAkAQAagEQARgDAAgPQAAgOgSgGQgggMgmg2Qglgzg1gQQhPgWhJA8QhDA4gYBWQgGAXALALQANALAUgJQA6gaAvAXQAJAEAhATQAcASAWAJQAsASA7gLIAGgBQAIAAABAIgAvDlQIBJDYQAHAYALAKQALAJATAAQATAAAKgLQALgMAJgeICHm0QAHgWAHgJQAIgJALgBQAjgFAAAxIAAF9QAAAbgCAHQgBAEgFADQgEADgFAAIgRAAQgIAAgHAHQgGAHAAAKQAAAOAIAFQAIAFAWAAICbAAQAUAAAIgFQAIgFAAgNQABgLgGgHQgGgHgJAAIgQAAQgLAAgGgKQgCgKAAgYIAAiBQABgdAFgHQAGgGAXgBIB0AAQAXABAGAHQADAEABAGIABAeIAAB8QAAAbgDAHQgGAKgJAAIgQAAQgJAAgHAHQgHAHAAAKQABAOAHAFQAJAFAWAAICaAAQAWAAAJgFQAIgFAAgOQAAgKgGgHQgGgHgJAAIgSAAQgFAAgDgDQgFgDgCgEQgCgLAAgXIAAl9QAAgYACgKQACgEAFgEQADgCAFAAIASAAQAIgBAHgGQAGgHAAgLQABgOgKgFQgIgFgWAAIiaAAQgWAAgJAFQgJAFAAAOQAAALAHAHQAGAGALABIAQAAQAKAAAFAKQADAGAAAcIAABoIgBAeQgBAHgDADQgGAIgXAAIh0AAQgXAAgGgHQgFgGgBgeIAAhtQAAgaACgIQAGgKALAAIAQAAQAJgBAGgGQAGgHAAgLQAAgOgIgFQgIgFgVAAIkmAAQgRAAgIAFQgHAHgBAMQABAVAbADQAdADAAASQABAJgEAMIheE6QgBAGgFAAQgEABgCgFIhfkuQgJgZABgKQAAgLAFgGQAGgEARgCQAbgEABgTQAAgXgdAAIinAAQgeAAABAZQAAAKAFAFQAFAFAOAEQAPADAGAFQAHAEADAJIAmBvQAHAXgJAZIg+C2QgCAGgFABQgEAAgCgGIhzlHQgDgKAAgJQgBgKAHgFQAGgFAOgBQARgCAGgEQAIgFAAgLQAAgXgcAAIiwAAQgcAAAAAWQAAAKAFAGQAFAFAOACQAUAEAHAIQAHAHAKAaICmG+QAJAZAKAJQALAJATAAQAQAAANgJQAGgHALgbIBMjYQACgEAFAAQADAAACAEgAOkiCQgGAHAAAKQAAAOAIAFQAJAGAVAAIFigBQAOAAAHgFQAHgFADgLIANhCQAEgQgFgJQgGgJgLAAQgPABgJAQIgHAPQgPAfgvAAIhVAAQgjAAgPgFQgKgEgDgLQgDgLAAgiIAAhrQAAgaAIgFQAEgDAfgBIAnAAQAaABAIADQAHADACANIABAGQAEAWASgBQAOABAFgJQAGgJgBgWIAAhIQABgWgGgIQgFgJgOAAQgTAAgDAVIgBAFQgCANgHADQgHAEgbAAIgnAAQgfAAgEgEQgIgEAAgaIAAhlQAAgiAJgJQAIgJAjAAIBPAAQAgABAMADQAPAGAHAPQAFAQADADQAHANAOgBQAMAAAGgIQAEgJgDgQIgMg7QgEgVgaAAIlTAAQgVAAgJAFQgJAGAAANQAAAKAGAHQAIAIAIgBIARAAQAEABAEADQAEADABAGQAEAIAAAZIAAF8QAAAagEAIQgBAFgDADQgEADgFAAIgRAAQgIAAgHAGgAHziCQgHAHAAAKQAAAOAIAFQAIAFAWAAIE/AAQAaAAAEgVIAOhCQADgQgFgJQgFgJgMAAQgPABgIAQIgIAPQgOAfgwAAIgwAAQgaABgLgCQgLgCgHgEQgHgFgCgJQgCgJAAgdIAAlkQAAgcACgGQADgLAPAAIASAAQAJAAAHgGQAHgHgBgLQAAgNgJgGQgIgFgXAAIidAAQgWAAgJAFQgJAGAAANQABALAGAHQAHAGAKAAIAQAAQALAAADALQADAJAAAZIAAGAQAAAXgDAIQgCAEgEAEQgEADgEAAIgQAAQgKAAgFAGg");
	this.shape.setTransform(0,0,0.223,0.223);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgYAZQgKgKAAgPQAAgOAKgLQAKgJAOgBQAPABAKAJQAKALAAAOQAAAPgKAKQgKALgPgBQgOABgKgLgAAWAYIgPgVQANgBAAgNQAAgPgRAAIgTAAIAAAyIAJAAIAAgUIAFAAIAOAUIAKAAg");
	this.shape_1.setTransform(29.1,13.2,0.223,0.223);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgrAiQgFAAgEgDQgEgDAAgFIAAgtQAAgLANAAIA+AAQARAAAKAJQALAJAAAPQAAAQgLAJQgKAJgRAAg");
	this.shape_2.setTransform(-2.5,18.9,0.223,0.223);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgJAHIAAgNIAIAAQALAAAAAGQAAAHgNAAg");
	this.shape_3.setTransform(29.1,12.9,0.223,0.223);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhvCtQgog+AAhsQAAhuAog/QApg/BFAAQBGAAAqBAQApA+AABsQAABrgpA/QgpA/hGAAQhGAAgpg9g");
	this.shape_4.setTransform(-10.9,6.7,0.223,0.223);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgYAfQgIAAADgIIAZgxQABgEADAAQADAAACAEIAZAyQABADgCACQAAABgBAAQAAAAgBABQAAAAgBAAQAAAAgBAAg");
	this.shape_5.setTransform(-9.9,19.6,0.223,0.223);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgtDtQgngDgNgHQgVgLAAghIAAljQAAghAKgMQAKgLAcgFIAdgDQBLAAAqA/QArA/AABvQAABxgrA/QgqA8hGAAIgJAAg");
	this.shape_6.setTransform(14.4,6.7,0.223,0.223);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AhvCtQgog/AAhrQAAhuAog/QApg/BGAAQBFAAAqBAQApA+AABsQAABrgpA/QgpA/hGAAQhGAAgpg9g");
	this.shape_7.setTransform(1.5,6.7,0.223,0.223);

	this.instance = new lib.Path();
	this.instance.parent = this;
	this.instance.setTransform(0.1,0,0.223,0.223,0,0,0,164.9,164.9);
	this.instance.alpha = 0.359;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.whitelogo, new cjs.Rectangle(-39,-39,78,78), null);


// stage content:
(lib.halfpagebanneratasteoffivesimple = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_66 = function() {
		//onhover event to reveal green cta rectangle over orange rectangle
		this.btn_main.addEventListener("mouseover", fl_MouseOverHandler.bind(this));
		this.btn_main.addEventListener("mouseout", fl_MouseOutHandler.bind(this));
		
		function fl_MouseOverHandler()
		{
			this.cta_rollover.gotoAndPlay(2);
		}
		
		function fl_MouseOutHandler()
		{
		this.cta_rollover.gotoAndPlay(13);
		}
	}
	this.frame_275 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(66).call(this.frame_66).wait(209).call(this.frame_275).wait(14));

	// button
	this.btn_main = new lib.mainbutton();
	this.btn_main.parent = this;
	this.btn_main.setTransform(150.3,301.6,1.456,0.919,0,0,0,0.2,0.1);
	new cjs.ButtonHelper(this.btn_main, 0, 1, 2, false, new lib.mainbutton(), 3);

	this.timeline.addTween(cjs.Tween.get(this.btn_main).wait(289));

	// black-rectangle
	this.instance = new lib.blackrectangleinbox("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(289));

	// fade-from-white
	this.instance_1 = new lib.blackwideskyscraper();
	this.instance_1.parent = this;
	this.instance_1.setTransform(150.2,300,1.826,1,0,0,0,0.1,0);
	this.instance_1.filters = [new cjs.ColorFilter(0, 0, 0, 1, 255, 255, 255, 0)];
	this.instance_1.cache(-84,-302,168,604);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({alpha:0},9).wait(280));

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("EgV3AjuMAAAgzaMAs2AAAMAAAAzag");
	mask.setTransform(147.1,228.6);

	// thanksgiving
	this.instance_2 = new lib.thanksgiving();
	this.instance_2.parent = this;
	this.instance_2.setTransform(150,251.5);
	this.instance_2.alpha = 0;

	var maskedShapeInstanceList = [this.instance_2];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(187).to({x:-115.6},0).to({x:160,alpha:1},10).to({x:150},6).wait(30).to({alpha:0},5).wait(51));

	// mask (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	mask_1.graphics.p("EgV3AjuMAAAgzaMAs2AAAMAAAAzag");
	mask_1.setTransform(147.1,228.6);

	// delicious-desserts
	this.instance_3 = new lib.halfpagedeliciousdesserts();
	this.instance_3.parent = this;
	this.instance_3.setTransform(150,277.3);
	this.instance_3.alpha = 0;

	var maskedShapeInstanceList = [this.instance_3];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(141).to({x:-80.9},0).to({x:170,alpha:1},10).to({x:150},6).wait(30).to({alpha:0},5).wait(97));

	// mask (mask)
	var mask_2 = new cjs.Shape();
	mask_2._off = true;
	mask_2.graphics.p("EgV3AjuMAAAgzaMAs2AAAMAAAAzag");
	mask_2.setTransform(147.1,228.6);

	// savory-sides
	this.instance_4 = new lib.savorysides();
	this.instance_4.parent = this;
	this.instance_4.setTransform(150,251.5);
	this.instance_4.alpha = 0;

	var maskedShapeInstanceList = [this.instance_4];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_2;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(95).to({x:-109.5},0).to({x:160,alpha:1},10).to({x:150},6).wait(30).to({alpha:0},5).wait(143));

	// mask (mask)
	var mask_3 = new cjs.Shape();
	mask_3._off = true;
	mask_3.graphics.p("EgV3AjuMAAAgzaMAs2AAAMAAAAzag");
	mask_3.setTransform(147.1,228.6);

	// a taste of
	this.instance_5 = new lib.atasteof();
	this.instance_5.parent = this;
	this.instance_5.setTransform(143.2,201.6);
	this.instance_5.alpha = 0;

	var maskedShapeInstanceList = [this.instance_5];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_3;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(33).to({x:-88},0).to({x:163.2,alpha:1},10).to({x:142.9},6).wait(184).to({alpha:0},5).wait(51));

	// mask (mask)
	var mask_4 = new cjs.Shape();
	mask_4._off = true;
	mask_4.graphics.p("EgV3AjuMAAAgzaMAs2AAAMAAAAzag");
	mask_4.setTransform(147.1,228.6);

	// whole-foods-market
	this.instance_6 = new lib.wholefoodsmarket();
	this.instance_6.parent = this;
	this.instance_6.setTransform(150,277.3);
	this.instance_6.alpha = 0;

	var maskedShapeInstanceList = [this.instance_6];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_4;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(43).to({x:-114.2},0).to({x:160,alpha:1},10).to({x:150},6).wait(36).to({alpha:0},5).wait(189));

	// mask (mask)
	var mask_5 = new cjs.Shape();
	mask_5._off = true;
	mask_5.graphics.p("EgV3AjuMAAAgzaMAs2AAAMAAAAzag");
	mask_5.setTransform(147.1,228.6);

	// date
	this.instance_7 = new lib.datefive();
	this.instance_7.parent = this;
	this.instance_7.setTransform(150,342.2);
	this.instance_7.alpha = 0;

	var maskedShapeInstanceList = [this.instance_7];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_5;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(53).to({x:-40.9},0).to({x:160,alpha:1},10).to({x:150},6).wait(220));

	// mask (mask)
	var mask_6 = new cjs.Shape();
	mask_6._off = true;
	mask_6.graphics.p("EgV3AjuMAAAgzaMAs2AAAMAAAAzag");
	mask_6.setTransform(147.1,228.6);

	// for your feast
	this.instance_8 = new lib.foryourfeast();
	this.instance_8.parent = this;
	this.instance_8.setTransform(150,251.5);
	this.instance_8.alpha = 0;

	var maskedShapeInstanceList = [this.instance_8];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_6;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(250).to({alpha:1},10).wait(29));

	// find-an-event
	this.instance_9 = new lib.findanevent();
	this.instance_9.parent = this;
	this.instance_9.setTransform(150,385.3);
	this.instance_9.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(63).to({x:-66.5},0).to({x:160,alpha:1},10).to({x:150},6).wait(210));

	// cta-mask (mask)
	var mask_7 = new cjs.Shape();
	mask_7._off = true;
	mask_7.graphics.p("EgKAAjuIAAvOMAg/AAAIAAPOg");
	mask_7.setTransform(147.1,228.6);

	// cta-rectangle
	this.instance_10 = new lib.datefive();
	this.instance_10.parent = this;
	this.instance_10.setTransform(150,342.2);
	this.instance_10.alpha = 0;

	this.instance_11 = new lib.ctarectangle();
	this.instance_11.parent = this;
	this.instance_11.setTransform(150,384.9);
	this.instance_11.alpha = 0;

	var maskedShapeInstanceList = [this.instance_10,this.instance_11];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_7;
	}

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_11},{t:this.instance_10}]}).to({state:[{t:this.instance_11}]},63).to({state:[{t:this.instance_11}]},10).to({state:[{t:this.instance_11}]},6).wait(210));
	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(63).to({x:-66.5},0).to({x:160,alpha:1},10).to({x:150},6).wait(210));

	// mask (mask)
	var mask_8 = new cjs.Shape();
	mask_8._off = true;
	mask_8.graphics.p("EgV3AjuMAAAgzaMAs2AAAMAAAAzag");
	mask_8.setTransform(147.1,228.6);

	// tasting-event-near-you
	this.instance_12 = new lib.halfpagetastingeventnearyou();
	this.instance_12.parent = this;
	this.instance_12.setTransform(149.7,165.6);
	this.instance_12.alpha = 0;

	var maskedShapeInstanceList = [this.instance_12];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_8;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(9).to({x:-111.3},0).to({x:159.7,alpha:1},10).to({x:149.7},6).wait(264));

	// mask (mask)
	var mask_9 = new cjs.Shape();
	mask_9._off = true;
	mask_9.graphics.p("EgV3AjuMAAAgzaMAs2AAAMAAAAzag");
	mask_9.setTransform(147.1,228.6);

	// try-new-flavors
	this.instance_13 = new lib.trynewflavors();
	this.instance_13.parent = this;
	this.instance_13.setTransform(150,207.6);
	this.instance_13.alpha = 0;

	var maskedShapeInstanceList = [this.instance_13];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_9;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(240).to({y:201.6},0).to({alpha:1},10).wait(39));

	// logo
	this.instance_14 = new lib.whitelogo();
	this.instance_14.parent = this;
	this.instance_14.setTransform(150,37,1.296,1.296);
	this.instance_14.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_14).wait(9).to({scaleX:0.11,scaleY:0.11,y:37.1},0).to({scaleX:1.3,scaleY:1.3,y:37,alpha:1},6).to({scaleX:1.21,scaleY:1.21},7).wait(267));

	// turkey
	this.instance_15 = new lib.halfpageturkey_1();
	this.instance_15.parent = this;
	this.instance_15.setTransform(176,464.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_15).wait(289));

	// cranberries
	this.instance_16 = new lib.halfpagecranberries_1();
	this.instance_16.parent = this;
	this.instance_16.setTransform(57.5,564);

	this.timeline.addTween(cjs.Tween.get(this.instance_16).wait(289));

	// orange-fruit
	this.instance_17 = new lib.halfpageorange_1();
	this.instance_17.parent = this;
	this.instance_17.setTransform(50,68.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_17).wait(289));

	// potatoes
	this.instance_18 = new lib.halfpagepotatoes_1();
	this.instance_18.parent = this;
	this.instance_18.setTransform(44,399.8);

	this.timeline.addTween(cjs.Tween.get(this.instance_18).wait(289));

	// greens
	this.instance_19 = new lib.halfpagegreens_1();
	this.instance_19.parent = this;
	this.instance_19.setTransform(229.5,91.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_19).wait(289));

	// table
	this.instance_20 = new lib.halfpagetable_1();
	this.instance_20.parent = this;
	this.instance_20.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.instance_20).wait(289));

	// trace
	this.instance_21 = new lib.halfpagetrace();
	this.instance_21.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_21).wait(289));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(149.5,286.5,301,616.6);
// library properties:
lib.properties = {
	id: '85088BD5353243C8B4895C262600CED3',
	width: 300,
	height: 600,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	webfonts: {},
	manifest: [
		{src:"images/index_atlas_.png", id:"index_atlas_"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['85088BD5353243C8B4895C262600CED3'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;